import { AlertTriangle, BadgeCheck, Landmark } from "lucide-react";
import { redirect } from "next/navigation";
import { VatProfileCard } from "@/components/vat-profile-card";
import { TaxPaymentMatch } from "@/components/tax-payment-match";
import styles from "@/components/taxes.module.css";
import { fiscalYearBounds, getActiveFiscalYear } from "@/lib/fiscal-year";
import { createClient } from "@/lib/supabase/server";
import { getWorkspace } from "@/lib/workspace";

export const dynamic="force-dynamic";
function money(v:number,c="EUR"){return new Intl.NumberFormat("en-LU",{style:"currency",currency:c,minimumFractionDigits:2}).format(v)}

export default async function TaxesPage(){
 const workspace=await getWorkspace();if(!workspace.authenticated)redirect("/sign-in");if(!workspace.company)redirect("/setup");const year=await getActiveFiscalYear(workspace.company.fiscal_year_start_month),bounds=fiscalYearBounds(year,workspace.company.fiscal_year_start_month),currency=workspace.company.base_currency||"EUR",supabase=await createClient();
 const[entriesResult,accountsResult,invoicesResult,pendingResult,aedResult,taxEventsResult,bankResult]=await Promise.all([
  supabase.from("journal_entries").select("id").eq("company_id",workspace.company.id).eq("status","posted").gte("entry_date",bounds.start).lte("entry_date",bounds.end),
  supabase.from("company_accounts").select("id,code").eq("company_id",workspace.company.id).in("code",["461411","421611"]),
  supabase.from("sales_invoices").select("id,vat_treatment,subtotal").eq("company_id",workspace.company.id).eq("status","issued").gte("service_date",bounds.start).lte("service_date",bounds.end),
  supabase.from("source_transactions").select("id,vat_amount,classification_status").eq("company_id",workspace.company.id).neq("classification_status","posted").gt("vat_amount",0).gte("occurred_on",bounds.start).lte("occurred_on",bounds.end),
  supabase.from("compliance_obligations").select("id,obligation_type,due_date,status,period_label").eq("company_id",workspace.company.id).eq("authority","AED").order("due_date",{ascending:true}),
  supabase.from("tax_events").select("id,authority,tax_type,tax_year,amount,due_date,reference,status,bank_transaction_id,source_document_id").eq("company_id",workspace.company.id).or(`tax_year.eq.${year},tax_year.is.null`).order("due_date",{ascending:true,nullsFirst:false}),
  supabase.from("bank_transactions").select("id,booking_date,amount,counterparty_name,reference,match_status").eq("company_id",workspace.company.id).lt("amount",0).gte("booking_date",bounds.start).lte("booking_date",bounds.end).order("booking_date",{ascending:false}).limit(200)
 ]);
 if([entriesResult,accountsResult,invoicesResult,pendingResult,aedResult,taxEventsResult,bankResult].some(r=>r.error))throw new Error("Could not load the tax workspace.");
 const entries=entriesResult.data??[],accounts=accountsResult.data??[],accountMap=new Map(accounts.map(a=>[a.id,a.code]));let outputVat=0,inputVat=0;if(entries.length&&accounts.length){const{data}=await supabase.from("journal_lines").select("company_account_id,debit,credit").in("journal_entry_id",entries.map(e=>e.id)).in("company_account_id",accounts.map(a=>a.id));for(const line of data??[]){const code=accountMap.get(line.company_account_id);if(code==="461411")outputVat+=Number(line.credit)-Number(line.debit);if(code==="421611")inputVat+=Number(line.debit)-Number(line.credit)}}
 const invoices=invoicesResult.data??[],euInvoices=invoices.filter(i=>i.vat_treatment==="eu_b2b_reverse_charge"),position=outputVat-inputVat,pendingVat=(pendingResult.data??[]).length,aedRows=(aedResult.data??[]).filter(o=>!o.period_label||String(o.period_label).includes(String(year))),nextAed=aedRows.find(o=>!['paid','filed'].includes(o.status))??null,taxEvents=taxEventsResult.data??[],bankRows=bankResult.data??[];
 return <div className={styles.page}><div className={styles.intro}><div><p>Taxes & authority evidence · FY {year}</p><h1>Your {year} tax position.</h1><p>Ledger estimates stay separate from actual ACD/AED notices. The selected financial year controls ledger, invoice, notice and matching context.</p></div><span className={styles.verified}><BadgeCheck size={13}/>Evidence-led</span></div>
 <section className={styles.hero}><article className={styles.vatHero}><div className={styles.heroTop}><span>{year} VAT ledger</span><span className={styles.positionPill}>{position>0?"payable":position<0?"credit":"balanced"}</span></div><div className={styles.heroAmount}>{money(Math.abs(position),currency)}</div><div className={styles.heroLabel}>{position>0?"currently reserved for AED":position<0?"current VAT credit":"no net VAT due from posted entries"}</div><div className={styles.vatSplit}><div><span>Output VAT</span><strong>{money(outputVat,currency)}</strong></div><div><span>Input VAT</span><strong>{money(inputVat,currency)}</strong></div></div></article><VatProfileCard frequency={workspace.company.vat_filing_frequency} year={year}/></section>
 <section className={styles.metrics}><article><span>{year} tax notices</span><strong>{taxEvents.length}</strong><small>Imported authority evidence</small></article><article><span>Open notice amount</span><strong>{money(taxEvents.filter(e=>e.status!=="paid").reduce((n,e)=>n+Number(e.amount??0),0),currency)}</strong><small>Actual notices, not estimates</small></article><article><span>VAT items to review</span><strong>{pendingVat}</strong><small>Unposted VAT evidence · {year}</small></article><article><span>Next AED cutoff</span><strong>{nextAed?.due_date?new Date(`${nextAed.due_date}T12:00:00`).toLocaleDateString("en-LU",{day:"2-digit",month:"short"}):"—"}</strong><small>{nextAed?.obligation_type??`No ${year} AED obligation found`}</small></article></section>
 <section className={styles.contentGrid}><div><article className={styles.rateCard}><div className={styles.rateHead}><div><p className={styles.sectionKicker}>Authority cases · {year}</p><h2>Tax notices & payments</h2></div><span>{taxEvents.filter(e=>e.status!=="paid").length} open</span></div>{taxEvents.length===0?<div style={{padding:"22px 0",fontSize:12,color:"var(--muted)"}}>No {year} tax notices converted yet. Upload an ACD/AED notice in Documents, run extraction, then choose “Create tax case”.</div>:<div className={styles.rateRows}>{taxEvents.map(event=>{const candidates=bankRows.filter(b=>event.amount==null||Math.abs(Math.abs(Number(b.amount))-Number(event.amount))<=.02).slice(0,8);return <div key={event.id} style={{padding:"12px 0",borderBottom:"1px solid var(--border)",display:"grid",gap:7}}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><div><strong style={{fontSize:12}}>{event.authority} · {event.tax_type.replaceAll("_"," ")}</strong><small style={{display:"block",color:"var(--muted)",marginTop:2}}>{event.tax_year??year}{event.reference?` · ${event.reference}`:""}{event.due_date?` · due ${new Date(`${event.due_date}T12:00:00`).toLocaleDateString("en-LU")}`:""}</small></div><div style={{textAlign:"right"}}><strong>{event.amount!=null?money(Number(event.amount),currency):"Amount not extracted"}</strong><small style={{display:"block"}}>{event.status}</small></div></div>{event.status!=="paid"?<TaxPaymentMatch taxEventId={event.id} candidates={candidates}/>:null}</div>})}</div>}</article>
 {euInvoices.length?<article className={styles.euCard}><div className={styles.euHead}><div><p className={styles.sectionKicker}>EU reporting signal · {year}</p><h2>Reverse-charge sales detected.</h2></div><Landmark size={18}/></div><div className={styles.euSignal}><div><span>EU B2B services</span><strong>{money(euInvoices.reduce((n,i)=>n+Number(i.subtotal),0),currency)}</strong></div><div><span>Invoices</span><strong>{euInvoices.length}</strong></div></div><div className={styles.euNote}><AlertTriangle size={14}/><span>Review the separate recapitulative statement workflow before submission.</span></div></article>:null}</div>
 <aside className={styles.readiness}><p className={styles.sectionKicker}>{year} tax control</p><h2>What is grounded.</h2><div className={styles.readinessRows}><div className={styles.readinessRow}><span>Posted VAT ledger</span><strong className={styles.good}>Live</strong></div><div className={styles.readinessRow}><span>Authority notice amounts</span><strong className={taxEvents.length?styles.good:styles.warning}>{taxEvents.length?"Imported":"Needs evidence"}</strong></div><div className={styles.readinessRow}><span>Bank payment matching</span><strong className={styles.good}>Year-scoped</strong></div><div className={styles.readinessRow}><span>Tax reserve estimates</span><strong className={styles.warning}>Estimate only</strong></div></div><p className={styles.sourceNote}>Actual tax liabilities remain notice-driven. Compta never converts a reserve estimate into a filed or assessed liability automatically.</p></aside></section></div>;
}
