import { AlertTriangle, BadgeCheck, Landmark, PiggyBank, ShieldCheck } from "lucide-react";
import { redirect } from "next/navigation";
import { VatProfileCard } from "@/components/vat-profile-card";
import { TaxPaymentMatch } from "@/components/tax-payment-match";
import { TaxProfileForm } from "@/components/tax-profile-form";
import styles from "@/components/taxes.module.css";
import reserve from "@/components/tax-reserve.module.css";
import { fiscalYearBounds, getActiveFiscalYear } from "@/lib/fiscal-year";
import { createClient } from "@/lib/supabase/server";
import { getWorkspace } from "@/lib/workspace";

export const dynamic="force-dynamic";
function money(v:number,c="EUR"){return new Intl.NumberFormat("en-LU",{style:"currency",currency:c,minimumFractionDigits:2}).format(v)}
function irc(profit:number){if(profit<=0)return 0;if(profit<=175000)return profit*.14;if(profit<=200001)return 24500+(profit-175000)*.30;return profit*.16}

export default async function TaxesPage(){
 const workspace=await getWorkspace();if(!workspace.authenticated)redirect("/sign-in");if(!workspace.company)redirect("/setup");const year=await getActiveFiscalYear(workspace.company.fiscal_year_start_month),bounds=fiscalYearBounds(year,workspace.company.fiscal_year_start_month),currency=workspace.company.base_currency||"EUR",supabase=await createClient();
 const[entriesResult,accountsResult,invoicesResult,pendingResult,aedResult,taxEventsResult,bankResult,profileResult]=await Promise.all([
  supabase.from("journal_entries").select("id").eq("company_id",workspace.company.id).eq("status","posted").gte("entry_date",bounds.start).lte("entry_date",bounds.end),
  supabase.from("company_accounts").select("id,code,account_type").eq("company_id",workspace.company.id).eq("is_active",true),
  supabase.from("sales_invoices").select("id,vat_treatment,subtotal").eq("company_id",workspace.company.id).eq("status","issued").gte("service_date",bounds.start).lte("service_date",bounds.end),
  supabase.from("source_transactions").select("id,vat_amount,classification_status").eq("company_id",workspace.company.id).neq("classification_status","posted").gt("vat_amount",0).gte("occurred_on",bounds.start).lte("occurred_on",bounds.end),
  supabase.from("compliance_obligations").select("id,obligation_type,due_date,status,period_label").eq("company_id",workspace.company.id).eq("authority","AED").order("due_date",{ascending:true}),
  supabase.from("tax_events").select("id,authority,tax_type,tax_year,amount,due_date,reference,status,bank_transaction_id,source_document_id").eq("company_id",workspace.company.id).or(`tax_year.eq.${year},tax_year.is.null`).order("due_date",{ascending:true,nullsFirst:false}),
  supabase.from("bank_transactions").select("id,booking_date,amount,counterparty_name,reference,match_status").eq("company_id",workspace.company.id).neq("match_status","ignored").lt("amount",0).gte("booking_date",bounds.start).lte("booking_date",bounds.end).order("booking_date",{ascending:false}).limit(300),
  supabase.from("company_tax_profiles").select("municipality,icc_multiplier,icc_multiplier_year,icc_verified_at,prior_closing_balance_total,prior_balance_year").eq("company_id",workspace.company.id).maybeSingle()
 ]);
 if([entriesResult,accountsResult,invoicesResult,pendingResult,aedResult,taxEventsResult,bankResult,profileResult].some(r=>r.error))throw new Error("Could not load the tax workspace.");
 const entries=entriesResult.data??[],accounts=accountsResult.data??[],accountMap=new Map(accounts.map(a=>[a.id,a]));let outputVat=0,inputVat=0,revenue=0,operatingExpense=0,bookBank=0;if(entries.length&&accounts.length){const{data}=await supabase.from("journal_lines").select("company_account_id,debit,credit").in("journal_entry_id",entries.map(e=>e.id));for(const line of data??[]){const a=accountMap.get(line.company_account_id);if(!a)continue;const d=Number(line.debit),c=Number(line.credit);if(a.code==="461411")outputVat+=c-d;if(a.code==="421611")inputVat+=d-c;if(a.account_type==="revenue")revenue+=c-d;if(a.account_type==="expense"&&!['6711','6721','6811'].includes(a.code))operatingExpense+=d-c;if(a.code==="5131")bookBank+=d-c}}
 const invoices=invoicesResult.data??[],euInvoices=invoices.filter(i=>i.vat_treatment==="eu_b2b_reverse_charge"),position=outputVat-inputVat,pendingVat=(pendingResult.data??[]).length,aedRows=(aedResult.data??[]).filter(o=>!o.period_label||String(o.period_label).includes(String(year))),nextAed=aedRows.find(o=>!['paid','filed'].includes(o.status))??null,taxEvents=taxEventsResult.data??[],bankRows=bankResult.data??[],profile=profileResult.data;
 const profit=Math.max(0,revenue-operatingExpense),ircTax=irc(profit),fund=ircTax*.07,profileYear=Number(profile?.icc_multiplier_year),multiplier=profileYear===year&&profile?.icc_multiplier!=null?Number(profile.icc_multiplier):null,icc=multiplier===null?null:Math.max(profit-17500,0)*.03*multiplier,vatPayable=Math.max(position,0),directEstimate=ircTax+fund+(icc??0),recommendedReserve=vatPayable+directEstimate,safeCash=bookBank-recommendedReserve,prior=profile?.prior_closing_balance_total==null?null:Number(profile.prior_closing_balance_total),ifMinimum=prior===null?null:prior<=350000?535:prior<=2000000?1605:4815;
 return <div className={styles.page}>
  <div className={styles.intro}><div><p>Taxes · FY {year}</p><h1>Your complete {year} tax position.</h1><p>Estimates, VAT, authority notices and reserve planning now live together. Estimated liabilities remain clearly separated from ACD/AED assessments.</p></div><span className={styles.verified}><BadgeCheck size={13}/>Evidence-led</span></div>
  <section className={styles.hero}><article className={styles.vatHero}><div className={styles.heroTop}><span>Estimated direct taxes · {year}</span><span className={styles.positionPill}>{multiplier===null?"ICC rate pending":"estimate complete"}</span></div><div className={styles.heroAmount}>{money(directEstimate,currency)}</div><div className={styles.heroLabel}>IRC + employment fund + {icc===null?"ICC awaiting municipality multiplier":"ICC"}</div><div className={styles.vatSplit}><div><span>Accounting profit proxy</span><strong>{money(profit,currency)}</strong></div><div><span>Recommended total reserve</span><strong>{money(recommendedReserve,currency)}</strong></div></div></article><VatProfileCard frequency={workspace.company.vat_filing_frequency} year={year}/></section>
  <section className={styles.metrics}><article><span>VAT position</span><strong>{money(Math.abs(position),currency)}</strong><small>{position>0?"Payable":position<0?"Credit":"Balanced"}</small></article><article><span>Safe-to-use book cash</span><strong>{money(safeCash,currency)}</strong><small>Book bank less recommended tax reserve</small></article><article><span>Open notice amount</span><strong>{money(taxEvents.filter(e=>e.status!=="paid").reduce((n,e)=>n+Number(e.amount??0),0),currency)}</strong><small>Actual notices, not estimates</small></article><article><span>Next AED cutoff</span><strong>{nextAed?.due_date?new Date(`${nextAed.due_date}T12:00:00`).toLocaleDateString("en-LU",{day:"2-digit",month:"short"}):"—"}</strong><small>{nextAed?.obligation_type??`No ${year} AED obligation found`}</small></article></section>
  <section className={reserve.grid} style={{marginBottom:12}}><article className={reserve.card}><div className={reserve.head}><div><p>Reserve stack · {year}</p><h2>What Compta recommends holding back</h2></div><PiggyBank/></div><div className={reserve.row}><span>VAT payable</span><strong>{money(vatPayable,currency)}</strong></div><div className={reserve.row}><span>IRC estimate</span><strong>{money(ircTax,currency)}</strong></div><div className={reserve.row}><span>Employment fund surcharge · 7% IRC</span><strong>{money(fund,currency)}</strong></div><div className={reserve.row}><span>ICC estimate</span><strong>{icc===null?`Confirm ${year} multiplier`:money(icc,currency)}</strong></div><div className={reserve.total}><span>Recommended current reserve</span><strong>{money(recommendedReserve,currency)}</strong></div>{ifMinimum!==null?<div className={reserve.ifBox}><span>Minimum IF context</span><strong>{money(ifMinimum,currency)}</strong><p>Raw statutory minimum from the prior closing balance total. It remains separate from the current reserve estimate.</p></div>:null}</article><article className={reserve.card}><div className={reserve.head}><div><p>Direct-tax profile · {year}</p><h2>Inputs that change the estimate</h2></div><ShieldCheck/></div><TaxProfileForm municipality={profile?.municipality??workspace.company.municipality??null} multiplier={multiplier} year={year} priorBalance={prior}/><p className={reserve.note}>{profileYear&&profileYear!==year?`A multiplier is stored for ${profileYear}, but Compta will not reuse it for ${year} without confirmation.`:"The municipal multiplier is stored with its year and verification timestamp."}</p></article></section>
  <section className={styles.contentGrid}><div><article className={styles.rateCard}><div className={styles.rateHead}><div><p className={styles.sectionKicker}>Authority cases · {year}</p><h2>Tax notices & payments</h2></div><span>{taxEvents.filter(e=>e.status!=="paid").length} open</span></div>{taxEvents.length===0?<div style={{padding:"22px 0",fontSize:12,color:"var(--muted)"}}>No {year} tax notices converted yet. Upload an ACD/AED notice in Documents, run extraction, then choose “Create tax case”.</div>:<div className={styles.rateRows}>{taxEvents.map(event=>{const candidates=bankRows.filter(b=>event.amount==null||Math.abs(Math.abs(Number(b.amount))-Number(event.amount))<=.02).slice(0,8);return <div key={event.id} style={{padding:"12px 0",borderBottom:"1px solid var(--border)",display:"grid",gap:7}}><div style={{display:"flex",justifyContent:"space-between",gap:12}}><div><strong style={{fontSize:12}}>{event.authority} · {event.tax_type.replaceAll("_"," ")}</strong><small style={{display:"block",color:"var(--muted)",marginTop:2}}>{event.tax_year??year}{event.reference?` · ${event.reference}`:""}{event.due_date?` · due ${new Date(`${event.due_date}T12:00:00`).toLocaleDateString("en-LU")}`:""}</small></div><div style={{textAlign:"right"}}><strong>{event.amount!=null?money(Number(event.amount),currency):"Amount not extracted"}</strong><small style={{display:"block"}}>{event.status}</small></div></div>{event.status!=="paid"?<TaxPaymentMatch taxEventId={event.id} candidates={candidates}/>:null}</div>})}</div>}</article>{euInvoices.length?<article className={styles.euCard}><div className={styles.euHead}><div><p className={styles.sectionKicker}>EU reporting signal · {year}</p><h2>Reverse-charge sales detected.</h2></div><Landmark size={18}/></div><div className={styles.euSignal}><div><span>EU B2B services</span><strong>{money(euInvoices.reduce((n,i)=>n+Number(i.subtotal),0),currency)}</strong></div><div><span>Invoices</span><strong>{euInvoices.length}</strong></div></div><div className={styles.euNote}><AlertTriangle size={14}/><span>Review the separate recapitulative statement workflow before submission.</span></div></article>:null}</div>
   <aside className={styles.readiness}><p className={styles.sectionKicker}>{year} tax control</p><h2>Estimate vs. assessed tax.</h2><div className={styles.readinessRows}><div className={styles.readinessRow}><span>IRC + fund estimate</span><strong className={styles.good}>{money(ircTax+fund,currency)}</strong></div><div className={styles.readinessRow}><span>ICC estimate</span><strong className={multiplier===null?styles.warning:styles.good}>{icc===null?"Rate required":money(icc,currency)}</strong></div><div className={styles.readinessRow}><span>Posted VAT ledger</span><strong className={styles.good}>{money(position,currency)}</strong></div><div className={styles.readinessRow}><span>VAT items to review</span><strong className={pendingVat?styles.warning:styles.good}>{pendingVat}</strong></div><div className={styles.readinessRow}><span>Authority notices</span><strong className={taxEvents.length?styles.good:styles.warning}>{taxEvents.length?"Imported":"Needs evidence"}</strong></div></div><p className={styles.sourceNote}>Reserve figures are planning estimates only. ACD/AED notices and filings remain the authoritative evidence for assessed liabilities.</p></aside>
  </section>
 </div>;
}
