import { AlertTriangle, BadgeCheck, CheckCircle2, FileOutput, Landmark, ReceiptText } from "lucide-react";
import { redirect } from "next/navigation";
import styles from "@/components/vat-filing.module.css";
import { createClient } from "@/lib/supabase/server";
import { getWorkspace } from "@/lib/workspace";
export const dynamic="force-dynamic";
function money(v:number,c:string){return new Intl.NumberFormat("en-LU",{style:"currency",currency:c,minimumFractionDigits:2}).format(v)}
export default async function VatFilingPage(){const w=await getWorkspace();if(!w.authenticated)redirect("/sign-in");if(!w.company)redirect("/setup");const s=await createClient(),year=new Date().getFullYear(),currency=w.company.base_currency||"EUR",from=`${year}-01-01`,to=`${year}-12-31`,frequency=w.company.vat_filing_frequency||"annual";
 const [{data:accounts},{data:entries},{data:invoices},{data:pending},{data:taxMeta}]=await Promise.all([
  s.from("company_accounts").select("id,code").eq("company_id",w.company.id).in("code",["421611","461411"]),
  s.from("journal_entries").select("id").eq("company_id",w.company.id).eq("status","posted").gte("entry_date",from).lte("entry_date",to),
  s.from("sales_invoices").select("id,vat_treatment,subtotal,vat_total,total,customer_snapshot").eq("company_id",w.company.id).eq("status","issued").gte("service_date",from).lte("service_date",to),
  s.from("source_transactions").select("id",{count:"exact",head:true}).eq("company_id",w.company.id).in("classification_status",["unclassified","review","classified"]).gte("occurred_on",from).lte("occurred_on",to),
  s.from("source_transactions").select("id,vat_treatment,vat_rate,counterparty_country,transaction_kind,direction,vat_amount").eq("company_id",w.company.id).eq("classification_status","posted").gte("occurred_on",from).lte("occurred_on",to)
 ]);
 const map=new Map((accounts??[]).map(a=>[a.id,a.code]));let output=0,input=0;if(entries?.length&&accounts?.length){const{data:lines}=await s.from("journal_lines").select("company_account_id,debit,credit").in("journal_entry_id",entries.map(e=>e.id)).in("company_account_id",accounts.map(a=>a.id));for(const l of lines??[]){const code=map.get(l.company_account_id);if(code==="461411")output+=Number(l.credit)-Number(l.debit);if(code==="421611")input+=Number(l.debit)-Number(l.credit)}}
 const invoiceIds=(invoices??[]).map(i=>i.id),rates=new Map<number,{base:number;vat:number}>();if(invoiceIds.length){const{data:lines}=await s.from("sales_invoice_lines").select("invoice_id,vat_rate,net_amount,vat_amount").in("invoice_id",invoiceIds);const domestic=new Set((invoices??[]).filter(i=>i.vat_treatment==="domestic").map(i=>i.id));for(const l of lines??[]){if(!domestic.has(l.invoice_id))continue;const rate=Number(l.vat_rate),r=rates.get(rate)??{base:0,vat:0};r.base+=Number(l.net_amount);r.vat+=Number(l.vat_amount);rates.set(rate,r)}}
 const eu=(invoices??[]).filter(i=>i.vat_treatment==="eu_b2b_reverse_charge"),euBase=eu.reduce((x,i)=>x+Number(i.subtotal),0),unknownTax=(taxMeta??[]).filter(t=>t.vat_treatment==="unknown"&&((t.counterparty_country&&t.counterparty_country!=="LU")||Number(t.vat_amount)>0)).length,net=output-input,ready=(pending?.length??0)===0&&unknownTax===0;
 const due=frequency==="annual"?`Before 1 Mar ${year+1}`:frequency==="quarterly"?"Before the 15th after each quarter · annual recap before 1 May":"Before the 15th of the following month · annual recap before 1 May";
 return <div className={styles.page}><div className={styles.intro}><div><p>VAT filing · {year}</p><h1>From ledger to declaration draft.</h1><span>This workspace converts posted bookkeeping into a reviewable VAT position. Nothing here is marked filed until a filing snapshot/export is created and confirmed.</span></div><div className={styles.rule}><BadgeCheck/>LU VAT · {frequency}</div></div>
 <section className={styles.hero}><article><span>Net VAT position</span><strong>{money(Math.abs(net),currency)}</strong><small>{net>0?"Payable to AED":net<0?"VAT credit / refundable position":"Balanced"}</small></article><article><span>Output VAT</span><strong>{money(output,currency)}</strong><small>Posted 461411 balance</small></article><article><span>Deductible input VAT</span><strong>{money(input,currency)}</strong><small>Posted 421611 balance</small></article><article><span>Filing deadline</span><strong>{due}</strong><small>{frequency} profile</small></article></section>
 <section className={styles.grid}><article className={styles.card}><div className={styles.head}><div><p>Draft return</p><h2>Domestic taxable sales</h2></div><ReceiptText/></div>{[17,14,8,3,0].map(rate=>{const r=rates.get(rate)??{base:0,vat:0};return <div className={styles.row} key={rate}><span><b>{rate}%</b> taxable base</span><strong>{money(r.base,currency)}<small>VAT {money(r.vat,currency)}</small></strong></div>})}<div className={styles.total}><span>Net VAT from ledger</span><strong>{money(net,currency)}</strong></div></article>
 <article className={styles.card}><div className={styles.head}><div><p>EU reporting</p><h2>Recapitulative statement signal</h2></div><Landmark/></div><div className={styles.big}>{money(euBase,currency)}<small>{eu.length} reverse-charge invoice{eu.length===1?"":"s"}</small></div>{euBase>0?<div className={styles.notice}><AlertTriangle/>EU B2B services were detected. These transactions belong in the separate recapitulative statement workflow, due before the 25th after the reporting period.</div>:<div className={styles.clear}><CheckCircle2/>No EU B2B service sales detected in issued invoices.</div>}</article>
 <article className={styles.card}><div className={styles.head}><div><p>Readiness</p><h2>{ready?"Ready for filing review":"Evidence still missing"}</h2></div>{ready?<CheckCircle2/>:<AlertTriangle/>}</div><div className={styles.check}><span>Unreviewed transactions</span><strong>{pending?.length??0}</strong></div><div className={styles.check}><span>Unknown VAT treatment</span><strong>{unknownTax}</strong></div><div className={styles.check}><span>Sales rate breakdown</span><strong>Live</strong></div><div className={styles.check}><span>Purchase rate breakdown</span><strong>{(taxMeta??[]).some(t=>t.vat_rate!==null)?"Partial":"Needs richer evidence"}</strong></div><div className={styles.export}><FileOutput/><div><strong>eCDF export layer</strong><p>Compta now has the ledger totals and readiness model. The next step is schema-versioned eCDF field mapping and XML validation rather than inventing a generic XML file.</p></div></div></article></section></div>}
