import { BadgeCheck, Landmark, PiggyBank, ShieldCheck, WalletCards } from "lucide-react";
import { redirect } from "next/navigation";
import { TaxProfileForm } from "@/components/tax-profile-form";
import styles from "@/components/tax-reserve.module.css";
import { createClient } from "@/lib/supabase/server";
import { getWorkspace } from "@/lib/workspace";
export const dynamic="force-dynamic";
function money(v:number,c:string){return new Intl.NumberFormat("en-LU",{style:"currency",currency:c,minimumFractionDigits:2}).format(v)}
function irc(profit:number){if(profit<=0)return 0;if(profit<=175000)return profit*.14;if(profit<=200001)return 24500+(profit-175000)*.30;return profit*.16}
export default async function TaxReservePage(){const w=await getWorkspace();if(!w.authenticated)redirect("/sign-in");if(!w.company)redirect("/setup");const s=await createClient(),year=new Date().getFullYear(),currency=w.company.base_currency||"EUR",from=`${year}-01-01`,to=`${year}-12-31`;
 const[{data:entries},{data:accounts},{data:profile}]=await Promise.all([s.from("journal_entries").select("id").eq("company_id",w.company.id).eq("status","posted").gte("entry_date",from).lte("entry_date",to),s.from("company_accounts").select("id,code,account_type").eq("company_id",w.company.id).eq("is_active",true),s.from("company_tax_profiles").select("municipality,icc_multiplier,icc_multiplier_year,icc_verified_at,prior_closing_balance_total,prior_balance_year").eq("company_id",w.company.id).maybeSingle()]);
 const ids=(entries??[]).map(e=>e.id),accountMap=new Map((accounts??[]).map(a=>[a.id,a]));let revenue=0,operatingExpense=0,bank=0,outputVat=0,inputVat=0;if(ids.length){const{data:lines}=await s.from("journal_lines").select("company_account_id,debit,credit").in("journal_entry_id",ids);for(const l of lines??[]){const a=accountMap.get(l.company_account_id);if(!a)continue;const d=Number(l.debit),c=Number(l.credit);if(a.account_type==="revenue")revenue+=c-d;if(a.account_type==="expense"&&!['6711','6721','6811'].includes(a.code))operatingExpense+=d-c;if(a.code==='5131')bank+=d-c;if(a.code==='461411')outputVat+=c-d;if(a.code==='421611')inputVat+=d-c}}
 const profit=Math.max(0,revenue-operatingExpense),ircTax=irc(profit),fund=ircTax*.07,multiplier=profile?.icc_multiplier===null||profile?.icc_multiplier===undefined?null:Number(profile.icc_multiplier),icc=multiplier===null?null:Math.max(profit-17500,0)*.03*multiplier,vatPayable=Math.max(outputVat-inputVat,0),directKnown=ircTax+fund+(icc??0),recommended=vatPayable+directKnown,safe=bank-recommended,prior=profile?.prior_closing_balance_total===null||profile?.prior_closing_balance_total===undefined?null:Number(profile.prior_closing_balance_total),ifMinimum=prior===null?null:prior<=350000?535:prior<=2000000?1605:4815,trusted=multiplier!==null;
 return <div className={styles.page}><div className={styles.intro}><div><p>Tax reserve · {year}</p><h1>Know what cash is actually yours to use.</h1><span>Compta separates posted VAT, estimated direct taxes and book cash. The estimate remains visibly provisional wherever tax-profile evidence is missing.</span></div><div className={`${styles.trust} ${trusted?styles.trustGood:""}`}>{trusted?<BadgeCheck/>:<ShieldCheck/>}{trusted?"Municipality rate confirmed":"ICC rate needs confirmation"}</div></div>
 <section className={styles.hero}><article className={styles.safe}><span>Safe-to-use book cash</span><strong>{money(safe,currency)}</strong><small>Book bank {money(bank,currency)} − recommended reserve {money(recommended,currency)}</small></article><article><PiggyBank/><span>Recommended reserve</span><strong>{money(recommended,currency)}</strong><small>VAT + IRC + fund + {icc===null?"ICC pending":"ICC"}</small></article><article><WalletCards/><span>Accounting profit proxy</span><strong>{money(profit,currency)}</strong><small>Revenue less operating expenses before direct taxes</small></article></section>
 <section className={styles.grid}><article className={styles.card}><div className={styles.head}><div><p>Reserve stack</p><h2>What Compta is holding back</h2></div><Landmark/></div><div className={styles.row}><span>VAT payable</span><strong>{money(vatPayable,currency)}</strong></div><div className={styles.row}><span>IRC estimate</span><strong>{money(ircTax,currency)}</strong></div><div className={styles.row}><span>Employment fund surcharge · 7% IRC</span><strong>{money(fund,currency)}</strong></div><div className={styles.row}><span>ICC estimate</span><strong>{icc===null?"Needs multiplier":money(icc,currency)}</strong></div><div className={styles.total}><span>Recommended current reserve</span><strong>{money(recommended,currency)}</strong></div>{ifMinimum!==null?<div className={styles.ifBox}><span>Minimum IF context</span><strong>{money(ifMinimum,currency)}</strong><p>Raw statutory minimum based on the prior closing balance total entered below. It is shown separately because the official minimum-IF reduction interacts with prior IRC/fund tax.</p></div>:null}</article>
 <article className={styles.card}><div className={styles.head}><div><p>Tax profile</p><h2>Inputs that change the estimate</h2></div><ShieldCheck/></div><TaxProfileForm municipality={profile?.municipality??w.company.municipality??null} multiplier={multiplier} year={Number(profile?.icc_multiplier_year??year)} priorBalance={prior}/><p className={styles.note}>The municipal multiplier is stored with its year and verification timestamp. Compta does not infer it from the city name until an official rate source is integrated.</p></article></section></div>}
