import type { SupabaseClient } from "@supabase/supabase-js";
import { classifyTransactionsWithAI, type AiTransactionInput } from "@/lib/openai-bookkeeping";

type Company={id:string;legal_name:string;trading_name:string|null;activity:string|null;vat_registered:boolean;vat_number:string|null;base_currency:string};
type PipelineOptions={supabase:SupabaseClient;company:Company;start?:string;end?:string;sourceIds?:string[];maxTransactions?:number};
type SourceRow={id:string;occurred_on:string;direction:string;amount_gross:number|string;currency:string;counterparty_name:string|null;description:string|null;source_type:string;source_id:string|null;classification_status:string;suggested_account_id:string|null;suggestion_confidence:number|string|null;suggestion_reason:string|null;suggestion_kind:string|null;counterparty_country:string|null};
const pendingStatuses=["unclassified","review","classified"];
const safeKinds=new Set(["operating","bank_fee","payment_processor_fee","ai_software_subscription","ai_advertising","ai_professional_service","ai_bank_fee","ai_fuel","ai_insurance","ai_telecom","ai_service_revenue","ai_sales_revenue"]);
const protectedSuggestionKinds=new Set(["shareholder_transfer","tax_advance","tax_payment","payment_processor_fee","refund_candidate","platform_payout","penalty","registry_payment","bank_transfer_unknown"]);
const riskyType=/tax|shareholder|loan|asset|vehicle|personal|cash|transfer_unknown|registry|capital|refund|payout/i;
function validCode(code:string|null,accounts:Map<string,{id:string;code:string;label:string;account_type:string}>){return code?accounts.get(code)??null:null}
async function postOne(supabase:SupabaseClient,id:string,code:string){const{error}=await supabase.rpc("classify_and_post_source_transaction",{p_source_transaction_id:id,p_account_code:code});return error?.message??null}

export async function runAiTransactionPipeline({supabase,company,start,end,sourceIds,maxTransactions=180}:PipelineOptions){
 if(sourceIds?.length){for(const id of sourceIds){const{error}=await supabase.rpc("apply_source_transaction_suggestion",{p_source_transaction_id:id});if(error)throw new Error(error.message)}}else await supabase.rpc("reanalyze_pending_source_transactions",{p_company_id:company.id});
 let query=supabase.from("source_transactions").select("id,occurred_on,direction,amount_gross,currency,counterparty_name,description,source_type,source_id,classification_status,suggested_account_id,suggestion_confidence,suggestion_reason,suggestion_kind,counterparty_country").eq("company_id",company.id).in("classification_status",pendingStatuses).order("occurred_on",{ascending:true}).order("created_at",{ascending:true}).limit(maxTransactions);
 if(start)query=query.gte("occurred_on",start);if(end)query=query.lte("occurred_on",end);if(sourceIds?.length)query=query.in("id",sourceIds);
 const{data:initial,error:sourceError}=await query;if(sourceError)throw new Error(sourceError.message);let rows=(initial??[]) as SourceRow[];
 const[{data:accountRows,error:accountError},{data:ruleRows,error:ruleError}]=await Promise.all([
  supabase.from("company_accounts").select("id,code,label,account_type").eq("company_id",company.id).eq("is_active",true).in("account_type",["expense","revenue","asset","liability"]),
  supabase.from("classification_rules").select("normalized_counterparty,direction,company_account_id,vat_treatment,vat_rate,counterparty_country,times_confirmed").eq("company_id",company.id).order("times_confirmed",{ascending:false}).limit(160)
 ]);if(accountError)throw new Error(accountError.message);if(ruleError)throw new Error(ruleError.message);
 const accountByCode=new Map((accountRows??[]).map(a=>[String(a.code),{id:String(a.id),code:String(a.code),label:String(a.label),account_type:String(a.account_type)}]));const accountById=new Map([...accountByCode.values()].map(a=>[a.id,a]));
 let deterministicPosted=0;const deterministicErrors:string[]=[];
 for(const row of rows){const account=row.suggested_account_id?accountById.get(row.suggested_account_id):null,confidence=Number(row.suggestion_confidence??0),kind=row.suggestion_kind??"";if(account&&confidence>=.97&&["expense","revenue"].includes(account.account_type)&&safeKinds.has(kind)&&!protectedSuggestionKinds.has(kind)){const error=await postOne(supabase,row.id,account.code);if(error)deterministicErrors.push(error);else deterministicPosted++}}
 if(deterministicPosted){let q=supabase.from("source_transactions").select("id,occurred_on,direction,amount_gross,currency,counterparty_name,description,source_type,source_id,classification_status,suggested_account_id,suggestion_confidence,suggestion_reason,suggestion_kind,counterparty_country").eq("company_id",company.id).in("classification_status",pendingStatuses).order("occurred_on",{ascending:true}).order("created_at",{ascending:true}).limit(maxTransactions);if(start)q=q.gte("occurred_on",start);if(end)q=q.lte("occurred_on",end);if(sourceIds?.length)q=q.in("id",sourceIds);const{data}=await q;rows=(data??[]) as SourceRow[]}
 if(!rows.length)return{scanned:deterministicPosted,deterministic_posted:deterministicPosted,ai_suggested:0,ai_auto_posted:0,remaining:0,errors:deterministicErrors};
 const bankIds=rows.filter(r=>r.source_type==="bank"&&r.source_id).map(r=>r.source_id as string),bankMap=new Map<string,Record<string,unknown>>();if(bankIds.length){const{data:banks}=await supabase.from("bank_transactions").select("id,raw_data,counterparty_name,counterparty_iban,reference,external_id,booking_date,value_date,amount,currency").in("id",bankIds);for(const b of banks??[])bankMap.set(String(b.id),{...(b.raw_data&&typeof b.raw_data==="object"?b.raw_data as Record<string,unknown>:{}),bank_counterparty:b.counterparty_name,bank_counterparty_iban:b.counterparty_iban,bank_reference:b.reference,bank_external_id:b.external_id})}
 const rules=(ruleRows??[]).map(r=>{const a=accountById.get(String(r.company_account_id));return a?{normalized_counterparty:String(r.normalized_counterparty),direction:String(r.direction),code:a.code,label:a.label,times_confirmed:Number(r.times_confirmed??0),vat_treatment:r.vat_treatment as string|null,vat_rate:r.vat_rate as number|string|null,counterparty_country:r.counterparty_country as string|null}:null}).filter(Boolean) as Array<{normalized_counterparty:string;direction:string;code:string;label:string;times_confirmed:number;vat_treatment:string|null;vat_rate:number|string|null;counterparty_country:string|null}>;
 const inputs:AiTransactionInput[]=rows.map(r=>{const a=r.suggested_account_id?accountById.get(r.suggested_account_id):null;return{id:r.id,occurred_on:r.occurred_on,direction:r.direction,amount_gross:Number(r.amount_gross),currency:r.currency,counterparty_name:r.counterparty_name,description:r.description,current_suggestion_code:a?.code??null,current_suggestion_confidence:r.suggestion_confidence==null?null:Number(r.suggestion_confidence),current_suggestion_reason:r.suggestion_reason,raw_data:r.source_id?bankMap.get(r.source_id)??null:null}});
 let classifications=[] as Awaited<ReturnType<typeof classifyTransactionsWithAI>>;for(let i=0;i<inputs.length;i+=50)classifications.push(...await classifyTransactionsWithAI({company,accounts:[...accountByCode.values()],rules,transactions:inputs.slice(i,i+50)}));
 const rowMap=new Map(rows.map(r=>[r.id,r]));let suggested=0,autoPosted=0;const errors=[...deterministicErrors],updates:Record<string,unknown>[]=[],autoQueue:{id:string;code:string}[]=[];
 for(const result of classifications){
  const row=rowMap.get(result.id);if(!row)continue;
  const now=new Date().toISOString(),aiMeta={...result,model:"gpt-5-mini",analyzed_at:now,bank_evidence_used:Boolean(row.source_id&&bankMap.has(row.source_id))};
  if(protectedSuggestionKinds.has(row.suggestion_kind??"")){
    const protectedAccount=row.suggested_account_id?accountById.get(row.suggested_account_id):null;
    updates.push({id:row.id,suggested_account_id:row.suggested_account_id,suggestion_confidence:row.suggestion_confidence,suggestion_reason:row.suggestion_reason,suggestion_kind:row.suggestion_kind,ai_classification:aiMeta,ai_analyzed_at:now,ai_model:"gpt-5-mini",counterparty_name:!row.counterparty_name&&result.normalized_counterparty?result.normalized_counterparty:null,counterparty_country:!row.counterparty_country&&result.counterparty_country?result.counterparty_country.toUpperCase().slice(0,2):null});
    if(protectedAccount)suggested++;
    continue;
  }
  const account=validCode(result.account_code,accountByCode),confidence=Math.max(0,Math.min(1,Number(result.confidence)||0)),kind=`ai_${String(result.transaction_type||"unknown").toLowerCase().replace(/[^a-z0-9]+/g,"_").slice(0,48)}`,reason=`AI · ${result.reason}${result.vat_evidence_missing?" · VAT evidence still required":""}`;
  updates.push({id:row.id,suggested_account_id:account?.id??null,suggestion_confidence:confidence,suggestion_reason:reason,suggestion_kind:kind,ai_classification:aiMeta,ai_analyzed_at:now,ai_model:"gpt-5-mini",counterparty_name:!row.counterparty_name&&result.normalized_counterparty?result.normalized_counterparty:null,counterparty_country:!row.counterparty_country&&result.counterparty_country?result.counterparty_country.toUpperCase().slice(0,2):null});if(account)suggested++;
  const safePurpose=result.business_purpose==="business"||result.business_purpose==="likely_business",safeAccount=account&&["expense","revenue"].includes(account.account_type),safeType=!riskyType.test(result.transaction_type),safeConfidence=confidence>=.96&&!result.needs_review;if(account&&safePurpose&&safeAccount&&safeType&&safeConfidence)autoQueue.push({id:row.id,code:account.code});
 }
 if(updates.length){const{error}=await supabase.rpc("apply_ai_bookkeeping_suggestions",{p_company_id:company.id,p_rows:updates});if(error)errors.push(error.message)}
 for(const item of autoQueue){const error=await postOne(supabase,item.id,item.code);if(error)errors.push(error);else autoPosted++}
 let remainingQuery=supabase.from("source_transactions").select("id",{count:"exact",head:true}).eq("company_id",company.id).in("classification_status",pendingStatuses);if(start)remainingQuery=remainingQuery.gte("occurred_on",start);if(end)remainingQuery=remainingQuery.lte("occurred_on",end);if(sourceIds?.length)remainingQuery=remainingQuery.in("id",sourceIds);const{count}=await remainingQuery;
 return{scanned:inputs.length+deterministicPosted,deterministic_posted:deterministicPosted,ai_suggested:suggested,ai_auto_posted:autoPosted,remaining:Number(count??0),errors};
}
