import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";

type Payload=Record<string,unknown>;
type TBRow={code:string;label:string;account_type:string;debit:number;credit:number;balance:number};
const W=595.28,H=841.89,M=46,INK=rgb(.10,.10,.11),MUTED=rgb(.42,.43,.46),LINE=rgb(.88,.89,.90),SOFT=rgb(.96,.97,.96),ACCENT=rgb(.70,.87,.03);
function o(v:unknown){return v&&typeof v==="object"?v as Record<string,unknown>:null}
function a(v:unknown){return Array.isArray(v)?v:[]}
function n(v:unknown){const x=Number(v);return Number.isFinite(x)?x:0}
function s(v:unknown){return typeof v==="string"?v:""}
function clean(v:string){return v.normalize("NFKD").replace(/[–—]/g,"-").replace(/[‘’]/g,"'").replace(/[“”]/g,'"').replace(/[^\x20-\x7E]/g," ").replace(/\s+/g," ").trim()}
function snap(p:Payload){return o(p.ledger_snapshot)??{}}
function co(p:Payload){return o(p.company)??{}}
function pl(p:Payload){return o(snap(p).profit_and_loss)??{}}
function cur(p:Payload){return s(co(p).base_currency)||"EUR"}
function money(v:number,c:string){return `${c} ${new Intl.NumberFormat("en-LU",{minimumFractionDigits:2,maximumFractionDigits:2}).format(v)}`}
function rows(p:Payload):TBRow[]{return a(snap(p).trial_balance).map(raw=>{const r=o(raw)??{};return{code:s(r.code),label:s(r.label),account_type:s(r.account_type),debit:n(r.debit),credit:n(r.credit),balance:n(r.balance)}}).filter(r=>r.code)}
function revenue(p:Payload){return n(pl(p).revenue)}
function expenses(p:Payload){return n(pl(p).expenses)}
function result(p:Payload){return n(pl(p).result)}

class Writer{
 pdf:PDFDocument;regular:PDFFont;bold:PDFFont;page!:PDFPage;y=0;title:string;company:string;period:string;checksum:string;
 constructor(pdf:PDFDocument,r:PDFFont,b:PDFFont,p:Payload,title:string){this.pdf=pdf;this.regular=r;this.bold=b;this.title=clean(title);this.company=clean(s(co(p).legal_name)||"Company");this.period=clean(`${s(p.period_start)} - ${s(p.period_end)}`);this.checksum=s(p.ledger_checksum)}
 add(){this.page=this.pdf.addPage([W,H]);this.y=H-M;this.page.drawRectangle({x:M,y:this.y-24,width:22,height:22,color:INK});this.page.drawText("C",{x:M+6.2,y:this.y-17,size:11,font:this.bold,color:ACCENT});this.page.drawText(this.company,{x:M+31,y:this.y-10,size:10.5,font:this.bold,color:INK});this.page.drawText(this.title,{x:M+31,y:this.y-23,size:8,font:this.regular,color:MUTED});this.page.drawText(this.period,{x:W-M-112,y:this.y-10,size:7.5,font:this.regular,color:MUTED});this.y-=43;this.page.drawLine({start:{x:M,y:this.y},end:{x:W-M,y:this.y},thickness:.6,color:LINE});this.y-=18}
 ensure(h:number){if(this.y-h<58)this.add()}
 wrap(text:string,font:PDFFont,size:number,width:number){const words=clean(text).split(" ").filter(Boolean),out:string[]=[];let line="";for(const word of words){const next=line?`${line} ${word}`:word;if(font.widthOfTextAtSize(next,size)<=width)line=next;else{if(line)out.push(line);line=word}}if(line)out.push(line);return out.length?out:[""]}
 heading(text:string){this.ensure(40);this.page.drawText(clean(text),{x:M,y:this.y,size:17,font:this.bold,color:INK});this.y-=28}
 section(text:string){this.ensure(27);this.y-=3;this.page.drawText(clean(text).toUpperCase(),{x:M,y:this.y,size:7.5,font:this.bold,color:MUTED});this.y-=17}
 text(text:string,size=9,bold=false,color=INK,width=W-2*M){const font=bold?this.bold:this.regular,ls=this.wrap(text,font,size,width);this.ensure(ls.length*(size+3)+3);for(const line of ls){this.page.drawText(line,{x:M,y:this.y,size,font,color});this.y-=size+3}}
 note(text:string){const ls=this.wrap(text,this.regular,8.2,W-2*M-24),h=ls.length*11+18;this.ensure(h+8);this.page.drawRectangle({x:M,y:this.y-h+6,width:W-2*M,height:h,color:SOFT,borderColor:LINE,borderWidth:.5});let yy=this.y-10;for(const line of ls){this.page.drawText(line,{x:M+12,y:yy,size:8.2,font:this.regular,color:MUTED});yy-=11}this.y-=h+9}
 metric(label:string,value:string){label=clean(label);value=clean(value);this.ensure(32);this.page.drawText(label,{x:M,y:this.y,size:7.5,font:this.regular,color:MUTED});this.page.drawText(value,{x:W-M-this.bold.widthOfTextAtSize(value,10),y:this.y-1,size:10,font:this.bold,color:INK});this.y-=21;this.page.drawLine({start:{x:M,y:this.y},end:{x:W-M,y:this.y},thickness:.45,color:LINE});this.y-=10}
 header(cols:{label:string;x:number;right?:boolean}[]){this.ensure(25);this.page.drawRectangle({x:M,y:this.y-14,width:W-2*M,height:20,color:SOFT});for(const c of cols){const text=clean(c.label),tw=this.bold.widthOfTextAtSize(text,7);this.page.drawText(text,{x:c.right?c.x-tw:c.x,y:this.y-8,size:7,font:this.bold,color:MUTED})}this.y-=25}
 row(cells:{text:string;x:number;width?:number;right?:boolean;bold?:boolean}[]){const lineCounts=cells.map(c=>c.width?this.wrap(c.text,c.bold?this.bold:this.regular,7.7,c.width).length:1),h=Math.max(20,Math.max(...lineCounts)*10+7);this.ensure(h+3);for(const c of cells){const font=c.bold?this.bold:this.regular,ls=c.width?this.wrap(c.text,font,7.7,c.width):[clean(c.text)];ls.forEach((line,i)=>{const tw=font.widthOfTextAtSize(line,7.7);this.page.drawText(line,{x:c.right?c.x-tw:c.x,y:this.y-8-i*10,size:7.7,font,color:INK})})}this.y-=h;this.page.drawLine({start:{x:M,y:this.y+2},end:{x:W-M,y:this.y+2},thickness:.35,color:LINE})}
 finish(){const total=this.pdf.getPageCount();for(let i=0;i<total;i++){const p=this.pdf.getPage(i);p.drawText(`Generated by Compta from frozen closing snapshot | Page ${i+1}/${total}`,{x:M,y:30,size:6.5,font:this.regular,color:MUTED});if(this.checksum)p.drawText(`Ledger ${clean(this.checksum.slice(0,16))}`,{x:W-M-95,y:30,size:6.5,font:this.regular,color:MUTED})}}
}

function drawPL(w:Writer,p:Payload){const c=cur(p),rs=rows(p),rev=rs.filter(r=>r.account_type==="revenue"&&Math.abs(r.balance)>.005),exp=rs.filter(r=>r.account_type==="expense"&&Math.abs(r.balance)>.005);w.heading("Profit & Loss");w.note("Prepared from the frozen closing snapshot. This report is a Compta working document and does not submit anything to eCDF or the RCS.");w.section("Revenue");w.header([{label:"PCN",x:M+8},{label:"ACCOUNT",x:M+60},{label:"AMOUNT",x:W-M-8,right:true}]);for(const r of rev)w.row([{text:r.code,x:M+8},{text:r.label,x:M+60,width:300},{text:money(r.credit-r.debit,c),x:W-M-8,right:true}]);w.metric("Total revenue",money(revenue(p),c));w.section("Expenses");w.header([{label:"PCN",x:M+8},{label:"ACCOUNT",x:M+60},{label:"AMOUNT",x:W-M-8,right:true}]);for(const r of exp)w.row([{text:r.code,x:M+8},{text:r.label,x:M+60,width:300},{text:money(r.debit-r.credit,c),x:W-M-8,right:true}]);w.metric("Total expenses",money(expenses(p),c));w.section("Result");w.metric("Result for the year",money(result(p),c))}
function drawBS(w:Writer,p:Payload){const c=cur(p),rs=rows(p),assets=rs.filter(r=>r.account_type==="asset"&&Math.abs(r.balance)>.005),liabs=rs.filter(r=>r.account_type==="liability"&&Math.abs(r.balance)>.005),eq=rs.filter(r=>r.account_type==="equity"&&Math.abs(r.balance)>.005),at=assets.reduce((x,r)=>x+r.balance,0),prior=liabs.reduce((x,r)=>x-r.balance,0)+eq.reduce((x,r)=>x-r.balance,0),rhs=prior+result(p);w.heading("Balance Sheet");w.note("Closing balances are shown from the frozen ledger snapshot. Current-year result is presented separately because it is derived from the P&L at closing.");w.section("Assets");w.header([{label:"PCN",x:M+8},{label:"ACCOUNT",x:M+60},{label:"BALANCE",x:W-M-8,right:true}]);for(const r of assets)w.row([{text:r.code,x:M+8},{text:r.label,x:M+60,width:300},{text:money(r.balance,c),x:W-M-8,right:true}]);w.metric("Total assets",money(at,c));w.section("Equity and liabilities");w.header([{label:"PCN",x:M+8},{label:"ACCOUNT",x:M+60},{label:"BALANCE",x:W-M-8,right:true}]);for(const r of eq)w.row([{text:r.code,x:M+8},{text:r.label,x:M+60,width:300},{text:money(-r.balance,c),x:W-M-8,right:true}]);for(const r of liabs)w.row([{text:r.code,x:M+8},{text:r.label,x:M+60,width:300},{text:money(-r.balance,c),x:W-M-8,right:true}]);w.row([{text:"142",x:M+8},{text:"Result for the year",x:M+60,width:300,bold:true},{text:money(result(p),c),x:W-M-8,right:true,bold:true}]);w.metric("Total equity and liabilities",money(rhs,c));w.metric("Balance control",money(at-rhs,c))}
function drawTB(w:Writer,p:Payload,pcn:boolean){const c=cur(p),rs=rows(p).filter(r=>Math.abs(r.debit)>.005||Math.abs(r.credit)>.005);w.heading(pcn?"PCN Account Balances":"Trial Balance");w.note(pcn?"PCN-oriented account balances from the frozen closing snapshot. CSV is a working reference and is not labelled as an eCDF import file.":"Debits and credits by account from the frozen closing snapshot.");w.header([{label:"PCN",x:M+6},{label:"ACCOUNT",x:M+53},{label:"DEBIT",x:W-M-118,right:true},{label:"CREDIT",x:W-M-8,right:true}]);for(const r of rs)w.row([{text:r.code,x:M+6},{text:r.label,x:M+53,width:250},{text:r.debit?money(r.debit,c):"-",x:W-M-118,right:true},{text:r.credit?money(r.credit,c):"-",x:W-M-8,right:true}])}
function drawAnnexe(w:Writer,p:Payload){const c=cur(p),rs=rows(p),assets=rs.filter(r=>r.account_type==="asset"&&r.balance>.005),eq=rs.filter(r=>r.account_type==="equity"&&r.balance<-.005),depr=rs.find(r=>r.code==="6333"),company=co(p);w.heading("Annexe to the Annual Accounts - Draft");w.note("Review required. This draft contains only facts available in Compta. It deliberately avoids inventing legal, tax, staffing, commitment or related-party disclosures that have not been confirmed by the user.");w.section("Company identification");w.metric("Legal name",s(company.legal_name)||"-");w.metric("Legal form",s(company.legal_form)||"-");w.metric("RCS number",s(company.rcs_number)||"-");w.metric("Financial year",`${s(p.period_start)} - ${s(p.period_end)}`);w.section("Financial overview");w.metric("Revenue",money(revenue(p),c));w.metric("Expenses",money(expenses(p),c));w.metric("Result for the year",money(result(p),c));if(depr)w.metric("Depreciation / value adjustments",money(depr.debit-depr.credit,c));w.section("Closing asset balances");for(const r of assets)w.metric(`${r.code} - ${r.label}`,money(r.balance,c));w.section("Closing equity balances");for(const r of eq)w.metric(`${r.code} - ${r.label}`,money(-r.balance,c));w.metric("142 - Result for the year",money(result(p),c));w.section("Review before official use");w.text("Supplement this draft with disclosures that apply to the company but are not represented by ledger balances, including any required narrative accounting policies, guarantees or commitments, subsequent events, staff information, related-party matters, management or audit information, and other required notes.",8.8,false,MUTED)}
function drawGL(w:Writer,p:Payload){const entries=a(o(p.general_ledger)?.entries),c=cur(p);w.heading("General Ledger");w.note("Frozen journal detail for the closing snapshot. Each entry is shown with its debit and credit lines.");for(const raw of entries){const e=o(raw)??{};w.section(`J${String(n(e.entry_number)).padStart(4,"0")} | ${s(e.entry_date)}`);w.text(s(e.description)||"Journal entry",9,true);w.header([{label:"PCN",x:M+6},{label:"ACCOUNT",x:M+53},{label:"DEBIT",x:W-M-118,right:true},{label:"CREDIT",x:W-M-8,right:true}]);for(const lr of a(e.lines)){const l=o(lr)??{},cc=s(l.currency)||c;w.row([{text:s(l.account_code),x:M+6},{text:s(l.account_label),x:M+53,width:250},{text:n(l.debit)?money(n(l.debit),cc):"-",x:W-M-118,right:true},{text:n(l.credit)?money(n(l.credit),cc):"-",x:W-M-8,right:true}])}w.y-=5}}

export async function buildFinancialDocumentPdf(payload:Payload,type:string,title:string){const pdf=await PDFDocument.create(),r=await pdf.embedFont(StandardFonts.Helvetica),b=await pdf.embedFont(StandardFonts.HelveticaBold);pdf.setTitle(clean(title));pdf.setAuthor("Compta");pdf.setCreator("Compta document generator 2026.1");pdf.setSubject("Financial document generated from a frozen closing snapshot");const w=new Writer(pdf,r,b,payload,title);w.add();if(type==="profit_loss")drawPL(w,payload);else if(type==="balance_sheet")drawBS(w,payload);else if(type==="trial_balance")drawTB(w,payload,false);else if(type==="pcn")drawTB(w,payload,true);else if(type==="annexe")drawAnnexe(w,payload);else if(type==="general_ledger")drawGL(w,payload);else if(type==="annual_accounts"){w.heading("Annual Accounts");w.text(`Financial year ${s(payload.period_start)} - ${s(payload.period_end)}`,11,false,MUTED);w.note("Compta-generated annual accounts model based on the frozen closing snapshot. No authority submission is performed.");w.section("Key figures");w.metric("Revenue",money(revenue(payload),cur(payload)));w.metric("Expenses",money(expenses(payload),cur(payload)));w.metric("Result",money(result(payload),cur(payload)));w.add();drawPL(w,payload);w.add();drawBS(w,payload)}else throw new Error("Unsupported financial document type");w.finish();return pdf.save()}
