import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage, type RGB } from "pdf-lib";

type Payload=Record<string,unknown>;
type TBRow={code:string;label:string;account_type:string;debit:number;credit:number;balance:number};
type JournalLine={account_code:string;account_label:string;account_type:string;description:string;debit:number;credit:number;currency:string};
type JournalEntry={entry_number:number;entry_date:string;description:string;source_type:string;lines:JournalLine[]};
const W=595.28,H=841.89,M=42,CONTENT=W-2*M;
const INK=rgb(.08,.09,.10),MUTED=rgb(.39,.41,.44),FAINT=rgb(.63,.65,.68),LINE=rgb(.86,.87,.88),SOFT=rgb(.965,.968,.965),SOFT2=rgb(.94,.945,.94),ACCENT=rgb(.70,.87,.03),WHITE=rgb(1,1,1),GOOD=rgb(.22,.45,.20);
function o(v:unknown){return v&&typeof v==="object"?v as Record<string,unknown>:null}
function a(v:unknown){return Array.isArray(v)?v:[]}
function n(v:unknown){const x=Number(v);return Number.isFinite(x)?x:0}
function s(v:unknown){return typeof v==="string"?v:""}
function clean(v:string){return v.normalize("NFKD").replace(/[–—]/g,"-").replace(/[‘’]/g,"'").replace(/[“”]/g,'"').replace(/[^\x20-\x7E]/g," ").replace(/\s+/g," ").trim()}
function snap(p:Payload){return o(p.ledger_snapshot)??{}}
function co(p:Payload){return o(p.company)??{}}
function pl(p:Payload){return o(snap(p).profit_and_loss)??{}}
function cur(p:Payload){return s(co(p).base_currency)||"EUR"}
function money(v:number,c:string){const abs=Math.abs(v),formatted=new Intl.NumberFormat("en-LU",{minimumFractionDigits:2,maximumFractionDigits:2}).format(abs);return v<-.005?`(${c} ${formatted})`:`${c} ${formatted}`}
function plainMoney(v:number){return new Intl.NumberFormat("en-LU",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Math.abs(v))}
function rows(p:Payload):TBRow[]{return a(snap(p).trial_balance).map(raw=>{const r=o(raw)??{};return{code:s(r.code),label:s(r.label),account_type:s(r.account_type),debit:n(r.debit),credit:n(r.credit),balance:n(r.balance)}}).filter(r=>r.code)}
function revenue(p:Payload){return n(pl(p).revenue)}function expenses(p:Payload){return n(pl(p).expenses)}function result(p:Payload){return n(pl(p).result)}
function sides(balance:number){return balance>=0?{debit:balance,credit:0}:{debit:0,credit:-balance}}
function balanceLabel(balance:number,currency:string){const side=balance>=0?"Dr":"Cr";return `${money(Math.abs(balance),currency)} ${side}`}
function journalEntries(p:Payload):JournalEntry[]{const raw=a(o(p.journal)?.entries).length?a(o(p.journal)?.entries):a(o(p.general_ledger)?.entries);return raw.map(item=>{const e=o(item)??{};return{entry_number:n(e.entry_number),entry_date:s(e.entry_date),description:s(e.description)||"Journal entry",source_type:s(e.source_type),lines:a(e.lines).map(lineRaw=>{const l=o(lineRaw)??{};return{account_code:s(l.account_code),account_label:s(l.account_label),account_type:s(l.account_type),description:s(l.description),debit:n(l.debit),credit:n(l.credit),currency:s(l.currency)||cur(p)}})}}).sort((x,y)=>x.entry_date.localeCompare(y.entry_date)||x.entry_number-y.entry_number)}

class Writer{
 pdf:PDFDocument;regular:PDFFont;bold:PDFFont;page!:PDFPage;y=0;title:string;company:string;period:string;checksum:string;generated:string;compact=false;
 constructor(pdf:PDFDocument,r:PDFFont,b:PDFFont,p:Payload,title:string){this.pdf=pdf;this.regular=r;this.bold=b;this.title=clean(title);this.company=clean(s(co(p).legal_name)||"Company");this.period=clean(`${s(p.period_start)} - ${s(p.period_end)}`);this.checksum=s(p.ledger_checksum);const gd=s(p.generated_at)||s(p.snapshot_at);this.generated=gd?new Date(gd).toLocaleDateString("en-LU",{year:"numeric",month:"short",day:"2-digit"}):""}
 add(compact=false){this.compact=compact;this.page=this.pdf.addPage([W,H]);this.y=H-M;this.page.drawRectangle({x:M,y:this.y-22,width:20,height:20,color:INK});this.page.drawText("C",{x:M+5.6,y:this.y-16,size:10.5,font:this.bold,color:ACCENT});this.page.drawText(this.company,{x:M+29,y:this.y-8,size:10,font:this.bold,color:INK});this.page.drawText(this.title,{x:M+29,y:this.y-20,size:7.6,font:this.regular,color:MUTED});const right=this.period;this.page.drawText(right,{x:W-M-this.regular.widthOfTextAtSize(right,7.3),y:this.y-8,size:7.3,font:this.regular,color:MUTED});this.y-=38;this.page.drawLine({start:{x:M,y:this.y},end:{x:W-M,y:this.y},thickness:.55,color:LINE});this.y-=compact?11:17}
 cover(p:Payload){this.page=this.pdf.addPage([W,H]);this.y=H-M;this.page.drawRectangle({x:M,y:H-M-42,width:30,height:30,color:INK});this.page.drawText("C",{x:M+8.5,y:H-M-32,size:15,font:this.bold,color:ACCENT});this.page.drawText("COMPTA",{x:M+40,y:H-M-24,size:8,font:this.bold,color:MUTED});this.page.drawRectangle({x:M,y:H-212,width:6,height:108,color:ACCENT});this.page.drawText("Annual Accounts",{x:M+26,y:H-135,size:28,font:this.bold,color:INK});this.page.drawText(`Financial year ${clean(this.period)}`,{x:M+27,y:H-160,size:10,font:this.regular,color:MUTED});this.page.drawText(this.company,{x:M+27,y:H-190,size:14,font:this.bold,color:INK});const company=co(p),meta=[s(company.legal_form),s(company.rcs_number)?`RCS ${s(company.rcs_number)}`:"",s(company.registered_address)].filter(Boolean).map(clean).join(" | ");if(meta)this.page.drawText(meta,{x:M+27,y:H-208,size:7.8,font:this.regular,color:MUTED,maxWidth:CONTENT-27});this.page.drawRectangle({x:M,y:H-410,width:CONTENT,height:132,color:SOFT,borderColor:LINE,borderWidth:.5});this.page.drawText("YEAR AT A GLANCE",{x:M+18,y:H-300,size:7.4,font:this.bold,color:MUTED});const vals=[{label:"Revenue",value:money(revenue(p),cur(p))},{label:"Expenses",value:money(expenses(p),cur(p))},{label:"Result for the year",value:money(result(p),cur(p))}];vals.forEach((item,i)=>{const x=M+18+i*(CONTENT-36)/3;this.page.drawText(item.label,{x,y:H-329,size:7.2,font:this.regular,color:MUTED});this.page.drawText(item.value,{x,y:H-352,size:12.2,font:this.bold,color:INK});if(i<2)this.page.drawLine({start:{x:x+(CONTENT-36)/3-12,y:H-370},end:{x:x+(CONTENT-36)/3-12,y:H-312},thickness:.45,color:LINE})});this.page.drawText("Prepared from the frozen closing snapshot",{x:M,y:105,size:8.5,font:this.bold,color:INK});this.page.drawText("Compta generates preparation and export documents only. No filing or submission to an authority is performed.",{x:M,y:88,size:7.5,font:this.regular,color:MUTED,maxWidth:CONTENT});if(this.generated)this.page.drawText(`Generated ${this.generated}`,{x:M,y:63,size:7,font:this.regular,color:FAINT})}
 ensure(h:number){if(this.y-h<55)this.add(this.compact)}
 wrap(text:string,font:PDFFont,size:number,width:number){const words=clean(text).split(" ").filter(Boolean),out:string[]=[];let line="";for(const word of words){const next=line?`${line} ${word}`:word;if(font.widthOfTextAtSize(next,size)<=width)line=next;else{if(line)out.push(line);line=word}}if(line)out.push(line);return out.length?out:[""]}
 heading(text:string,subtitle?:string){this.ensure(subtitle?52:36);this.page.drawText(clean(text),{x:M,y:this.y,size:19,font:this.bold,color:INK});this.y-=subtitle?24:30;if(subtitle){this.text(subtitle,8.1,false,MUTED,CONTENT,2);this.y-=8}}
 section(text:string){this.ensure(25);this.y-=3;this.page.drawText(clean(text).toUpperCase(),{x:M,y:this.y,size:7.2,font:this.bold,color:MUTED});this.y-=15}
 text(text:string,size=8.6,bold=false,color:RGB=INK,width=CONTENT,gap=2.5){const font=bold?this.bold:this.regular,ls=this.wrap(text,font,size,width);this.ensure(ls.length*(size+gap)+3);for(const line of ls){this.page.drawText(line,{x:M,y:this.y,size,font,color});this.y-=size+gap}}
 note(text:string){const ls=this.wrap(text,this.regular,7.7,CONTENT-24),h=ls.length*10+18;this.ensure(h+6);this.page.drawRectangle({x:M,y:this.y-h+5,width:CONTENT,height:h,color:SOFT,borderColor:LINE,borderWidth:.45});let yy=this.y-10;for(const line of ls){this.page.drawText(line,{x:M+12,y:yy,size:7.7,font:this.regular,color:MUTED});yy-=10}this.y-=h+8}
 metric(label:string,value:string,emphasis=false){label=clean(label);value=clean(value);this.ensure(28);this.page.drawText(label,{x:M,y:this.y,size:7.8,font:emphasis?this.bold:this.regular,color:emphasis?INK:MUTED});this.page.drawText(value,{x:W-M-this.bold.widthOfTextAtSize(value,emphasis?10.5:9.5),y:this.y-1,size:emphasis?10.5:9.5,font:this.bold,color:INK});this.y-=18;this.page.drawLine({start:{x:M,y:this.y},end:{x:W-M,y:this.y},thickness:.4,color:LINE});this.y-=8}
 header(cols:{label:string;x:number;right?:boolean}[],height=19){this.ensure(height+6);this.page.drawRectangle({x:M,y:this.y-height+5,width:CONTENT,height,color:SOFT2});for(const c of cols){const text=clean(c.label),tw=this.bold.widthOfTextAtSize(text,6.7);this.page.drawText(text,{x:c.right?c.x-tw:c.x,y:this.y-8,size:6.7,font:this.bold,color:MUTED})}this.y-=height+4}
 row(cells:{text:string;x:number;width?:number;right?:boolean;bold?:boolean;color?:RGB}[],opts?:{size?:number;minHeight?:number;lineGap?:number;shade?:boolean}){const size=opts?.size??7.6,gap=opts?.lineGap??2.2,minH=opts?.minHeight??18;const lineCounts=cells.map(c=>c.width?this.wrap(c.text,c.bold?this.bold:this.regular,size,c.width).length:1),h=Math.max(minH,Math.max(...lineCounts)*(size+gap)+6);this.ensure(h+2);if(opts?.shade)this.page.drawRectangle({x:M,y:this.y-h+4,width:CONTENT,height:h,color:SOFT});for(const c of cells){const font=c.bold?this.bold:this.regular,ls=c.width?this.wrap(c.text,font,size,c.width):[clean(c.text)];ls.forEach((line,i)=>{const tw=font.widthOfTextAtSize(line,size);this.page.drawText(line,{x:c.right?c.x-tw:c.x,y:this.y-7-i*(size+gap),size,font,color:c.color??INK})})}this.y-=h;this.page.drawLine({start:{x:M,y:this.y+2},end:{x:W-M,y:this.y+2},thickness:.3,color:LINE})}
 pill(label:string,value:string){const valueW=this.bold.widthOfTextAtSize(clean(value),8.5),width=Math.min(CONTENT,Math.max(150,valueW+82));this.ensure(29);this.page.drawRectangle({x:M,y:this.y-20,width,height:24,color:SOFT,borderColor:LINE,borderWidth:.4});this.page.drawText(clean(label),{x:M+9,y:this.y-12,size:7,font:this.regular,color:MUTED});this.page.drawText(clean(value),{x:M+width-9-valueW,y:this.y-12,size:8.5,font:this.bold,color:INK});this.y-=33}
 finish(){const total=this.pdf.getPageCount();for(let i=0;i<total;i++){const p=this.pdf.getPage(i);const left=`Generated by Compta | Frozen closing snapshot | Page ${i+1}/${total}`;p.drawText(left,{x:M,y:27,size:6.1,font:this.regular,color:FAINT});if(this.checksum){const right=`Ledger ${clean(this.checksum.slice(0,16))}`,tw=this.regular.widthOfTextAtSize(right,6.1);p.drawText(right,{x:W-M-tw,y:27,size:6.1,font:this.regular,color:FAINT})}}}
}

function drawPL(w:Writer,p:Payload,embedded=false){const c=cur(p),rs=rows(p),rev=rs.filter(r=>r.account_type==="revenue"&&Math.abs(r.balance)>.005),exp=rs.filter(r=>r.account_type==="expense"&&Math.abs(r.balance)>.005);w.heading("Profit & Loss",embedded?undefined:"Detailed financial report from the frozen closing snapshot.");if(!embedded)w.note("Amounts reflect Compta's detailed ledger accounts. This is a financial report and preparation aid; it is not an automatic authority submission.");w.section("Revenue");w.header([{label:"PCN",x:M+8},{label:"ACCOUNT",x:M+61},{label:"AMOUNT",x:W-M-8,right:true}]);rev.forEach((r,i)=>w.row([{text:r.code,x:M+8},{text:r.label,x:M+61,width:300},{text:money(r.credit-r.debit,c),x:W-M-8,right:true}],{shade:i%2===1}));w.metric("Total revenue",money(revenue(p),c),true);w.section("Expenses");w.header([{label:"PCN",x:M+8},{label:"ACCOUNT",x:M+61},{label:"AMOUNT",x:W-M-8,right:true}]);exp.forEach((r,i)=>w.row([{text:r.code,x:M+8},{text:r.label,x:M+61,width:300},{text:money(r.debit-r.credit,c),x:W-M-8,right:true}],{shade:i%2===1}));w.metric("Total expenses",money(expenses(p),c),true);w.section("Result");w.metric("Result for the year",money(result(p),c),true)}
function drawBS(w:Writer,p:Payload,embedded=false){const c=cur(p),rs=rows(p),assets=rs.filter(r=>r.account_type==="asset"&&Math.abs(r.balance)>.005),liabs=rs.filter(r=>r.account_type==="liability"&&Math.abs(r.balance)>.005),eq=rs.filter(r=>r.account_type==="equity"&&Math.abs(r.balance)>.005),at=assets.reduce((x,r)=>x+r.balance,0),prior=liabs.reduce((x,r)=>x-r.balance,0)+eq.reduce((x,r)=>x-r.balance,0),rhs=prior+result(p),gap=at-rhs;w.heading("Balance Sheet",embedded?undefined:"Closing financial position from the frozen snapshot.");if(!embedded)w.note("Current-year result is presented separately from prior equity. A zero balance control confirms that both sides of the closing balance sheet agree.");w.section("Assets");w.header([{label:"PCN",x:M+8},{label:"ACCOUNT",x:M+61},{label:"BALANCE",x:W-M-8,right:true}]);assets.forEach((r,i)=>w.row([{text:r.code,x:M+8},{text:r.label,x:M+61,width:300},{text:money(r.balance,c),x:W-M-8,right:true}],{shade:i%2===1}));w.metric("Total assets",money(at,c),true);w.section("Equity and liabilities");w.header([{label:"PCN",x:M+8},{label:"ACCOUNT",x:M+61},{label:"BALANCE",x:W-M-8,right:true}]);let idx=0;for(const r of eq){w.row([{text:r.code,x:M+8},{text:r.label,x:M+61,width:300},{text:money(-r.balance,c),x:W-M-8,right:true}],{shade:idx++%2===1})}for(const r of liabs){w.row([{text:r.code,x:M+8},{text:r.label,x:M+61,width:300},{text:money(-r.balance,c),x:W-M-8,right:true}],{shade:idx++%2===1})}w.row([{text:"142",x:M+8},{text:"Result for the year",x:M+61,width:300,bold:true},{text:money(result(p),c),x:W-M-8,right:true,bold:true}],{shade:idx%2===1});w.metric("Total equity and liabilities",money(rhs,c),true);w.metric("Balance control",money(gap,c),true)}
function drawTrialBalance(w:Writer,p:Payload){const c=cur(p),rs=rows(p).filter(r=>Math.abs(r.debit)>.005||Math.abs(r.credit)>.005);w.heading("Trial Balance","Account turnover plus closing debit/credit position.");w.note("Debit and credit turnover show activity during the year. Closing debit and closing credit show the net year-end position; they are not additional movements.");w.header([{label:"PCN",x:M+3},{label:"ACCOUNT",x:M+43},{label:"DEBIT TURN.",x:W-M-215,right:true},{label:"CREDIT TURN.",x:W-M-137,right:true},{label:"CLOSE DR",x:W-M-65,right:true},{label:"CLOSE CR",x:W-M-3,right:true}],18);rs.forEach((r,i)=>{const side=sides(r.balance);w.row([{text:r.code,x:M+3},{text:r.label,x:M+43,width:185},{text:r.debit?plainMoney(r.debit):"-",x:W-M-215,right:true},{text:r.credit?plainMoney(r.credit):"-",x:W-M-137,right:true},{text:side.debit?plainMoney(side.debit):"-",x:W-M-65,right:true},{text:side.credit?plainMoney(side.credit):"-",x:W-M-3,right:true}],{size:6.7,minHeight:15,lineGap:1.7,shade:i%2===1})});w.text(`Currency: ${c}`,6.8,false,FAINT)}
function drawPCN(w:Writer,p:Payload){const c=cur(p),rs=rows(p).filter(r=>Math.abs(r.balance)>.005);w.heading("PCN Closing Balances","Year-end debit and credit balances by PCN account.");w.note("This report uses net closing balances, not cumulative debit/credit turnover. It is intended as a preparation reference for official forms. CSV remains a generic working export, not an eCDF import file.");w.header([{label:"PCN",x:M+8},{label:"ACCOUNT",x:M+61},{label:"CLOSING DEBIT",x:W-M-104,right:true},{label:"CLOSING CREDIT",x:W-M-8,right:true}]);let dr=0,cr=0;rs.forEach((r,i)=>{const side=sides(r.balance);dr+=side.debit;cr+=side.credit;w.row([{text:r.code,x:M+8},{text:r.label,x:M+61,width:270},{text:side.debit?money(side.debit,c):"-",x:W-M-104,right:true},{text:side.credit?money(side.credit,c):"-",x:W-M-8,right:true}],{size:7.2,minHeight:17,shade:i%2===1})});w.metric("Closing debit total",money(dr,c),true);w.metric("Closing credit total",money(cr,c),true);w.metric("Control difference",money(dr-cr,c),true)}
function drawAnnexe(w:Writer,p:Payload){const c=cur(p),rs=rows(p),assets=rs.filter(r=>r.account_type==="asset"&&r.balance>.005),eq=rs.filter(r=>r.account_type==="equity"&&r.balance<-.005),depr=rs.find(r=>r.code==="6333"),company=co(p);w.heading("Annexe to the Annual Accounts - Draft","Evidence-based notes summary for review before official use.");w.note("This draft only uses facts present in Compta. It does not invent legal, tax, staffing, commitment, related-party or subsequent-event disclosures that have not been confirmed.");w.section("Company identification");w.metric("Legal name",s(company.legal_name)||"-");w.metric("Legal form",s(company.legal_form)||"-");w.metric("RCS number",s(company.rcs_number)||"-");w.metric("Financial year",`${s(p.period_start)} - ${s(p.period_end)}`);w.section("Financial overview");w.metric("Revenue",money(revenue(p),c));w.metric("Expenses",money(expenses(p),c));w.metric("Result for the year",money(result(p),c),true);if(depr)w.metric("Depreciation / value adjustments",money(depr.debit-depr.credit,c));w.section("Closing position");for(const r of assets)w.metric(`${r.code} - ${r.label}`,money(r.balance,c));for(const r of eq)w.metric(`${r.code} - ${r.label}`,money(-r.balance,c));w.metric("142 - Result for the year",money(result(p),c));w.section("Review before official use");w.text("Confirm any narrative disclosures that are not represented by ledger balances, including accounting policies requiring explanation, guarantees or commitments, events after the reporting period, staff information, related-party matters, management or audit information, and any other legally required notes.",7.9,false,MUTED)}
function drawJournal(w:Writer,p:Payload){const entries=journalEntries(p),c=cur(p);w.heading("General Journal","Chronological frozen journal entries for the financial year.");w.note("Journal numbers remain the immutable audit references. Entries below are presented by accounting date for easier review, so the sequence of J-numbers may not be chronological.");for(const e of entries){const ref=`J${String(e.entry_number).padStart(4,"0")}`,head=`${ref}   ${e.entry_date}   ${e.description}`;const height=24+e.lines.length*14;w.ensure(height);w.page.drawRectangle({x:M,y:w.y-17,width:CONTENT,height:20,color:SOFT2});w.page.drawText(clean(head),{x:M+7,y:w.y-10,size:7.4,font:w.bold,color:INK,maxWidth:CONTENT-14});w.y-=24;for(const line of e.lines){w.row([{text:line.account_code,x:M+7},{text:line.account_label,x:M+49,width:245},{text:line.debit?money(line.debit,line.currency||c):"-",x:W-M-111,right:true},{text:line.credit?money(line.credit,line.currency||c):"-",x:W-M-7,right:true}],{size:7,minHeight:13,lineGap:1.4})}w.y-=3}}
function drawLedger(w:Writer,p:Payload){const entries=journalEntries(p),c=cur(p);type Move={date:string;entry:number;description:string;debit:number;credit:number;currency:string};const groups=new Map<string,{code:string;label:string;type:string;moves:Move[]}>();for(const e of entries){for(const line of e.lines){const key=line.account_code||line.account_label;if(!groups.has(key))groups.set(key,{code:line.account_code,label:line.account_label,type:line.account_type,moves:[]});groups.get(key)!.moves.push({date:e.entry_date,entry:e.entry_number,description:e.description||line.description,debit:line.debit,credit:line.credit,currency:line.currency||c})}}w.heading("General Ledger","Account-by-account movements, running balances and closing balances.");w.note("Movements are ordered by accounting date within each account. The running balance is debit minus credit and is displayed with its debit/credit side.");for(const group of [...groups.values()].sort((x,y)=>x.code.localeCompare(y.code,undefined,{numeric:true}))){group.moves.sort((x,y)=>x.date.localeCompare(y.date)||x.entry-y.entry);w.ensure(72);w.y-=4;w.page.drawRectangle({x:M,y:w.y-27,width:CONTENT,height:31,color:INK});w.page.drawText(clean(`${group.code}  ${group.label}`),{x:M+10,y:w.y-10,size:9,font:w.bold,color:WHITE,maxWidth:CONTENT-175});let running=0;for(const move of group.moves)running+=move.debit-move.credit;const close=balanceLabel(running,c),tw=w.bold.widthOfTextAtSize(clean(close),7.8);w.page.drawText(clean(close),{x:W-M-10-tw,y:w.y-10,size:7.8,font:w.bold,color:ACCENT});w.page.drawText("Closing balance",{x:W-M-10-tw,y:w.y-21,size:5.9,font:w.regular,color:WHITE});w.y-=37;w.header([{label:"DATE",x:M+5},{label:"REF",x:M+63},{label:"DESCRIPTION",x:M+105},{label:"DEBIT",x:W-M-158,right:true},{label:"CREDIT",x:W-M-92,right:true},{label:"BALANCE",x:W-M-5,right:true}],17);let run=0;group.moves.forEach((move,i)=>{run+=move.debit-move.credit;w.row([{text:move.date,x:M+5},{text:`J${String(move.entry).padStart(4,"0")}`,x:M+63},{text:move.description,x:M+105,width:220},{text:move.debit?plainMoney(move.debit):"-",x:W-M-158,right:true},{text:move.credit?plainMoney(move.credit):"-",x:W-M-92,right:true},{text:`${plainMoney(run)} ${run>=0?"Dr":"Cr"}`,x:W-M-5,right:true}],{size:6.55,minHeight:14,lineGap:1.4,shade:i%2===1})});w.text(`Currency ${c}`,6.2,false,FAINT);w.y-=8}}

export async function buildFinancialDocumentPdf(payload:Payload,type:string,title:string){
 const pdf=await PDFDocument.create(),r=await pdf.embedFont(StandardFonts.Helvetica),b=await pdf.embedFont(StandardFonts.HelveticaBold);pdf.setTitle(clean(title));pdf.setAuthor("Compta");pdf.setCreator("Compta document generator 2026.2");pdf.setSubject("Financial document generated from a frozen closing snapshot");const w=new Writer(pdf,r,b,payload,title);
 if(type==="annual_accounts"){w.cover(payload);w.add();drawBS(w,payload,true);w.add();drawPL(w,payload,true)}
 else{w.add(type==="general_journal"||type==="general_ledger");if(type==="profit_loss")drawPL(w,payload);else if(type==="balance_sheet")drawBS(w,payload);else if(type==="trial_balance")drawTrialBalance(w,payload);else if(type==="pcn")drawPCN(w,payload);else if(type==="annexe")drawAnnexe(w,payload);else if(type==="general_journal")drawJournal(w,payload);else if(type==="general_ledger")drawLedger(w,payload);else throw new Error("Unsupported financial document type")}
 w.finish();return pdf.save()
}
