type Payload=Record<string,unknown>;
function obj(value:unknown){return value&&typeof value==="object"?value as Record<string,unknown>:null}
function arr(value:unknown){return Array.isArray(value)?value:[]}
function str(value:unknown){return typeof value==="string"?value:""}
function num(value:unknown){const n=Number(value);return Number.isFinite(n)?n:0}
function esc(value:unknown){const s=String(value??"");return /[",\n\r]/.test(s)?`"${s.replaceAll('"','""')}"`:s}
function lines(rows:unknown[][]){return rows.map(row=>row.map(esc).join(",")).join("\r\n")+"\r\n"}
function snapshot(payload:Payload){return obj(payload.ledger_snapshot)??{}}
function trial(payload:Payload){return arr(snapshot(payload).trial_balance).map(raw=>obj(raw)??{})}
function pl(payload:Payload){return obj(snapshot(payload).profit_and_loss)??{}}

export function buildFinancialDocumentCsv(payload:Payload,documentType:string){const tb=trial(payload);if(documentType==="trial_balance"||documentType==="pcn")return lines([["PCN","Account","Type","Debit","Credit","Net debit balance"],...tb.map(r=>[str(r.code),str(r.label),str(r.account_type),num(r.debit).toFixed(2),num(r.credit).toFixed(2),num(r.balance).toFixed(2)])]);if(documentType==="profit_loss"){const revenue=tb.filter(r=>str(r.account_type)==="revenue"),expenses=tb.filter(r=>str(r.account_type)==="expense"),p=pl(payload);return lines([["Section","PCN","Account","Amount"],...revenue.map(r=>["Revenue",str(r.code),str(r.label),(num(r.credit)-num(r.debit)).toFixed(2)]),["Revenue total","","",num(p.revenue).toFixed(2)],...expenses.map(r=>["Expense",str(r.code),str(r.label),(num(r.debit)-num(r.credit)).toFixed(2)]),["Expense total","","",num(p.expenses).toFixed(2)],["Result","","",num(p.result).toFixed(2)]])}if(documentType==="balance_sheet"){const assets=tb.filter(r=>str(r.account_type)==="asset"&&Math.abs(num(r.balance))>.005),liabilities=tb.filter(r=>str(r.account_type)==="liability"&&Math.abs(num(r.balance))>.005),equity=tb.filter(r=>str(r.account_type)==="equity"&&Math.abs(num(r.balance))>.005),result=num(pl(payload).result);return lines([["Side","PCN","Account","Amount"],...assets.map(r=>["Assets",str(r.code),str(r.label),num(r.balance).toFixed(2)]),...liabilities.map(r=>["Liabilities",str(r.code),str(r.label),(-num(r.balance)).toFixed(2)]),...equity.map(r=>["Equity",str(r.code),str(r.label),(-num(r.balance)).toFixed(2)]),["Equity","142","Result for the year",result.toFixed(2)]])}if(documentType==="general_ledger"){const entries=arr(obj(payload.general_ledger)?.entries),out:unknown[][]=[["Entry","Date","Entry description","Source","PCN","Account","Line description","Debit","Credit","Currency"]];for(const raw of entries){const e=obj(raw)??{};for(const rawLine of arr(e.lines)){const l=obj(rawLine)??{};out.push([`J${String(num(e.entry_number)).padStart(4,"0")}`,str(e.entry_date),str(e.description),str(e.source_type),str(l.account_code),str(l.account_label),str(l.description),num(l.debit).toFixed(2),num(l.credit).toFixed(2),str(l.currency)])}}return lines(out)}throw new Error("CSV is not available for this document type");}
