type CompanyContext={legal_name:string;trading_name:string|null;activity:string|null;vat_registered:boolean;vat_number:string|null;base_currency:string};
type AccountContext={id:string;code:string;label:string;account_type:string};
type RuleContext={normalized_counterparty:string;direction:string;code:string;label:string;times_confirmed:number;vat_treatment:string|null;vat_rate:number|string|null;counterparty_country:string|null};
export type NormalizedBankRow={booking_date:string;value_date?:string|null;amount:number;currency?:string;counterparty_name?:string|null;counterparty_iban?:string|null;counterparty_address?:string|null;reference?:string|null;communication?:string|null;operation_code?:string|null;external_id?:string|null;raw_details?:string|null;source_page?:number|null};
export type PdfBankExtraction={bank_name:string|null;account_iban:string|null;account_name:string|null;currency:string|null;transactions:NormalizedBankRow[]};
export type AiTransactionInput={id:string;occurred_on:string;direction:string;amount_gross:number;currency:string;counterparty_name:string|null;description:string|null;current_suggestion_code:string|null;current_suggestion_confidence:number|null;current_suggestion_reason:string|null;raw_data:Record<string,unknown>|null};
export type AiClassification={id:string;normalized_counterparty:string|null;transaction_type:string;account_code:string|null;confidence:number;business_purpose:"business"|"likely_business"|"uncertain"|"personal_or_nonbusiness";vat_treatment:"domestic"|"eu_b2b_reverse_charge"|"non_eu"|"exempt_or_zero"|"unknown";vat_rate:number|null;vat_evidence_missing:boolean;counterparty_country:string|null;needs_review:boolean;reason:string};

const pdfRowSchema={type:"object",additionalProperties:false,required:["booking_date","value_date","amount","currency","counterparty_name","counterparty_iban","counterparty_address","reference","communication","operation_code","external_id","raw_details","source_page"],properties:{booking_date:{type:"string"},value_date:{type:["string","null"]},amount:{type:"number"},currency:{type:["string","null"]},counterparty_name:{type:["string","null"]},counterparty_iban:{type:["string","null"]},counterparty_address:{type:["string","null"]},reference:{type:["string","null"]},communication:{type:["string","null"]},operation_code:{type:["string","null"]},external_id:{type:["string","null"]},raw_details:{type:["string","null"]},source_page:{type:["integer","null"]}}};
const pdfSchema={type:"object",additionalProperties:false,required:["bank_name","account_iban","account_name","currency","transactions"],properties:{bank_name:{type:["string","null"]},account_iban:{type:["string","null"]},account_name:{type:["string","null"]},currency:{type:["string","null"]},transactions:{type:"array",items:pdfRowSchema}}} as const;
const classificationItemSchema={type:"object",additionalProperties:false,required:["id","normalized_counterparty","transaction_type","account_code","confidence","business_purpose","vat_treatment","vat_rate","vat_evidence_missing","counterparty_country","needs_review","reason"],properties:{id:{type:"string"},normalized_counterparty:{type:["string","null"]},transaction_type:{type:"string"},account_code:{type:["string","null"]},confidence:{type:"number",minimum:0,maximum:1},business_purpose:{type:"string",enum:["business","likely_business","uncertain","personal_or_nonbusiness"]},vat_treatment:{type:"string",enum:["domestic","eu_b2b_reverse_charge","non_eu","exempt_or_zero","unknown"]},vat_rate:{type:["number","null"]},vat_evidence_missing:{type:"boolean"},counterparty_country:{type:["string","null"]},needs_review:{type:"boolean"},reason:{type:"string"}}};
const classificationSchema={type:"object",additionalProperties:false,required:["results"],properties:{results:{type:"array",items:classificationItemSchema}}} as const;

function outputText(payload:unknown){if(!payload||typeof payload!=="object")return null;const output=(payload as{output?:unknown[]}).output;if(!Array.isArray(output))return null;for(const item of output){if(!item||typeof item!=="object")continue;const content=(item as{content?:unknown[]}).content;if(!Array.isArray(content))continue;for(const part of content){if(part&&typeof part==="object"&&(part as{type?:string}).type==="output_text"&&typeof(part as{text?:unknown}).text==="string")return(part as{text:string}).text}}return null}
async function structuredResponse(apiKey:string,body:Record<string,unknown>){const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify(body)});const payload=await response.json();if(!response.ok){console.error("OpenAI bookkeeping request failed",response.status);throw new Error("The AI bookkeeping service is temporarily unavailable.")}const text=outputText(payload);if(!text)throw new Error("The bookkeeping model returned no structured output.");return JSON.parse(text) as Record<string,unknown>}
function companyPrompt(company:CompanyContext){return `Company: ${company.legal_name}${company.trading_name?` / ${company.trading_name}`:""}. Activity: ${company.activity||"not supplied"}. Base currency: ${company.base_currency}. VAT registered: ${company.vat_registered?"yes":"no"}${company.vat_number?` (${company.vat_number})`:""}.`}

export async function extractBankStatementPdf(file:File,company:CompanyContext):Promise<PdfBankExtraction>{const apiKey=process.env.OPENAI_API_KEY;if(!apiKey)throw new Error("OpenAI bank-statement extraction is not configured on this deployment yet.");if(file.type!=="application/pdf"&&!/\.pdf$/i.test(file.name))throw new Error("Only PDF statements can use AI document extraction.");if(file.size>15*1024*1024)throw new Error("PDF bank statements are limited to 15 MB per import.");const bytes=Buffer.from(await file.arrayBuffer()),base64=bytes.toString("base64");const payload=await structuredResponse(apiKey,{model:"gpt-5-mini",store:false,input:[{role:"developer",content:[{type:"input_text",text:`You extract bank movements for a Luxembourg bookkeeping application. ${companyPrompt(company)} Read the entire PDF visually and extract EVERY actual account movement exactly once. Never include opening balances, closing balances, subtotals, page totals, advertisements or informational text as transactions. Preserve printed merchant/sender/beneficiary names, IBANs, payment references, communications and bank transaction labels whenever visible. Amounts must be signed: money into the account is positive; money out is negative. Dates must be YYYY-MM-DD. Do not invent unreadable data; use null. source_page is the 1-based PDF page containing the movement.`}]},{role:"user",content:[{type:"input_text",text:"Normalize this bank statement into structured account movements."},{type:"input_file",filename:file.name,file_data:`data:application/pdf;base64,${base64}`}]}],text:{format:{type:"json_schema",name:"zuelen_bank_statement",strict:true,schema:pdfSchema}},max_output_tokens:16000});const parsed=payload as unknown as PdfBankExtraction;if(!Array.isArray(parsed.transactions))throw new Error("No transaction list was returned from the PDF.");return parsed}

export async function classifyTransactionsWithAI(args:{company:CompanyContext;accounts:AccountContext[];rules:RuleContext[];transactions:AiTransactionInput[]}):Promise<AiClassification[]>{
 const apiKey=process.env.OPENAI_API_KEY;if(!apiKey)throw new Error("OpenAI bookkeeping classification is not configured on this deployment yet.");if(!args.transactions.length)return[];
 const accountList=args.accounts.map(a=>`${a.code} | ${a.account_type} | ${a.label}`).join("\n"),ruleList=args.rules.slice(0,80).map(r=>`${r.normalized_counterparty} | ${r.direction} -> ${r.code} ${r.label} | confirmed ${r.times_confirmed}x${r.counterparty_country?` | ${r.counterparty_country}`:""}`).join("\n")||"No confirmed rules yet.";
 const transactions=args.transactions.map(t=>({id:t.id,date:t.occurred_on,direction:t.direction,amount:t.amount_gross,currency:t.currency,counterparty:t.counterparty_name,description:t.description,current_suggestion:t.current_suggestion_code,current_confidence:t.current_suggestion_confidence,current_reason:t.current_suggestion_reason,bank_evidence:t.raw_data}));
 const payload=await structuredResponse(apiKey,{model:"gpt-5-mini",store:false,input:[{role:"developer",content:[{type:"input_text",text:`You are the classification layer of Zuelen, a Luxembourg bookkeeping application. ${companyPrompt(args.company)} Your task is to classify the BUSINESS PURPOSE and PCN account of bank movements. Use only the allowed account codes below. Prefer confirmed company history when the merchant identity matches despite changing card/payment references, BUT never let a learned rule override clear bank-direction semantics or a safer tax/shareholder/refund rule. Recognize common SaaS/software subscriptions, advertising platforms, professional marketplaces, bank fees, fuel, insurance, telecoms, tax authorities, shareholder transfers, loans and ordinary online marketplaces. A changing numeric suffix after a merchant name usually does not make it a different merchant. For example recurring WIX.COM references are still Wix. Do not treat a payment processor wrapper such as PAYPAL as the merchant when the underlying merchant is visible.

BANK-DIRECTION SEMANTICS:
- direction=income means money entered the bank account. Do not classify it as an expense merely because the counterparty also sells advertising/software.
- direction=expense means money left the bank account.
- Incoming Google/YouTube/AdSense platform payouts are revenue when the evidence/history supports monetisation. Do not call an incoming Google payment an advertising refund unless the bank evidence explicitly indicates a refund/credit.
- An incoming bank movement explicitly labelled refund/remboursement/card refund is NOT new sales revenue. Match/reverse the original expense category when identifiable; otherwise use transaction_type=refund_candidate, account_code=null and needs_review=true.

HIGH-RISK LUXEMBOURG RULES:
- Shareholder current account: "apport compte courant associé" or shareholder funding into the company normally increases a liability to the shareholder (4712 for short-term), not shareholder receivable 4212. A company payment back to the shareholder normally reduces 4712. Use 4212 only when the evidence clearly means the shareholder owes money to the company. Keep needs_review=true for genuinely ambiguous owner movements.
- ACD quarterly tax advances/acompte/avance are tax prepayments, not personnel advances. If the exact tax (IRC/ICC/IF) is not supported by the notice, prefer generic ACD receivable/prepayment 42148 and needs_review=true rather than guessing a specific tax account. A generic ACD settlement of an already established liability can use an ACD payable account when supported.
- Stripe/card processing charges belong to the dedicated electronic-payment fee account 61334 when that account is available; do not classify an identifiable payment-processing fee as IT services.
- A current deterministic Zuelen suggestion for shareholder_transfer, tax_advance, tax_payment, payment_processor_fee or refund_candidate represents a safety rule. Explain it rather than contradicting it unless the bank evidence clearly proves the deterministic interpretation wrong.

IMPORTANT SAFETY RULES:
- A bank statement proves payment, not recoverable VAT. vat_treatment and vat_rate are advisory only; set vat_evidence_missing=true whenever an invoice/receipt would be needed to support VAT treatment.
- Never invent a VAT amount.
- Set needs_review=true for genuinely ambiguous owner/personal transfers, loans, fixed-asset purchases, tax payments whose exact liability is unclear, refunds whose original expense is unclear, cash movements, or when the business purpose cannot be supported.
- An ordinary recurring operating merchant can have needs_review=false even when VAT evidence is missing; VAT evidence is a separate workflow.
- Use confidence >=0.96 only when the PCN category is exceptionally clear from merchant/history/context.
- Online marketplaces can be recognized as marketplaces, but if the purchased business purpose is unknown, choose the best plausible expense account only as a suggestion and keep needs_review=true.

ALLOWED COMPANY ACCOUNTS:
${accountList}

CONFIRMED CLASSIFICATION HISTORY:
${ruleList}`}]},{role:"user",content:[{type:"input_text",text:`Classify these pending bank movements. Return one result for every id and no extra ids.\n${JSON.stringify(transactions)}` }]}],text:{format:{type:"json_schema",name:"zuelen_bank_classification",strict:true,schema:classificationSchema}},max_output_tokens:12000});
 const results=(payload as{results?:unknown}).results;if(!Array.isArray(results))throw new Error("The bookkeeping model returned no classifications.");return results as AiClassification[];
}
