import { Building2, ExternalLink, FileArchive, FileCheck2, FileText, Landmark, LockKeyhole, ReceiptText, Search, ShieldCheck, Sparkles, WandSparkles } from "lucide-react";
import Link from "next/link";
import { redirect } from "next/navigation";
import { DocumentUploader } from "@/components/document-uploader";
import { DocumentRowActions } from "@/components/document-row-actions";
import { DocumentExtractionButton } from "@/components/document-extraction-button";
import { DocumentMatchActions, TaxNoticeAction } from "@/components/document-workflow-actions";
import styles from "@/components/documents.module.css";
import { createClient } from "@/lib/supabase/server";
import { getWorkspace } from "@/lib/workspace";

export const dynamic="force-dynamic";
const typeLabel:Record<string,string>={receipt:"Receipt",purchase_invoice:"Supplier invoice",bank_statement:"Bank statement",tax_notice:"Tax notice",filing:"Filing",annex:"Annual accounts",sales_invoice:"Sales invoice",other:"Business document"};
const categoryTypes:Record<string,string[]>={all:[],sales:["sales_invoice"],purchases:["purchase_invoice"],receipts:["receipt"],bank:["bank_statement"],tax:["tax_notice","filing"],company:["annex","other"]};
function sizeLabel(bytes:number|null){if(!bytes)return"—";return bytes>=1024*1024?`${(bytes/1024/1024).toFixed(2)} MB`:`${Math.max(1,Math.round(bytes/1024))} KB`}
function money(value:unknown,currency:unknown){if(typeof value!=="number")return null;return new Intl.NumberFormat("en-LU",{style:"currency",currency:typeof currency==="string"&&currency.length===3?currency:"EUR",minimumFractionDigits:2}).format(value)}
function extractionSummary(raw:unknown){if(!raw||typeof raw!=="object")return null;const d=raw as Record<string,unknown>;if(typeof d.error==="string")return{error:d.error};const kind=typeof d.document_kind==="string"?d.document_kind:null,party=kind==="sales_invoice"?(typeof d.customer_name==="string"?d.customer_name:null):(typeof d.issuer_name==="string"?d.issuer_name:null);return{kind,party,total:money(d.total,d.currency),vat:money(d.vat_amount,d.currency),category:typeof d.suggested_account_category==="string"?d.suggested_account_category:null,treatment:typeof d.suggested_vat_treatment==="string"?d.suggested_vat_treatment.replaceAll("_"," "):null,confidence:typeof d.confidence==="number"?Math.round(d.confidence*100):null}}
function archivedBatchId(raw:unknown){if(!raw||typeof raw!=="object")return null;const value=(raw as Record<string,unknown>).bank_import_batch_id;return typeof value==="string"?value:null}
type Params=Promise<{category?:string;q?:string}>;
export default async function DocumentsPage({searchParams}:{searchParams:Params}){
 const params=await searchParams,category=categoryTypes[params.category??"all"]?params.category??"all":"all",q=(params.q??"").trim().toLowerCase();const workspace=await getWorkspace();if(!workspace.authenticated)redirect("/sign-in");if(!workspace.company||!workspace.organization)redirect("/setup");const supabase=await createClient();
 const[{data,error},{data:links},{data:taxEvents},{data:bankBatches,error:batchError}]=await Promise.all([
  supabase.from("documents").select("id,type,file_name,mime_type,file_size,extraction_status,extracted_data,created_at,storage_path").eq("company_id",workspace.company.id).order("created_at",{ascending:false}).limit(250),
  supabase.from("document_transaction_links").select("id,document_id,source_transaction_id,match_score,status,source_transactions(occurred_on,counterparty_name,description,amount_gross,currency,classification_status)").eq("company_id",workspace.company.id).in("status",["suggested","confirmed"]).order("match_score",{ascending:false}),
  supabase.from("tax_events").select("id,source_document_id").eq("company_id",workspace.company.id),
  supabase.from("bank_import_batches").select("id,file_name,row_count,imported_count,duplicate_count,created_at").eq("company_id",workspace.company.id).order("created_at",{ascending:false}).limit(100)
 ]);
 if(error)throw new Error(`Could not load documents: ${error.message}`);if(batchError)throw new Error(`Could not load bank statement records: ${batchError.message}`);const docs=data??[],archivedBatchIds=new Set(docs.map(doc=>archivedBatchId(doc.extracted_data)).filter((id):id is string=>Boolean(id))),statementRecords=(bankBatches??[]).filter(batch=>!archivedBatchIds.has(batch.id)),bestLink=new Map<string,(typeof links extends Array<infer T>?T:never)>();for(const link of links??[]){if(!bestLink.has(link.document_id)||link.status==="confirmed")bestLink.set(link.document_id,link as never)}const taxDocs=new Set((taxEvents??[]).map(e=>e.source_document_id).filter(Boolean));
 const bankDocumentCount=docs.filter(doc=>doc.type==="bank_statement").length+statementRecords.length,totalCount=docs.length+statementRecords.length,count=(types:string[])=>!types.length?totalCount:types.includes("bank_statement")?docs.filter(doc=>types.includes(doc.type)).length+statementRecords.length:docs.filter(doc=>types.includes(doc.type)).length,visible=docs.filter(doc=>(category==="all"||categoryTypes[category].includes(doc.type))&&(!q||`${doc.file_name} ${typeLabel[doc.type]??doc.type}`.toLowerCase().includes(q))),visibleStatements=(category==="all"||category==="bank")?statementRecords.filter(batch=>!q||`${batch.file_name??"Bank statement"} bank statement banking`.toLowerCase().includes(q)):[];
 const folders=[{key:"all",label:"All documents",icon:FileArchive,types:[]},{key:"sales",label:"Sales invoices",icon:FileText,types:["sales_invoice"]},{key:"purchases",label:"Supplier invoices",icon:ReceiptText,types:["purchase_invoice"]},{key:"receipts",label:"Receipts",icon:ReceiptText,types:["receipt"]},{key:"bank",label:"Bank statements",icon:Landmark,types:["bank_statement"]},{key:"tax",label:"Tax & filings",icon:ShieldCheck,types:["tax_notice","filing"]},{key:"company",label:"Business docs",icon:Building2,types:["annex","other"]}];
 const shown=visible.length+visibleStatements.length;
 return <div className={styles.page}>
  <div className={styles.intro}><div><p>Evidence vault</p><h1>Documents</h1><p>Your private business document hub for invoices, statements, receipts, filings and company records.</p></div><span className={styles.securityPill}><LockKeyhole size={13}/>Private storage · RLS protected</span></div>
  <DocumentUploader organizationId={workspace.organization.id} companyId={workspace.company.id}/>
  <section className={styles.folderGrid}>{folders.map(folder=><Link href={`/app/documents?category=${folder.key}`} className={`${styles.folderCard} ${category===folder.key?styles.folderActive:""}`} key={folder.key}><span><folder.icon size={17}/></span><div><strong>{folder.label}</strong><small>{count(folder.types)} document{count(folder.types)===1?"":"s"}</small></div></Link>)}</section>
  <section className={styles.library}><div className={styles.libraryHead}><div><p>{folders.find(f=>f.key===category)?.label??"Documents"}</p><h2>Company document library</h2></div><span>{shown} shown</span></div><form method="get" className={styles.tools}><input type="hidden" name="category" value={category}/><label><Search size={15}/><input name="q" defaultValue={params.q??""} placeholder="Search documents"/></label><button type="submit">Search</button></form>
  {shown===0?<div className={styles.empty}><div className={styles.emptyIcon}><FileCheck2 size={23}/></div><h3>{totalCount?"No documents in this folder.":"Your document vault starts here."}</h3><p>{totalCount?"Choose another folder or add a new document using the floating button.":"Add receipts, invoices, bank statements, filings and business documents from one place."}</p></div>:<div className={styles.docList}>
   {visibleStatements.map(batch=><article className={styles.docRow} key={`bank-batch-${batch.id}`}><div className={styles.docIdentity}><span className={styles.docIcon}><Landmark size={17}/></span><div><strong>{batch.file_name||"Imported bank statement"}</strong><small>Bank statement · {batch.imported_count} movements · {new Date(batch.created_at).toLocaleDateString("en-LU",{day:"2-digit",month:"short",year:"numeric"})}</small></div></div><div className={styles.extractionArea}><div className={styles.aiSummaryHead}><Landmark size={12}/><strong>Imported through Banking</strong><span>{batch.duplicate_count?`${batch.duplicate_count} duplicates skipped`:"Statement record"}</span></div><p className={styles.statementNote}>This historical import is represented in the document hub. Re-upload the original statement in Banking if you want the source file itself attached without duplicating movements.</p></div><div className={styles.docActions}><Link href="/app/banking" className={styles.openButton}>View banking <ExternalLink size={11}/></Link></div></article>)}
   {visible.map(doc=>{const extracted=extractionSummary(doc.extracted_data),aiSupported=["application/pdf","image/jpeg","image/png","image/webp"].includes(doc.mime_type??""),salesReady=extracted&&!extracted.error&&extracted.kind==="sales_invoice",match=bestLink.get(doc.id) as {id:string;match_score:number|string;status:string;source_transactions?:{occurred_on:string;counterparty_name:string|null;description:string|null;amount_gross:number|string;currency:string;classification_status:string}|null}|undefined,taxNotice=extracted&&!extracted.error&&extracted.kind==="tax_notice";return <article className={styles.docRow} key={doc.id}>
    <div className={styles.docIdentity}><span className={styles.docIcon}><FileText size={17}/></span><div><strong>{doc.file_name}</strong><small>{typeLabel[doc.type]??doc.type} · {sizeLabel(doc.file_size)} · {new Date(doc.created_at).toLocaleDateString("en-LU",{day:"2-digit",month:"short",year:"numeric"})}</small></div></div><div className={styles.docMeta}><span className={styles.statusPill}>{doc.extraction_status.replaceAll("_"," ")}</span></div>
    <div className={styles.extractionArea}>{extracted&&!extracted.error?<><div className={styles.aiSummaryHead}><Sparkles size={12}/><strong>{extracted.party||"Extracted document"}</strong>{extracted.confidence!==null?<span>{extracted.confidence}% confidence</span>:null}</div><div className={styles.aiSummaryGrid}><span><small>Total</small><strong>{extracted.total||"—"}</strong></span><span><small>VAT</small><strong>{extracted.vat||"—"}</strong></span><span><small>Treatment</small><strong>{salesReady?"Sales invoice → receivable":extracted.treatment||extracted.category||"Review"}</strong></span></div>{match?.source_transactions?<div className={styles.matchBox}><strong>{match.source_transactions.counterparty_name||match.source_transactions.description||"Recorded transaction"}</strong><span>{match.source_transactions.occurred_on} · {money(Number(match.source_transactions.amount_gross),match.source_transactions.currency)}</span></div>:null}</>:extracted?.error?<span className={styles.extractionError}>{extracted.error}</span>:<p>Analyze this document to identify parties, dates, amounts, VAT and the correct workflow.</p>}</div>
    <div className={styles.docActions}><Link href={`/app/documents/${doc.id}/open`} target="_blank" className={styles.openButton}>Open <ExternalLink size={11}/></Link>{aiSupported?<DocumentExtractionButton documentId={doc.id} status={doc.extraction_status}/>:null}{salesReady?<Link href={`/app/invoices/new?document=${doc.id}`} className={styles.secondaryAction}><WandSparkles size={11}/>Invoice draft</Link>:null}{extracted&&!extracted.error&&["receipt","purchase_invoice"].includes(extracted.kind??"")?<DocumentMatchActions documentId={doc.id} linkId={match?.id} score={match?Number(match.match_score):null} posted={match?.source_transactions?.classification_status==="posted"}/>:null}{taxNotice?<TaxNoticeAction documentId={doc.id} exists={taxDocs.has(doc.id)}/>:null}<DocumentRowActions id={doc.id} storagePath={doc.storage_path} fileName={doc.file_name} type={doc.type as "receipt"|"purchase_invoice"|"sales_invoice"|"bank_statement"|"tax_notice"|"filing"|"annex"|"other"}/></div>
   </article>})}
  </div>}
  <div className={styles.footer}><ShieldCheck size={13}/>Evidence stays separate from accounting entries; links are explicit and auditable.</div></section>
 </div>;
}
