import { ExternalLink, FileArchive, FileCheck2, FileSpreadsheet, FileText, Landmark, LockKeyhole, ReceiptText, Search, ShieldCheck, Sparkles, WandSparkles } from "lucide-react";
import Link from "next/link";
import { redirect } from "next/navigation";
import { DocumentUploader } from "@/components/document-uploader";
import { GeneratedDocumentDelete } from "@/components/generated-document-delete";
import { DocumentRowActions } from "@/components/document-row-actions";
import { DocumentExtractionButton } from "@/components/document-extraction-button";
import { DocumentMatchActions, TaxNoticeAction } from "@/components/document-workflow-actions";
import styles from "@/components/documents.module.css";
import { createClient } from "@/lib/supabase/server";
import { getWorkspace } from "@/lib/workspace";

export const dynamic="force-dynamic";
const typeLabel:Record<string,string>={receipt:"Receipt",purchase_invoice:"Supplier invoice",bank_statement:"Bank statement",tax_notice:"Tax notice",filing:"Filing",annex:"Annual accounts",sales_invoice:"Sales invoice",other:"Business document"};
const reportLabel:Record<string,string>={profit_loss:"Profit & Loss",balance_sheet:"Balance Sheet",trial_balance:"Trial Balance",pcn:"PCN Closing Balances",annual_accounts:"Annual Accounts",annexe:"Annexe to the Annual Accounts",general_ledger:"General Ledger",general_journal:"General Journal"};
const csvTypes=new Set(["profit_loss","balance_sheet","trial_balance","pcn","general_ledger","general_journal"]);
function sizeLabel(bytes:number|null){if(!bytes)return"—";return bytes>=1024*1024?`${(bytes/1024/1024).toFixed(2)} MB`:`${Math.max(1,Math.round(bytes/1024))} KB`}
function money(value:unknown,currency:unknown){const number=Number(value);if(!Number.isFinite(number))return null;return new Intl.NumberFormat("en-LU",{style:"currency",currency:typeof currency==="string"&&currency.length===3?currency:"EUR",minimumFractionDigits:2}).format(number)}
function extractionSummary(raw:unknown){if(!raw||typeof raw!=="object")return null;const d=raw as Record<string,unknown>;if(typeof d.error==="string")return{error:d.error};const kind=typeof d.document_kind==="string"?d.document_kind:null,party=kind==="sales_invoice"?(typeof d.customer_name==="string"?d.customer_name:null):(typeof d.issuer_name==="string"?d.issuer_name:null);return{kind,party,total:money(d.total,d.currency),category:typeof d.suggested_account_category==="string"?d.suggested_account_category:null,treatment:typeof d.suggested_vat_treatment==="string"?d.suggested_vat_treatment.replaceAll("_"," "):null,confidence:typeof d.confidence==="number"?Math.round(d.confidence*100):null}}
function archivedBatchId(raw:unknown){if(!raw||typeof raw!=="object")return null;const value=(raw as Record<string,unknown>).bank_import_batch_id;return typeof value==="string"?value:null}
function customerName(raw:unknown){if(!raw||typeof raw!=="object")return"Customer";const value=(raw as Record<string,unknown>).name;return typeof value==="string"&&value?value:"Customer"}
function dateLabel(value:string){return new Date(value.length===10?`${value}T12:00:00`:value).toLocaleDateString("en-LU",{day:"2-digit",month:"short",year:"numeric"})}
type Params=Promise<{category?:string;q?:string}>;
type LibraryItem={kind:"document"|"statement"|"invoice"|"report";date:string;data:any};

export default async function DocumentsPage({searchParams}:{searchParams:Params}){
 const params=await searchParams,allowed=new Set(["all","invoices","bank","reports"]),category=allowed.has(params.category??"all")?params.category??"all":"all",q=(params.q??"").trim().toLowerCase();
 const workspace=await getWorkspace();if(!workspace.authenticated)redirect("/sign-in");if(!workspace.company||!workspace.organization)redirect("/setup");const supabase=await createClient();
 const[{data,error},{data:links},{data:taxEvents},{data:bankBatches,error:batchError},{data:generated,error:generatedError},{data:invoices,error:invoiceError}]=await Promise.all([
  supabase.from("documents").select("id,type,file_name,mime_type,file_size,extraction_status,extracted_data,created_at,storage_path").eq("company_id",workspace.company.id).order("created_at",{ascending:false}).limit(300),
  supabase.from("document_transaction_links").select("id,document_id,source_transaction_id,match_score,status,source_transactions(occurred_on,counterparty_name,description,amount_gross,currency,classification_status)").eq("company_id",workspace.company.id).in("status",["suggested","confirmed"]).order("match_score",{ascending:false}),
  supabase.from("tax_events").select("id,source_document_id").eq("company_id",workspace.company.id),
  supabase.from("bank_import_batches").select("id,file_name,row_count,imported_count,duplicate_count,created_at").eq("company_id",workspace.company.id).order("created_at",{ascending:false}).limit(150),
  supabase.from("generated_documents").select("id,title,document_type,fiscal_year,generator_version,created_at").eq("company_id",workspace.company.id).order("created_at",{ascending:false}).limit(150),
  supabase.from("sales_invoices").select("id,invoice_number,status,payment_status,issue_date,currency,total,customer_snapshot,created_at").eq("company_id",workspace.company.id).neq("status","void").order("created_at",{ascending:false}).limit(150)
 ]);
 if(error)throw new Error(`Could not load documents: ${error.message}`);if(batchError)throw new Error(`Could not load bank statement records: ${batchError.message}`);if(generatedError)throw new Error(`Could not load generated reports: ${generatedError.message}`);if(invoiceError)throw new Error(`Could not load invoices: ${invoiceError.message}`);
 const docs=data??[],reportRows=generated??[],invoiceRows=invoices??[],archivedBatchIds=new Set(docs.map(doc=>archivedBatchId(doc.extracted_data)).filter((id):id is string=>Boolean(id))),statementRecords=(bankBatches??[]).filter(batch=>!archivedBatchIds.has(batch.id));
 const bestLink=new Map<string,(typeof links extends Array<infer T>?T:never)>();for(const link of links??[]){if(!bestLink.has(link.document_id)||link.status==="confirmed")bestLink.set(link.document_id,link as never)}const taxDocs=new Set((taxEvents??[]).map(e=>e.source_document_id).filter(Boolean));
 const bankDocs=docs.filter(doc=>doc.type==="bank_statement"),bankCount=bankDocs.length+statementRecords.length,totalCount=docs.length+statementRecords.length+invoiceRows.length+reportRows.length;
 const folders=[
  {key:"all",label:"All Documents",icon:FileArchive,count:totalCount},
  {key:"invoices",label:"Invoices",icon:ReceiptText,count:invoiceRows.length},
  {key:"bank",label:"Bank Statements",icon:Landmark,count:bankCount},
  {key:"reports",label:"Financial Reports",icon:FileSpreadsheet,count:reportRows.length}
 ];
 const items:LibraryItem[]=[];
 if(category==="all")for(const doc of docs){if(!q||`${doc.file_name} ${typeLabel[doc.type]??doc.type}`.toLowerCase().includes(q))items.push({kind:"document",date:doc.created_at,data:doc})}
 if(category==="all"||category==="bank")for(const batch of statementRecords){if(!q||`${batch.file_name??"Bank statement"} bank statement banking`.toLowerCase().includes(q))items.push({kind:"statement",date:batch.created_at,data:batch})}
 if(category==="all"||category==="invoices")for(const invoice of invoiceRows){const haystack=`${invoice.invoice_number??"draft invoice"} ${customerName(invoice.customer_snapshot)} invoice ${invoice.status}`.toLowerCase();if(!q||haystack.includes(q))items.push({kind:"invoice",date:invoice.created_at,data:invoice})}
 if(category==="all"||category==="reports")for(const report of reportRows){const label=reportLabel[report.document_type]??report.title;if(!q||`${label} ${report.fiscal_year} financial report`.toLowerCase().includes(q))items.push({kind:"report",date:report.created_at,data:report})}
 if(category==="bank")for(const doc of bankDocs){if(!q||`${doc.file_name} bank statement`.toLowerCase().includes(q))items.push({kind:"document",date:doc.created_at,data:doc})}
 items.sort((a,b)=>new Date(b.date).getTime()-new Date(a.date).getTime());
 const activeFolder=folders.find(folder=>folder.key===category)??folders[0];
 return <div className={styles.page}>
  <div className={styles.intro}><div><p>Document centre</p><h1>Documents</h1><p>Invoices, bank statements, financial reports and source evidence in one searchable library.</p></div><span className={styles.securityPill}><LockKeyhole size={13}/>Private storage · RLS protected</span></div>
  <DocumentUploader organizationId={workspace.organization.id} companyId={workspace.company.id}/>
  <section className={styles.folderGrid}>{folders.map(folder=><Link href={`/app/documents?category=${folder.key}`} className={`${styles.folderCard} ${category===folder.key?styles.folderActive:""}`} key={folder.key}><span><folder.icon size={18}/></span><div><strong>{folder.label}</strong><small>{folder.count} document{folder.count===1?"":"s"}</small></div></Link>)}</section>
  <section className={styles.library}>
   <div className={styles.libraryHead}><div><p>Library</p><h2>{activeFolder.label}</h2></div><span>{items.length} shown</span></div>
   <form method="get" className={styles.tools}><input type="hidden" name="category" value={category}/><label><Search size={15}/><input name="q" defaultValue={params.q??""} placeholder={`Search ${activeFolder.label.toLowerCase()}`}/></label><button type="submit">Search</button></form>
   {items.length===0?<div className={styles.empty}><div className={styles.emptyIcon}><FileCheck2 size={23}/></div><h3>{totalCount?"No documents match this view.":"Your document library starts here."}</h3><p>{totalCount?"Try another category or search term.":"Create an invoice, import a bank statement, generate a financial report or upload source evidence."}</p></div>:<div className={styles.docList}>{items.map(item=>{
    if(item.kind==="statement"){const batch=item.data;return <article className={styles.docRow} key={`bank-batch-${batch.id}`}><div className={styles.docIdentity}><span className={styles.docIcon}><Landmark size={17}/></span><div><strong>{batch.file_name||"Imported bank statement"}</strong><small>Bank statement · imported through Banking</small></div></div><div className={styles.docDetail}><strong>{batch.imported_count} movements</strong><span>{batch.duplicate_count?`${batch.duplicate_count} duplicates skipped`:"Import completed"}</span></div><time className={styles.docDate}>{dateLabel(batch.created_at)}</time><div className={styles.docActions}><Link href="/app/banking" className={styles.openButton}>View <ExternalLink size={11}/></Link></div></article>}
    if(item.kind==="invoice"){const invoice=item.data;return <article className={styles.docRow} key={`invoice-${invoice.id}`}><div className={styles.docIdentity}><span className={styles.docIcon}><ReceiptText size={17}/></span><div><strong>{invoice.invoice_number||"Draft invoice"}</strong><small>Invoice · {invoice.status==="draft"?"draft":invoice.payment_status}</small></div></div><div className={styles.docDetail}><strong>{customerName(invoice.customer_snapshot)}</strong><span>{money(invoice.total,invoice.currency)||"—"}</span></div><time className={styles.docDate}>{dateLabel(invoice.issue_date)}</time><div className={styles.docActions}><Link href={`/app/invoices/${invoice.id}`} className={styles.openButton}>View <ExternalLink size={11}/></Link></div></article>}
    if(item.kind==="report"){const report=item.data,label=reportLabel[report.document_type]??String(report.title).replaceAll("FY ","");const displayTitle=`${label} · ${report.fiscal_year}`;return <article className={styles.docRow} key={`report-${report.id}`}><div className={styles.docIdentity}><span className={styles.docIcon}><FileSpreadsheet size={17}/></span><div><strong>{displayTitle}</strong><small>Financial report · generator {report.generator_version}</small></div></div><div className={styles.docDetail}><strong>Frozen closing snapshot</strong><span>Versioned output</span></div><time className={styles.docDate}>{dateLabel(report.created_at)}</time><div className={styles.docActions}><Link href={`/app/documents/generated/${report.id}/pdf`} className={styles.openButton}>PDF</Link>{csvTypes.has(report.document_type)?<Link href={`/app/documents/generated/${report.id}/csv`} className={styles.secondaryAction}>CSV</Link>:null}<GeneratedDocumentDelete id={report.id} title={displayTitle}/></div></article>}
    const doc=item.data,extracted=extractionSummary(doc.extracted_data),aiSupported=["application/pdf","image/jpeg","image/png","image/webp"].includes(doc.mime_type??""),salesReady=extracted&&!extracted.error&&extracted.kind==="sales_invoice",match=bestLink.get(doc.id) as {id:string;match_score:number|string;status:string;source_transactions?:{occurred_on:string;counterparty_name:string|null;description:string|null;amount_gross:number|string;currency:string;classification_status:string}|null}|undefined,taxNotice=extracted&&!extracted.error&&extracted.kind==="tax_notice";
    const summary=extracted&&!extracted.error?(extracted.party||extracted.total||extracted.treatment||extracted.category||"Extracted document"):extracted?.error?"Needs extraction review":"Source document";
    return <article className={styles.docRow} key={doc.id}><div className={styles.docIdentity}><span className={styles.docIcon}><FileText size={17}/></span><div><strong>{doc.file_name}</strong><small>{typeLabel[doc.type]??doc.type} · {sizeLabel(doc.file_size)}</small></div></div><div className={styles.docDetail}>{extracted&&!extracted.error?<><strong><Sparkles size={11}/>{summary}</strong><span>{[extracted.total,extracted.confidence!==null?`${extracted.confidence}% confidence`:null].filter(Boolean).join(" · ")||"Analyzed"}</span></>:<><strong>{summary}</strong><span>{doc.extraction_status.replaceAll("_"," ")}</span></>}</div><time className={styles.docDate}>{dateLabel(doc.created_at)}</time><div className={styles.docActions}><Link href={`/app/documents/${doc.id}/open`} target="_blank" className={styles.openButton}>View <ExternalLink size={11}/></Link>{aiSupported?<DocumentExtractionButton documentId={doc.id} status={doc.extraction_status}/>:null}{salesReady?<Link href={`/app/invoices/new?document=${doc.id}`} className={styles.secondaryAction}><WandSparkles size={11}/>Invoice</Link>:null}{extracted&&!extracted.error&&["receipt","purchase_invoice"].includes(extracted.kind??"")?<DocumentMatchActions documentId={doc.id} linkId={match?.id} score={match?Number(match.match_score):null} posted={match?.source_transactions?.classification_status==="posted"}/>:null}{taxNotice?<TaxNoticeAction documentId={doc.id} exists={taxDocs.has(doc.id)}/>:null}<DocumentRowActions id={doc.id} storagePath={doc.storage_path} fileName={doc.file_name} type={doc.type as "receipt"|"purchase_invoice"|"sales_invoice"|"bank_statement"|"tax_notice"|"filing"|"annex"|"other"}/></div></article>
   })}</div>}
   <div className={styles.footer}><ShieldCheck size={13}/>Source evidence stays separate from accounting entries; generated reports remain tied to their closing snapshots.</div>
  </section>
 </div>;
}
