import { AlertTriangle, CalendarCheck2, ExternalLink } from "lucide-react";
import Link from "next/link";
import { redirect } from "next/navigation";
import { ComplianceSyncButton } from "@/components/compliance-sync-button";
import { ComplianceStatusControl } from "@/components/compliance-status-control";
import styles from "@/components/compliance.module.css";
import { createClient } from "@/lib/supabase/server";
import { getWorkspace } from "@/lib/workspace";
export const dynamic="force-dynamic";
function meta(row:{metadata:unknown}){return row.metadata&&typeof row.metadata==="object"?row.metadata as Record<string,unknown>:{};}function url(row:{metadata:unknown}){const value=meta(row).source_url;return typeof value==="string"?value:null}
export default async function CompliancePage(){
 const workspace=await getWorkspace();if(!workspace.authenticated)redirect("/sign-in");if(!workspace.company)redirect("/setup");
 const year=new Date().getFullYear(),today=new Date(),todayKey=today.toISOString().slice(0,10),supabase=await createClient();
 const[{data,error},pendingTx,unknownVat,annualSnapshot,taxProfile,taxNotices]=await Promise.all([
  supabase.from("compliance_obligations").select("id,authority,obligation_type,period_label,due_date,amount,currency,status,rule_key,rule_version,metadata").eq("company_id",workspace.company.id).order("due_date",{ascending:true,nullsFirst:false}),
  supabase.from("source_transactions").select("id",{count:"exact",head:true}).eq("company_id",workspace.company.id).in("classification_status",["unclassified","review","classified"]),
  supabase.from("source_transactions").select("id",{count:"exact",head:true}).eq("company_id",workspace.company.id).eq("classification_status","posted").eq("vat_treatment","unknown").or("counterparty_country.not.is.null,vat_amount.gt.0"),
  supabase.from("filings").select("id,snapshot_at").eq("company_id",workspace.company.id).eq("filing_type","ecdf_accounts").eq("period_label",String(year)).order("created_at",{ascending:false}).limit(1).maybeSingle(),
  supabase.from("company_tax_profiles").select("icc_multiplier").eq("company_id",workspace.company.id).maybeSingle(),
  supabase.from("tax_events").select("id",{count:"exact",head:true}).eq("company_id",workspace.company.id)
 ]);if(error)throw new Error(`Could not load compliance calendar: ${error.message}`);
 const rows=data??[],active=rows.filter(r=>!["paid","filed","not_applicable"].includes(r.status)),next=active.find(r=>r.due_date&&r.due_date>=todayKey)??active[0]??null,overdue=active.filter(r=>r.due_date&&r.due_date<todayKey).length,completed=rows.filter(r=>["paid","filed"].includes(r.status)).length,health=rows.length?Math.max(0,Math.round(((rows.length-overdue)/rows.length)*100)):100,nextDate=next?.due_date?new Date(`${next.due_date}T12:00:00`):null,days=nextDate?Math.ceil((nextDate.getTime()-today.getTime())/86400000):null,vatReady=(pendingTx.count??0)===0&&(unknownVat.count??0)===0,annualReady=Boolean(annualSnapshot.data),taxReady=taxProfile.data?.icc_multiplier!=null,noticeCount=taxNotices.count??0;
 return <div className={styles.page}><div className={styles.intro}><div><p>Compliance · Luxembourg</p><h1>Your runway.</h1><p>Every obligation now has an explicit lifecycle: upcoming → preparing → ready → filed/paid. Dates, evidence and completion state remain auditable.</p></div><ComplianceSyncButton year={year}/></div>
 <section className={styles.hero}><article className={styles.nextCard}><div className={styles.nextTop}><span className={styles.authority}>{next?.authority??"COMPTA"}</span><span className={styles.days}>{days===null?"No scheduled deadline":days<0?`${Math.abs(days)} days overdue`:days===0?"Due today":`${days} days remaining`}</span></div><div className={styles.date}>{nextDate?nextDate.getDate():"—"}{nextDate?<span>{nextDate.toLocaleDateString("en-LU",{month:"short"}).toUpperCase()}</span>:null}</div><h2>{next?.obligation_type??"Calendar is clear"}</h2><p>{next?`${next.period_label??year} · ${next.status.replaceAll("_"," ")}`:"Refresh rules to generate the current company calendar."}</p></article><aside className={styles.health}><p className={styles.kicker}>Compliance health</p><h2>{overdue?"Action required":"On track"}</h2><div className={styles.healthRing} style={{"--pct":`${health}%`} as React.CSSProperties}><div><strong>{health}%</strong><span>healthy</span></div></div><div className={styles.healthStats}><div><span>Active</span><strong>{active.length}</strong></div><div><span>Overdue</span><strong>{overdue}</strong></div><div><span>Completed</span><strong>{completed}</strong></div><div><span>Rules version</span><strong>2026.1</strong></div></div></aside></section>
 <section className={styles.deps}><Link href="/app/vat" className={styles.dep}><div className={styles.depTop}><span>VAT filing</span><b className={vatReady?"":styles.needs}>{vatReady?"ready":"review"}</b></div><strong>{vatReady?"Return data structurally ready":"VAT evidence has gaps"}</strong><small>{pendingTx.count??0} unreviewed · {unknownVat.count??0} unknown VAT</small></Link><Link href="/app/year-end" className={styles.dep}><div className={styles.depTop}><span>Annual accounts</span><b className={annualReady?"":styles.needs}>{annualReady?"frozen":"open"}</b></div><strong>{annualReady?"Closing snapshot exists":"Year-end not frozen"}</strong><small>Closing controls prevent accidental back-posting.</small></Link><Link href="/app/tax-reserve" className={styles.dep}><div className={styles.depTop}><span>Direct taxes</span><b className={taxReady?"":styles.needs}>{taxReady?"profiled":"input"}</b></div><strong>{taxReady?"Municipal input confirmed":"Tax reserve needs profile"}</strong><small>Estimates stay separate from assessed notices.</small></Link><Link href="/app/taxes" className={styles.dep}><div className={styles.depTop}><span>Authority evidence</span><b className={noticeCount?"":styles.needs}>{noticeCount?`${noticeCount} cases`:"none"}</b></div><strong>{noticeCount?"Tax notices are tracked":"Import authority notices"}</strong><small>Payments can be matched directly to notice amounts.</small></Link></section>
 <section className={styles.section}><div className={styles.sectionHead}><div><p className={styles.kicker}>Calendar</p><h2>Obligations & workflow</h2></div><span>{rows.length} rule slots</span></div>{rows.length===0?<div className={styles.empty}><CalendarCheck2 size={24}/><h3>No obligations generated yet.</h3><p>Refresh the rules to build the current company calendar.</p></div>:<div className={styles.timeline}>{rows.map(row=>{const due=row.due_date?new Date(`${row.due_date}T12:00:00`):null,isOverdue=!!row.due_date&&row.due_date<todayKey&&!['paid','filed','not_applicable'].includes(row.status),source=url(row);return <div className={styles.row} key={row.id}><div className={styles.dateCol}><strong>{due?due.toLocaleDateString("en-LU",{day:"2-digit",month:"short"}):"Event"}</strong><span>{due?due.getFullYear():"triggered"}</span></div><span className={`${styles.node} ${isOverdue?styles.overdue:""}`}/><div className={styles.rowMain}><span>{row.authority} · {row.rule_key??"custom"}</span><strong>{row.obligation_type}</strong><small>{row.period_label??"—"}{meta(row).note?` · ${String(meta(row).note)}`:""}</small></div><div className={styles.rowSide}><ComplianceStatusControl id={row.id} status={row.status}/>{source?<a className={styles.sourceLink} href={source} target="_blank" rel="noreferrer">Official source <ExternalLink size={9}/></a>:null}</div></div>})}</div>}</section><div className={styles.footnote}><AlertTriangle size={13}/><span>Completion states are operational evidence in Compta; they do not claim an authority accepted a filing unless you explicitly mark it filed/paid after confirmation.</span></div></div>;
}
