import { AlertTriangle, CalendarCheck2, ExternalLink } from "lucide-react";
import Link from "next/link";
import { redirect } from "next/navigation";
import { ComplianceSyncButton } from "@/components/compliance-sync-button";
import { ComplianceStatusControl } from "@/components/compliance-status-control";
import { fiscalYearBounds, getActiveFiscalYear } from "@/lib/fiscal-year";
import { createClient } from "@/lib/supabase/server";
import { getWorkspace } from "@/lib/workspace";
import styles from "./compliance-v2.module.css";
export const dynamic="force-dynamic";
function meta(row:{metadata:unknown}){return row.metadata&&typeof row.metadata==="object"?row.metadata as Record<string,unknown>:{};}function url(row:{metadata:unknown}){const value=meta(row).source_url;return typeof value==="string"?value:null}
export default async function CompliancePage(){
 const workspace=await getWorkspace();if(!workspace.authenticated)redirect("/sign-in");if(!workspace.company)redirect("/setup");
 const year=await getActiveFiscalYear(workspace.company.fiscal_year_start_month),bounds=fiscalYearBounds(year,workspace.company.fiscal_year_start_month),today=new Date(),todayKey=today.toISOString().slice(0,10),in30=new Date(today.getTime()+30*86400000).toISOString().slice(0,10),supabase=await createClient();
 const[{data,error},pendingTx,unknownVat,annualSnapshot,taxProfile,taxNotices]=await Promise.all([
  supabase.from("compliance_obligations").select("id,authority,obligation_type,period_label,due_date,amount,currency,status,rule_key,rule_version,metadata").eq("company_id",workspace.company.id).eq("period_label",String(year)).order("due_date",{ascending:true,nullsFirst:false}),
  supabase.from("source_transactions").select("id",{count:"exact",head:true}).eq("company_id",workspace.company.id).in("classification_status",["unclassified","review","classified"]).gte("occurred_on",bounds.start).lte("occurred_on",bounds.end),
  supabase.from("source_transactions").select("id",{count:"exact",head:true}).eq("company_id",workspace.company.id).eq("classification_status","posted").eq("vat_treatment","unknown").or("counterparty_country.not.is.null,vat_amount.gt.0").gte("occurred_on",bounds.start).lte("occurred_on",bounds.end),
  supabase.from("filings").select("id,snapshot_at").eq("company_id",workspace.company.id).eq("filing_type","ecdf_accounts").eq("period_label",String(year)).order("created_at",{ascending:false}).limit(1).maybeSingle(),
  supabase.from("company_tax_profiles").select("icc_multiplier,icc_multiplier_year").eq("company_id",workspace.company.id).maybeSingle(),
  supabase.from("tax_events").select("id",{count:"exact",head:true}).eq("company_id",workspace.company.id).eq("tax_year",year)
 ]);if(error)throw new Error(`Could not load compliance calendar: ${error.message}`);
 const rows=data??[],completed=rows.filter(r=>["paid","filed","not_applicable"].includes(r.status)),active=rows.filter(r=>!["paid","filed","not_applicable"].includes(r.status)),overdue=active.filter(r=>r.due_date&&r.due_date<todayKey),upcoming=active.filter(r=>!r.due_date||r.due_date>=todayKey),next=upcoming.find(r=>r.due_date)??active[0]??null,next30=upcoming.filter(r=>r.due_date&&r.due_date<=in30).length,inProgress=active.filter(r=>["preparing","ready"].includes(r.status)).length,nextDate=next?.due_date?new Date(`${next.due_date}T12:00:00`):null,days=nextDate?Math.ceil((nextDate.getTime()-today.getTime())/86400000):null,vatReady=(pendingTx.count??0)===0&&(unknownVat.count??0)===0,annualReady=Boolean(annualSnapshot.data),taxReady=taxProfile.data?.icc_multiplier!=null&&Number(taxProfile.data?.icc_multiplier_year)===year,noticeCount=taxNotices.count??0;
 const obligationRow=(row:(typeof rows)[number],isOverdue=false,isCompleted=false)=>{const due=row.due_date?new Date(`${row.due_date}T12:00:00`):null,source=url(row);return <div className={`${styles.row} ${isOverdue?styles.overdueRow:""} ${isCompleted?styles.completedRow:""}`} key={row.id}><div className={styles.rowDate}><strong>{due?due.toLocaleDateString("en-LU",{day:"2-digit",month:"short"}):"Event"}</strong><span>{due?due.getFullYear():"triggered"}</span></div><div className={styles.rowCopy}><span>{row.authority} · {row.rule_key??"custom"}</span><strong>{row.obligation_type}</strong><small>{row.period_label??"—"}{meta(row).note?` · ${String(meta(row).note)}`:""}</small></div><div className={styles.rowSide}><ComplianceStatusControl id={row.id} status={row.status}/>{source?<a href={source} target="_blank" rel="noreferrer">Official source <ExternalLink size={9}/></a>:null}</div></div>};
 return <div className={styles.page}>
  <div className={styles.intro}><div><p>Compliance · Luxembourg · FY {year}</p><h1>Compliance center</h1><h2>See the obligations generated for financial year {year}, even when their statutory due dates fall in {year+1}.</h2></div><div className={styles.syncSlot}><ComplianceSyncButton year={year}/></div></div>
  <section className={styles.metrics}><article className={`${styles.metric} ${overdue.length?styles.danger:""}`}><span>Overdue</span><strong>{overdue.length}</strong><small>{overdue.length?"Needs attention now":"Nothing overdue"}</small></article><article className={styles.metric}><span>Next 30 days</span><strong>{next30}</strong><small>Upcoming {year} obligations</small></article><article className={styles.metric}><span>In progress</span><strong>{inProgress}</strong><small>Preparing or ready</small></article><article className={styles.metric}><span>Completed</span><strong>{completed.length}</strong><small>Filed, paid or not applicable</small></article></section>
  <article className={styles.nextCard}><div className={styles.dateBlock}><strong>{nextDate?nextDate.getDate():"—"}</strong><span>{nextDate?nextDate.toLocaleDateString("en-LU",{month:"short"}).toUpperCase():"CLEAR"}</span></div><div className={styles.nextCopy}><span>Next FY {year} obligation</span><strong>{next?.obligation_type??"No active deadline"}</strong><small>{next?`${next.authority} · ${next.period_label??year} · ${next.status.replaceAll("_"," ")}`:`No obligations generated for ${year}. Refresh rules to create them.`}</small></div><div className={styles.nextSide}><b>{days===null?"No dated deadline":days<0?`${Math.abs(days)} days overdue`:days===0?"Due today":`${days} days remaining`}</b>{next&&url(next)?<a href={url(next)!} target="_blank" rel="noreferrer">Official source <ExternalLink size={9}/></a>:null}</div></article>
  <section className={styles.readiness}><Link href="/app/vat" className={styles.readyCard}><div className={styles.readyTop}><span>VAT · {year}</span><b className={vatReady?"":styles.needs}>{vatReady?"ready":"review"}</b></div><strong>{vatReady?"VAT data structurally ready":"VAT evidence still has gaps"}</strong><small>{pendingTx.count??0} unreviewed transactions · {unknownVat.count??0} unknown VAT treatments</small></Link><Link href="/app/year-end" className={styles.readyCard}><div className={styles.readyTop}><span>Annual accounts · {year}</span><b className={annualReady?"":styles.needs}>{annualReady?"frozen":"open"}</b></div><strong>{annualReady?"Closing snapshot exists":"Year-end remains open"}</strong><small>Review the FY {year} closing checklist before annual-account preparation.</small></Link><Link href="/app/tax-reserve" className={styles.readyCard}><div className={styles.readyTop}><span>Direct taxes · {year}</span><b className={taxReady?"":styles.needs}>{taxReady?"profiled":"input"}</b></div><strong>{taxReady?"Municipal tax input confirmed":`${year} tax estimate needs profile data`}</strong><small>Historical estimates never reuse a different year’s municipal multiplier silently.</small></Link><Link href="/app/taxes" className={styles.readyCard}><div className={styles.readyTop}><span>Authority evidence · {year}</span><b className={noticeCount?"":styles.needs}>{noticeCount?`${noticeCount} cases`:"none"}</b></div><strong>{noticeCount?"Tax notices are tracked":"No authority notices imported"}</strong><small>Notice amounts and payments stay evidence-driven.</small></Link></section>
  <section className={styles.sections}><article className={styles.section}><div className={styles.sectionHead}><div><p>Action & upcoming · FY {year}</p><h2>Open obligations</h2></div><span>{active.length} active</span></div>{active.length===0?<div className={styles.empty}><CalendarCheck2 size={20}/><p>No open obligations for {year}. Refresh rules if the year has not been generated yet.</p></div>:<div className={styles.list}>{overdue.map(row=>obligationRow(row,true,false))}{upcoming.map(row=>obligationRow(row,false,false))}</div>}</article><article className={styles.section}><div className={styles.sectionHead}><div><p>History · FY {year}</p><h2>Completed</h2></div><span>{completed.length}</span></div>{completed.length===0?<div className={styles.empty}>Completed filings and payments will appear here.</div>:<div className={styles.list}>{completed.slice(0,12).map(row=>obligationRow(row,false,true))}</div>}</article></section>
  <div className={styles.notice}><AlertTriangle size={13}/><span>Compta’s workflow status is an internal record. It never claims an authority accepted a filing unless you explicitly mark it filed or paid after confirmation.</span></div>
 </div>;
}
