"use server";

import { revalidatePath } from "next/cache";
import { createClient } from "@/lib/supabase/server";
import { getWorkspace } from "@/lib/workspace";

export type InvoiceActionState={status:"idle"|"success"|"error";message:string;invoiceId:string|null};
type ParsedInvoice={customerName:string;customerEmail:string;customerCountry:string;customerVat:string;issueDate:string;serviceDate:string;dueDate:string;vatTreatment:string;street:string;postalCode:string;city:string;notes:string;lines:unknown[]};
function parseInvoice(formData:FormData):ParsedInvoice|{error:string}{const customerName=String(formData.get("customer_name")??"").trim(),customerEmail=String(formData.get("customer_email")??"").trim(),customerCountry=String(formData.get("customer_country")??"LU").trim().toUpperCase(),customerVat=String(formData.get("customer_vat_number")??"").trim(),issueDate=String(formData.get("issue_date")??""),serviceDate=String(formData.get("service_date")??""),dueDate=String(formData.get("due_date")??""),vatTreatment=String(formData.get("vat_treatment")??"domestic"),street=String(formData.get("customer_street")??"").trim(),postalCode=String(formData.get("customer_postal_code")??"").trim(),city=String(formData.get("customer_city")??"").trim(),notes=String(formData.get("notes")??"").trim();if(!customerName||!street||!postalCode||!city)return{error:"Customer name and full billing address are required."};if(!/^[A-Z]{2}$/.test(customerCountry))return{error:"Use a two-letter country code such as LU, FR or DE."};if(![issueDate,serviceDate,dueDate].every(v=>/^\d{4}-\d{2}-\d{2}$/.test(v)))return{error:"Invoice, service and due dates are required."};if(!["domestic","eu_b2b_reverse_charge"].includes(vatTreatment))return{error:"Unsupported VAT treatment."};let lines:unknown;try{lines=JSON.parse(String(formData.get("lines_json")??"[]"))}catch{return{error:"The invoice lines could not be read."}}if(!Array.isArray(lines)||lines.length===0)return{error:"Add at least one invoice line."};return{customerName,customerEmail,customerCountry,customerVat,issueDate,serviceDate,dueDate,vatTreatment,street,postalCode,city,notes,lines}}
function refreshInvoicePaths(id?:string){revalidatePath("/app");revalidatePath("/app/invoices");revalidatePath("/app/accounting");revalidatePath("/app/taxes");if(id)revalidatePath(`/app/invoices/${id}`)}

export async function saveOrIssueInvoice(_previous:InvoiceActionState,formData:FormData):Promise<InvoiceActionState>{const workspace=await getWorkspace();if(!workspace.authenticated||!workspace.company)return{status:"error",message:"Your session expired. Please sign in again.",invoiceId:null};const parsed=parseInvoice(formData);if("error" in parsed)return{status:"error",message:parsed.error,invoiceId:null};const intent=String(formData.get("intent")??"save_draft"),draftId=String(formData.get("draft_invoice_id")??"").trim()||null;if(draftId&&!/^[0-9a-f-]{36}$/i.test(draftId))return{status:"error",message:"Invalid draft invoice.",invoiceId:null};const supabase=await createClient();const{data,error}=await supabase.rpc("save_service_invoice_draft",{p_company_id:workspace.company.id,p_invoice_id:draftId,p_customer_name:parsed.customerName,p_customer_email:parsed.customerEmail||null,p_customer_country:parsed.customerCountry,p_customer_vat_number:parsed.customerVat||null,p_customer_address:{street:parsed.street,postal_code:parsed.postalCode,city:parsed.city,country_code:parsed.customerCountry},p_issue_date:parsed.issueDate,p_service_date:parsed.serviceDate,p_due_date:parsed.dueDate,p_vat_treatment:parsed.vatTreatment,p_lines:parsed.lines,p_notes:parsed.notes||null});if(error)return{status:"error",message:error.message,invoiceId:null};const invoiceId=typeof data==="string"?data:null;if(!invoiceId)return{status:"error",message:"The draft was saved but no invoice ID was returned.",invoiceId:null};if(intent==="issue"){const{error:issueError}=await supabase.rpc("issue_service_invoice_draft",{p_invoice_id:invoiceId});if(issueError)return{status:"error",message:`Draft saved, but it could not be issued: ${issueError.message}`,invoiceId};refreshInvoicePaths(invoiceId);return{status:"success",message:"Invoice issued and posted to the ledger.",invoiceId}}refreshInvoicePaths(invoiceId);return{status:"success",message:"Draft saved. Nothing has been posted to the ledger yet.",invoiceId}}

export async function issueDraftInvoiceAction(_previous:InvoiceActionState,formData:FormData):Promise<InvoiceActionState>{const workspace=await getWorkspace();if(!workspace.authenticated||!workspace.company)return{status:"error",message:"Your session expired. Please sign in again.",invoiceId:null};const invoiceId=String(formData.get("invoice_id")??"");if(!/^[0-9a-f-]{36}$/i.test(invoiceId))return{status:"error",message:"Invalid invoice.",invoiceId:null};const supabase=await createClient();const{error}=await supabase.rpc("issue_service_invoice_draft",{p_invoice_id:invoiceId});if(error)return{status:"error",message:error.message,invoiceId:null};refreshInvoicePaths(invoiceId);return{status:"success",message:"Invoice issued and posted.",invoiceId}}

export async function correctAndReissueInvoice(_previous:InvoiceActionState,formData:FormData):Promise<InvoiceActionState>{const workspace=await getWorkspace();if(!workspace.authenticated||!workspace.company)return{status:"error",message:"Your session expired. Please sign in again.",invoiceId:null};const originalId=String(formData.get("original_invoice_id")??"");if(!/^[0-9a-f-]{36}$/i.test(originalId))return{status:"error",message:"Invalid original invoice.",invoiceId:null};const parsed=parseInvoice(formData);if("error" in parsed)return{status:"error",message:parsed.error,invoiceId:null};const supabase=await createClient();const{data,error}=await supabase.rpc("correct_and_reissue_service_invoice",{p_invoice_id:originalId,p_customer_name:parsed.customerName,p_customer_email:parsed.customerEmail||null,p_customer_country:parsed.customerCountry,p_customer_vat_number:parsed.customerVat||null,p_customer_address:{street:parsed.street,postal_code:parsed.postalCode,city:parsed.city,country_code:parsed.customerCountry},p_issue_date:parsed.issueDate,p_service_date:parsed.serviceDate,p_due_date:parsed.dueDate,p_vat_treatment:parsed.vatTreatment,p_lines:parsed.lines,p_notes:parsed.notes||null});if(error)return{status:"error",message:error.message,invoiceId:null};const invoiceId=typeof data==="string"?data:null;if(!invoiceId)return{status:"error",message:"Correction failed to return a replacement invoice.",invoiceId:null};refreshInvoicePaths(originalId);refreshInvoicePaths(invoiceId);return{status:"success",message:"Original invoice reversed and corrected invoice issued.",invoiceId}}

export async function voidInvoiceAction(_previous:InvoiceActionState,formData:FormData):Promise<InvoiceActionState>{const workspace=await getWorkspace();if(!workspace.authenticated||!workspace.company)return{status:"error",message:"Your session expired. Please sign in again.",invoiceId:null};const invoiceId=String(formData.get("invoice_id")??"");if(!/^[0-9a-f-]{36}$/i.test(invoiceId))return{status:"error",message:"Invalid invoice.",invoiceId:null};const supabase=await createClient();const{data:invoice,error:loadError}=await supabase.from("sales_invoices").select("status").eq("id",invoiceId).eq("company_id",workspace.company.id).maybeSingle();if(loadError||!invoice)return{status:"error",message:loadError?.message||"Invoice not found.",invoiceId:null};if(invoice.status==="draft"){const{error}=await supabase.from("sales_invoices").delete().eq("id",invoiceId);if(error)return{status:"error",message:error.message,invoiceId:null};refreshInvoicePaths();return{status:"success",message:"Draft deleted.",invoiceId:null}}const{error}=await supabase.rpc("void_sales_invoice_safe",{p_invoice_id:invoiceId});if(error)return{status:"error",message:error.message,invoiceId:null};refreshInvoicePaths(invoiceId);return{status:"success",message:"Invoice deleted from active receivables and reversed in the ledger.",invoiceId:null}}
