import { ArrowRight, CircleCheck, Clock3, ExternalLink, FileText, Pencil, Plus, ReceiptText } from "lucide-react";
import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { getWorkspace } from "@/lib/workspace";
import styles from "./invoice-list.module.css";

export const dynamic="force-dynamic";
function money(value:number,currency:string){return new Intl.NumberFormat("en-LU",{style:"currency",currency,minimumFractionDigits:2}).format(value)}
function customerName(snapshot:unknown){if(!snapshot||typeof snapshot!=="object")return"Customer";const value=(snapshot as Record<string,unknown>).name;return typeof value==="string"&&value?value:"Customer"}
export default async function InvoicesPage(){
 const workspace=await getWorkspace();if(!workspace.authenticated)redirect("/sign-in");if(!workspace.company)redirect("/setup");const supabase=await createClient();
 const[invoiceResult,paymentResult]=await Promise.all([supabase.from("sales_invoices").select("id,invoice_number,status,payment_status,issue_date,due_date,currency,subtotal,vat_total,total,customer_snapshot,issued_at,created_at").eq("company_id",workspace.company.id).neq("status","void").order("created_at",{ascending:false}),supabase.from("invoice_payments").select("invoice_id,amount").eq("company_id",workspace.company.id)]);if(invoiceResult.error)throw new Error(`Could not load invoices: ${invoiceResult.error.message}`);if(paymentResult.error)throw new Error(`Could not load payments: ${paymentResult.error.message}`);
 const invoices=invoiceResult.data??[],paidByInvoice=new Map<string,number>();for(const payment of paymentResult.data??[])paidByInvoice.set(payment.invoice_id,(paidByInvoice.get(payment.invoice_id)??0)+Number(payment.amount));const issued=invoices.filter(i=>i.status==="issued"),drafts=invoices.filter(i=>i.status==="draft"),today=new Date().toISOString().slice(0,10),outstanding=issued.reduce((sum,invoice)=>sum+Math.max(0,Number(invoice.total)-(paidByInvoice.get(invoice.id)??0)),0),overdue=issued.filter(invoice=>invoice.payment_status!=="paid"&&invoice.due_date<today).length,paid=issued.filter(invoice=>invoice.payment_status==="paid").length,currency=workspace.company.base_currency||"EUR";
 return <div className={styles.page}>
  <div className={styles.intro}><div><p>Sales & receivables</p><h1>Invoices</h1><h2>Create drafts, issue invoices, track balances and open any invoice directly from the register.</h2></div><Link href="/app/invoices/new" className={styles.newButton}><Plus size={15}/>New invoice</Link></div>
  <section className={styles.metrics}><article className={styles.metric}><span><ReceiptText size={14}/>Outstanding</span><strong>{money(outstanding,currency)}</strong><small>Issued customer balance</small></article><article className={styles.metric}><span><Clock3 size={14}/>Overdue</span><strong>{overdue}</strong><small>{overdue===0?"Nothing needs chasing":"Past due date"}</small></article><article className={styles.metric}><span><Pencil size={14}/>Drafts</span><strong>{drafts.length}</strong><small>Editable · not posted</small></article><article className={styles.metric}><span><CircleCheck size={14}/>Paid</span><strong>{paid}</strong><small>Settled receivables</small></article></section>
  <section className={styles.panel}><div className={styles.panelHead}><div><p>Sales register</p><h2>Invoices & drafts</h2></div><span>{invoices.length} documents</span></div>
   {invoices.length===0?<div className={styles.empty}><span><FileText size={22}/></span><h3>Your first invoice starts as a draft.</h3><p>Edit it freely, then issue it when you want Compta to post revenue, VAT and the receivable.</p><Link href="/app/invoices/new">Create first invoice <ArrowRight size={14}/></Link></div>:<div className={styles.list}>{invoices.map(invoice=>{const isDraft=invoice.status==="draft",isOverdue=!isDraft&&invoice.payment_status!=="paid"&&invoice.due_date<today,balance=isDraft?0:Math.max(0,Number(invoice.total)-(paidByInvoice.get(invoice.id)??0));return <article className={styles.row} key={invoice.id}>
    <div className={styles.invoiceId}><span className={styles.invoiceIcon}><ReceiptText size={16}/></span><div><Link href={`/app/invoices/${invoice.id}`}>{invoice.invoice_number||"Draft invoice"}<ExternalLink size={11}/></Link><small>{isDraft?"Editable draft":"Issued invoice · click to open"}</small></div></div>
    <strong className={styles.customer}>{customerName(invoice.customer_snapshot)}</strong><span className={`${styles.cell} ${styles.issue}`}>{new Date(`${invoice.issue_date}T12:00:00`).toLocaleDateString("en-LU",{day:"2-digit",month:"short",year:"numeric"})}</span><span className={`${styles.cell} ${styles.due}`}>{new Date(`${invoice.due_date}T12:00:00`).toLocaleDateString("en-LU",{day:"2-digit",month:"short"})}</span><span><i className={`${styles.status} ${invoice.payment_status==="paid"?styles.paid:isOverdue?styles.overdue:""}`}>{isDraft?"draft":isOverdue?"overdue":invoice.payment_status}</i></span><strong className={styles.balance}>{isDraft?"—":money(balance,invoice.currency)}</strong>
    <div className={styles.actions}>{isDraft?<Link href={`/app/invoices/${invoice.id}/edit`} className={styles.secondary}><Pencil size={12}/>Edit</Link>:invoice.payment_status!=="paid"?<Link className={styles.secondary} href={`/app/invoices/${invoice.id}#payment`}>Settle</Link>:null}<Link href={`/app/invoices/${invoice.id}`} className={styles.open}>Open <ArrowRight size={12}/></Link></div>
   </article>})}</div>}
  </section>
 </div>;
}
