import { ArrowRight, CircleCheck, Clock3, Eye, ExternalLink, FileText, Pencil, Plus, ReceiptText } from "lucide-react";
import Link from "next/link";
import { redirect } from "next/navigation";
import { fiscalYearBounds, getActiveFiscalYear } from "@/lib/fiscal-year";
import { intlLocale, normalizeLocale, type Locale } from "@/lib/i18n";
import { canBookkeep } from "@/lib/permissions";
import { createClient } from "@/lib/supabase/server";
import { getWorkspace } from "@/lib/workspace";
import styles from "./invoice-list.module.css";

export const dynamic="force-dynamic";
function money(value:number,currency:string,locale:Locale){return new Intl.NumberFormat(intlLocale(locale),{style:"currency",currency,minimumFractionDigits:2}).format(value)}
function customerName(snapshot:unknown,fr=false){if(!snapshot||typeof snapshot!=="object")return fr?"Client":"Customer";const value=(snapshot as Record<string,unknown>).name;return typeof value==="string"&&value?value:(fr?"Client":"Customer")}
export default async function InvoicesPage(){
 const workspace=await getWorkspace();if(!workspace.authenticated)redirect("/sign-in");if(!workspace.company)redirect("/setup");const locale=normalizeLocale(workspace.profile?.locale),fr=locale==="fr",editable=canBookkeep(workspace.role),year=await getActiveFiscalYear(workspace.company.fiscal_year_start_month),bounds=fiscalYearBounds(year,workspace.company.fiscal_year_start_month),supabase=await createClient();
 const[invoiceResult,paymentResult]=await Promise.all([
  supabase.from("sales_invoices").select("id,invoice_number,status,payment_status,issue_date,service_date,due_date,currency,subtotal,vat_total,total,customer_snapshot,issued_at,created_at").eq("company_id",workspace.company.id).neq("status","void").gte("service_date",bounds.start).lte("service_date",bounds.end).order("service_date",{ascending:false}).order("created_at",{ascending:false}),
  supabase.from("invoice_payments").select("invoice_id,amount,paid_on").eq("company_id",workspace.company.id).lte("paid_on",bounds.end)
 ]);if(invoiceResult.error)throw new Error(`${fr?"Impossible de charger les factures":"Could not load invoices"}: ${invoiceResult.error.message}`);if(paymentResult.error)throw new Error(`${fr?"Impossible de charger les paiements":"Could not load payments"}: ${paymentResult.error.message}`);
 const invoices=invoiceResult.data??[],paidByInvoice=new Map<string,number>();for(const payment of paymentResult.data??[])paidByInvoice.set(payment.invoice_id,(paidByInvoice.get(payment.invoice_id)??0)+Number(payment.amount));const issued=invoices.filter(i=>i.status==="issued"),drafts=invoices.filter(i=>i.status==="draft"),outstanding=issued.reduce((sum,invoice)=>sum+Math.max(0,Number(invoice.total)-(paidByInvoice.get(invoice.id)??0)),0),overdue=issued.filter(invoice=>Math.max(0,Number(invoice.total)-(paidByInvoice.get(invoice.id)??0))>.005&&invoice.due_date<=bounds.end).length,paid=issued.filter(invoice=>Math.max(0,Number(invoice.total)-(paidByInvoice.get(invoice.id)??0))<=.005).length,currency=workspace.company.base_currency||"EUR";
 const date=(value:string,withYear=true)=>new Date(`${value}T12:00:00`).toLocaleDateString(intlLocale(locale),withYear?{day:"2-digit",month:"short",year:"numeric"}:{day:"2-digit",month:"short"});
 return <div className={styles.page}>
  <div className={styles.intro}><div><p>{fr?`Ventes et créances · ${year}`:`Sales & receivables · ${year}`}</p><h1>{fr?"Factures":"Invoices"}</h1><h2>{editable?(fr?"Créez des brouillons, émettez des factures et suivez les créances de l’exercice sélectionné.":"Create drafts, issue invoices and inspect receivables in the selected financial year."):(fr?"Accès en lecture seule aux factures, brouillons et créances de l’exercice sélectionné.":"Read-only access to invoices, drafts and receivables in the selected financial year.")}</h2></div>{editable?<Link href="/app/invoices/new" className={styles.newButton}><Plus size={15}/>{fr?"Nouvelle facture":"New invoice"}</Link>:<span className={styles.newButton} style={{pointerEvents:"none",opacity:.72}}><Eye size={15}/>{fr?"Lecteur · lecture seule":"Viewer · read only"}</span>}</div>
  <section className={styles.metrics}><article className={styles.metric}><span><ReceiptText size={14}/>{fr?"Encours à la clôture":"Outstanding at period end"}</span><strong>{money(outstanding,currency,locale)}</strong><small>{fr?`Paiements après le ${date(bounds.end)} exclus`:`Payments after ${bounds.end} excluded`}</small></article><article className={styles.metric}><span><Clock3 size={14}/>{fr?"En retard à la clôture":"Overdue at period end"}</span><strong>{overdue}</strong><small>{overdue===0?(fr?"Aucun retard":"Nothing past due"):(fr?"Non réglées à la clôture sélectionnée":"Unsettled by the selected year-end")}</small></article><article className={styles.metric}><span><Pencil size={14}/>{fr?"Brouillons":"Drafts"}</span><strong>{drafts.length}</strong><small>{editable?(fr?"Modifiables · non comptabilisés":"Editable · not posted"):(fr?"Visibles · lecture seule":"Visible · read only")}</small></article><article className={styles.metric}><span><CircleCheck size={14}/>{fr?"Réglées à la clôture":"Settled by year-end"}</span><strong>{paid}</strong><small>{fr?`Paiements datés jusqu’au ${date(bounds.end)}`:`Payments dated through ${bounds.end}`}</small></article></section>
  <section className={styles.panel}><div className={styles.panelHead}><div><p>{fr?`Registre des ventes · ${year}`:`Sales register · ${year}`}</p><h2>{fr?"Factures et brouillons":"Invoices & drafts"}</h2></div><span>{invoices.length} {fr?`document${invoices.length===1?"":"s"}`:`document${invoices.length===1?"":"s"}`}</span></div>
   {invoices.length===0?<div className={styles.empty}><span><FileText size={22}/></span><h3>{fr?`Aucune facture pour l’exercice ${year}.`:`No invoices in financial year ${year}.`}</h3><p>{editable?(fr?`Créez un brouillon historique avec une date de prestation en ${year}, puis émettez-le lorsque vous souhaitez que Compta comptabilise les produits, la TVA et la créance.`:`Create a historical draft with a ${year} service date, then issue it when you want Compta to post revenue, VAT and the receivable.`):(fr?"Aucune facture n’est disponible pour cet exercice.":"No invoices are available in this financial year.")}</p>{editable?<Link href="/app/invoices/new">{fr?"Créer une facture":"Create invoice"} <ArrowRight size={14}/></Link>:null}</div>:<div className={styles.list}>{invoices.map(invoice=>{const isDraft=invoice.status==="draft",balance=isDraft?0:Math.max(0,Number(invoice.total)-(paidByInvoice.get(invoice.id)??0)),settledByYearEnd=!isDraft&&balance<=.005,isOverdue=!isDraft&&!settledByYearEnd&&invoice.due_date<=bounds.end,status=fr?(isDraft?"brouillon":settledByYearEnd?"payée":isOverdue?"en retard":"ouverte"):(isDraft?"draft":settledByYearEnd?"paid":isOverdue?"overdue":"open");return <article className={styles.row} key={invoice.id}>
    <div className={styles.invoiceId}><span className={styles.invoiceIcon}><ReceiptText size={16}/></span><div><Link href={`/app/invoices/${invoice.id}`}>{invoice.invoice_number||(fr?"Facture brouillon":"Draft invoice")}<ExternalLink size={11}/></Link><small>{isDraft?(editable?(fr?"Brouillon modifiable":"Editable draft"):(fr?"Brouillon · lecture seule":"Draft · read only")):(fr?`Prestation ${date(invoice.service_date)} · cliquez pour ouvrir`:`Service ${invoice.service_date} · click to open`)}</small></div></div>
    <strong className={styles.customer}>{customerName(invoice.customer_snapshot,fr)}</strong><span className={`${styles.cell} ${styles.issue}`}>{date(invoice.issue_date)}</span><span className={`${styles.cell} ${styles.due}`}>{date(invoice.due_date,false)}</span><span><i className={`${styles.status} ${settledByYearEnd?styles.paid:isOverdue?styles.overdue:""}`}>{status}</i></span><strong className={styles.balance}>{isDraft?"—":money(balance,invoice.currency,locale)}</strong>
    <div className={styles.actions}>{editable&&isDraft?<Link href={`/app/invoices/${invoice.id}/edit`} className={styles.secondary}><Pencil size={12}/>{fr?"Modifier":"Edit"}</Link>:editable&&!settledByYearEnd?<Link className={styles.secondary} href={`/app/invoices/${invoice.id}#payment`}>{fr?"Régler":"Settle"}</Link>:null}<Link href={`/app/invoices/${invoice.id}`} className={styles.open}>{editable?(fr?"Ouvrir":"Open"):(fr?"Voir":"View")} <ArrowRight size={12}/></Link></div>
   </article>})}</div>}
  </section>
 </div>;
}
