import { AlertTriangle, BadgeCheck, FileCheck2, FileCode2, FileText, ShieldCheck } from "lucide-react";
import { redirect } from "next/navigation";
import styles from "@/components/ecdf.module.css";
import { createClient } from "@/lib/supabase/server";
import { getWorkspace } from "@/lib/workspace";
export const dynamic="force-dynamic";
export default async function EcdfPage(){const w=await getWorkspace();if(!w.authenticated)redirect("/sign-in");if(!w.company)redirect("/setup");const s=await createClient(),year=new Date().getFullYear();const{data:filing,error}=await s.from("filings").select("id,period_label,status,schema_version,rules_version,ledger_snapshot,snapshot_at,ledger_checksum,export_status").eq("company_id",w.company.id).eq("filing_type","annual_accounts").eq("period_label",String(year)).order("created_at",{ascending:false}).limit(1).maybeSingle();if(error)throw new Error(`Could not load annual-account preparation: ${error.message}`);
 const snap=filing?.ledger_snapshot&&typeof filing.ledger_snapshot==="object"?filing.ledger_snapshot as Record<string,unknown>:null,tb=Array.isArray(snap?.trial_balance)?snap?.trial_balance:[],pl=snap?.profit_and_loss&&typeof snap.profit_and_loss==="object"?snap.profit_and_loss as Record<string,unknown>:null;
 return <div className={styles.page}><div className={styles.intro}><div><p>eCDF · annual accounts · {year}</p><h1>Prepare once. Export only when the schema is trusted.</h1><span>The annual-account package is built from a frozen closing snapshot, not from a moving ledger.</span></div><div className={filing?styles.status:styles.statusWarn}>{filing?<BadgeCheck/>:<AlertTriangle/>}{filing?"Closing snapshot found":"Create closing snapshot first"}</div></div>
 {!filing?<article className={styles.empty}><ShieldCheck/><h2>No frozen annual-account snapshot yet.</h2><p>Finish the Year-end checklist and create a closing snapshot. Compta will then freeze the trial balance used by this workspace.</p></article>:<><section className={styles.hero}><article><span>Snapshot</span><strong>{filing.snapshot_at?new Date(filing.snapshot_at).toLocaleString("en-LU",{dateStyle:"medium",timeStyle:"short"}):"—"}</strong><small>Rules {filing.rules_version||"—"}</small></article><article><span>Frozen PCN accounts</span><strong>{tb.length}</strong><small>Trial-balance lines</small></article><article><span>Current-year result</span><strong>{typeof pl?.result==="number"?new Intl.NumberFormat("en-LU",{style:"currency",currency:w.company.base_currency||"EUR"}).format(pl.result):"—"}</strong><small>Frozen P&L result</small></article><article><span>Ledger fingerprint</span><strong className={styles.hash}>{filing.ledger_checksum?.slice(0,12)||"—"}</strong><small>Detects snapshot drift</small></article></section>
 <section className={styles.grid}><article className={styles.card}><div className={styles.head}><div><p>Annual-account package</p><h2>Financial data readiness</h2></div><FileCheck2/></div><div className={styles.row}><span>Trial balance / PCN balances</span><strong>Frozen</strong></div><div className={styles.row}><span>Profit & loss source data</span><strong>Ready</strong></div><div className={styles.row}><span>Balance-sheet source data</span><strong>Ready</strong></div><div className={styles.row}><span>Annexe / notes questionnaire</span><strong className={styles.pending}>Next layer</strong></div><div className={styles.row}><span>Approval / AGM resolution</span><strong className={styles.pending}>Not generated</strong></div></article>
 <article className={styles.card}><div className={styles.head}><div><p>XML interface</p><h2>CTIE/eCDF transport</h2></div><FileCode2/></div><div className={styles.row}><span>Current CTIE XSD/schema package</span><strong className={styles.pending}>Required</strong></div><div className={styles.row}><span>Compta interface identifier</span><strong className={styles.pending}>Required</strong></div><div className={styles.row}><span>CTIE interface validation</span><strong className={styles.pending}>Required</strong></div><div className={styles.row}><span>XML generation</span><strong>Disabled safely</strong></div><div className={styles.notice}><AlertTriangle/><p>eCDF only accepts XML conforming to an active CTIE structure from a validated interface. Compta therefore will not label an internally generated file “eCDF compatible” before the official developer interface has been validated.</p></div></article>
 <article className={styles.card}><div className={styles.head}><div><p>Snapshot provenance</p><h2>What this filing is based on</h2></div><FileText/></div><div className={styles.meta}><span>Filing ID</span><code>{filing.id}</code><span>Status</span><code>{filing.status}</code><span>Export state</span><code>{filing.export_status}</code><span>Schema</span><code>{filing.schema_version||"Not installed"}</code></div></article></section></>}
 </div>}
