"use client";

import { Check, FileSpreadsheet, Landmark, LoaderCircle, Plus, UploadCloud, X } from "lucide-react";
import { useActionState, useEffect, useMemo, useRef, useState } from "react";
import { importBankRows, type BankImportState } from "@/app/app/banking/actions";
import { FloatingActionPortal } from "@/components/floating-action-portal";
import { useI18n } from "@/components/locale-context";
import styles from "./banking.module.css";

type Row={booking_date:string;value_date?:string|null;amount:number;currency?:string;counterparty_name?:string|null;counterparty_iban?:string|null;counterparty_address?:string|null;reference?:string|null;communication?:string|null;operation_code?:string|null;external_id?:string|null;raw_details?:string|null};
type Result={rows:Row[];message:string;headers:string[];detectedBank?:string;detectedIban?:string};
const initial:BankImportState={status:"idle",message:""};
const aliases={date:["bookingdate","booking_date","date","datum","buchungstag","dateoperation","datedoperation","datecomptable"],valueDate:["valuedate","value_date","valutadatum","datevaleur"],amount:["amount","montant","montantoperation","montantdeloperation","betrag","value","transactionamount"],debit:["debit","débit","debitamount","montantdebit"],credit:["credit","crédit","creditamount","montantcredit"],currency:["currency","devise","wahrung","währung"],counterparty:["counterparty","counterpartyname","beneficiary","beneficiaire","bénéficiaire","name","nom","partner","nomdelacontrepartie"],iban:["counterpartyiban","ibanbeneficiary","ibanbeneficiaire","iban","comptedelacontrepartie"],address:["counterpartyaddress","address","adresse","adressedelacontrepartie"],communication:["communication","message","remittanceinformation","purpose","memo","details","libelle","libellé"],operationCode:["description","transactiontype","transactioncode","operationcode","operation_code","bookingcode"],reference:["reference","paymentreference","referencepaiement"],external:["transactionid","externalid","external_id","id","referenceid","referencedoperation","referencedeloperation"]};
function norm(v:string){return v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]/g,"")}function findIndex(h:string[],n:string[]){const a=h.map(norm),b=n.map(norm);return a.findIndex(x=>b.includes(x))}function delimiter(l:string){return[";",",","\t"].sort((a,b)=>l.split(b).length-l.split(a).length)[0]??","}function parseLine(l:string,s:string){const o:string[]=[];let c="",q=false;for(let i=0;i<l.length;i++){const x=l[i];if(x==='"'){if(q&&l[i+1]==='"'){c+='"';i++}else q=!q}else if(x===s&&!q){o.push(c.trim());c=""}else c+=x}o.push(c.trim());return o}function num(r:string){let v=(r||"").trim().replace(/\s/g,"").replace(/[€$£]/g,"");if(!v)return 0;const c=v.lastIndexOf(","),d=v.lastIndexOf(".");if(c>d)v=v.replace(/\./g,"").replace(",",".");else if(d>c)v=v.replace(/,/g,"");else v=v.replace(",",".");return Number(v.replace(/[^0-9.-]/g,""))}function date(r:string){const v=(r||"").trim();if(/^\d{4}-\d{2}-\d{2}$/.test(v))return v;const m=v.match(/^(\d{1,2})[./-](\d{1,2})[./-](\d{4})$/);return m?`${m[3]}-${m[2].padStart(2,"0")}-${m[1].padStart(2,"0")}`:null}function cell(c:string[],i:number){return i>=0?(c[i]||"").trim():""}function score(r:string[]){return(findIndex(r,aliases.date)>=0?1:0)+(findIndex(r,aliases.amount)>=0||findIndex(r,aliases.debit)>=0||findIndex(r,aliases.credit)>=0?1:0)}function repairPost(c:string[],h:string[]){if(c.length<=h.length)return c;const n=h.map(norm),i=n.indexOf("communication"),j=n.findIndex(x=>["referencedoperation","referencedeloperation"].includes(x));if(i<0||j!==h.length-1)return c.slice(0,h.length);const x=c.length-h.length;return[...c.slice(0,i),c.slice(i,i+x+1).join(", "),c[c.length-1]]}function extractId(m:string){return m.match(/(?:End-to-end Identification|Payment initiation reference):\s*([^\s;]+)/i)?.[1]?.trim()||null}function bilParty(n:string,m:string){const b=m.match(/Beneficiary:\s*(.*?)\s+Beneficiary account:/i)?.[1]?.trim(),iban=m.match(/Beneficiary account:\s*([A-Z]{2}\d{2}[A-Z0-9 ]{10,30})\s+At:/i)?.[1]?.replace(/\s/g,"").trim(),o=m.match(/By order of:\s*(.*?)\s+Paying bank:/i)?.[1]?.trim();if(b||o)return{name:b||o||null,iban:iban||null};if(/card payment/i.test(n))return{name:m.replace(/\s+\d{2}\/\d{2}\/\d{4}\s+\d{2}:\d{2}\s*$/i,"").trim()||"Card payment",iban:null};if(/loan repayment/i.test(n))return{name:m.split(/\s+To the loan:/i)[0]?.trim()||"Loan repayment",iban:null};return{name:n||null,iban:null}}
function normalize(matrix:string[][],preamble=""):Result{const hi=matrix.findIndex(r=>score(r)>=2);if(hi<0)return{rows:[],message:"I couldn't detect a transaction table in this statement.",headers:[]};const h=matrix[hi].map(v=>String(v??"").trim()),data=matrix.slice(hi+1),nh=h.map(norm),isBil=nh.includes("valuedate")&&nh.includes("name")&&nh.includes("message")&&nh.includes("amount"),isPost=nh.includes("datecomptable")&&nh.includes("referencedoperation");if(isBil){const di=findIndex(h,["date"]),vi=findIndex(h,["value date"]),ni=findIndex(h,["name"]),mi=findIndex(h,["message"]),ai=findIndex(h,["amount"]),ci=findIndex(h,aliases.currency),rows:Row[]=[];for(const c of data){const d=date(cell(c,di)),a=num(cell(c,ai));if(!d||!Number.isFinite(a)||a===0)continue;const tn=cell(c,ni),m=cell(c,mi),p=bilParty(tn,m);rows.push({booking_date:d,value_date:date(cell(c,vi)),amount:a,currency:cell(c,ci).toUpperCase()||undefined,counterparty_name:p.name,counterparty_iban:p.iban,reference:m||tn||null,communication:m||null,operation_code:`BIL:${tn}`.slice(0,120),external_id:extractId(m),raw_details:m||null})}const ib=(preamble.match(/\bLU\d{18}\b/i)?.[0]||"").toUpperCase();return{rows,headers:h,detectedBank:"BIL",detectedIban:ib||undefined,message:`${rows.length} BIL movement${rows.length===1?"":"s"} detected.`}}const di=findIndex(h,aliases.date),vi=findIndex(h,aliases.valueDate),ai=findIndex(h,aliases.amount),db=findIndex(h,aliases.debit),cr=findIndex(h,aliases.credit),ci=findIndex(h,aliases.currency),pi=findIndex(h,aliases.counterparty),ii=findIndex(h,aliases.iban),adi=findIndex(h,aliases.address),comi=findIndex(h,aliases.communication),opi=findIndex(h,aliases.operationCode),ri=findIndex(h,aliases.reference),ei=findIndex(h,aliases.external);if(di<0||ai<0&&db<0&&cr<0)return{rows:[],message:"The statement needs a recognizable date and amount column.",headers:h};const rows:Row[]=[];for(const original of data){const c=isPost?repairPost(original,h):original,d=date(cell(c,di));if(!d)continue;let a=ai>=0?num(cell(c,ai)):0;if(ai<0)a=(cr>=0?Math.abs(num(cell(c,cr))):0)-(db>=0?Math.abs(num(cell(c,db))):0);if(!Number.isFinite(a)||a===0)continue;const com=cell(c,comi),ref=cell(c,ri),op=cell(c,opi),ad=cell(c,adi);rows.push({booking_date:d,value_date:date(cell(c,vi)),amount:a,currency:cell(c,ci).toUpperCase()||undefined,counterparty_name:cell(c,pi)||null,counterparty_iban:cell(c,ii)||null,counterparty_address:ad||null,reference:ref||com||null,communication:com||null,operation_code:op||null,external_id:cell(c,ei)||null,raw_details:[op,com,ad].filter(Boolean).join(" · ")||null})}return{rows,headers:h,detectedBank:isPost?"POST Luxembourg":undefined,message:`${rows.length} valid transaction${rows.length===1?"":"s"} detected${isPost?" from POST Luxembourg":""}.`}}
function csvMatrix(text:string){const lines=text.replace(/^\uFEFF/,"").split(/\r?\n/).filter(l=>l.trim()),i=lines.findIndex(l=>score(parseLine(l,delimiter(l)))>=2);if(i<0)return{matrix:[] as string[][],preamble:lines.slice(0,8).join(" ")};const s=delimiter(lines[i]);return{matrix:lines.slice(i).map(l=>parseLine(l,s)),preamble:lines.slice(0,i).join(" ")}}async function parseFile(file:File):Promise<Result>{if(/\.xlsx$/i.test(file.name)){const XLSX=await import("xlsx");const w=XLSX.read(await file.arrayBuffer(),{type:"array",cellDates:false}),s=w.Sheets[w.SheetNames[0]],m=XLSX.utils.sheet_to_json<(string|number|null)[]>(s,{header:1,raw:false,defval:""}).map(r=>r.map(v=>String(v??"")));return normalize(m)}const{matrix,preamble}=csvMatrix(await file.text());return normalize(matrix,preamble)}

export function BankImporter({defaultCurrency,initialOpen=false}:{defaultCurrency:string;initialOpen?:boolean}){
 const{locale}=useI18n(),fr=locale==="fr",l=(en:string,french:string)=>fr?french:en;
 const[state,action,pending]=useActionState(importBankRows,initial),input=useRef<HTMLInputElement>(null),[fileName,setFileName]=useState(""),[rows,setRows]=useState<Row[]>([]),[msg,setMsg]=useState<string|null>(null),[open,setOpen]=useState(initialOpen),[bank,setBank]=useState<string|null>(null),[accountName,setAccountName]=useState(l("Main bank account","Compte bancaire principal")),[iban,setIban]=useState(""),[pdfReady,setPdfReady]=useState(false);const preview=useMemo(()=>rows.slice(0,3),[rows]);
 useEffect(()=>{if(state.status==="success")setOpen(false)},[state.status]);
 useEffect(()=>{if(!open)return;const previous=document.body.style.overflow;document.body.style.overflow="hidden";const onKey=(event:KeyboardEvent)=>{if(event.key==="Escape"&&!pending)setOpen(false)};window.addEventListener("keydown",onKey);return()=>{document.body.style.overflow=previous;window.removeEventListener("keydown",onKey)}},[open,pending]);
 async function choose(file:File|null){if(!file)return;setFileName(file.name);setBank(null);setPdfReady(false);if(file.size>15*1024*1024){setRows([]);return setMsg(l("Keep statement files under 15 MB per import.","Limitez chaque relevé à 15 Mo."))}if(file.type==="application/pdf"||/\.pdf$/i.test(file.name)){setRows([]);setPdfReady(true);setBank("PDF");setMsg(null);return}try{const r=await parseFile(file);setRows(r.rows);setMsg(r.rows.length?r.message:l("No bank movements were found.","Aucun mouvement bancaire n’a été trouvé."));setBank(r.detectedBank||null);if(r.detectedBank&&["Main bank account","Compte bancaire principal"].includes(accountName))setAccountName(`${r.detectedBank}`);if(r.detectedIban)setIban(r.detectedIban)}catch{setRows([]);setMsg(l("Zuelen couldn't read this statement. Try CSV, XLSX or the original PDF statement.","Zuelen n’a pas pu lire ce relevé. Essayez le fichier CSV, XLSX ou le PDF original."))}}
 const fileReady=pdfReady||rows.length>0;
 const format=bank||(!fileName?"CSV / XLSX / PDF":pdfReady?"PDF":/\.xlsx$/i.test(fileName)?"XLSX":"CSV");
 const steps=[{label:l("Account","Compte"),ready:Boolean(accountName.trim()||iban.trim())},{label:l("Statement","Relevé"),ready:Boolean(fileName)},{label:l("Import","Import"),ready:false}];
 return <>
  <FloatingActionPortal><button className={styles.fab} type="button" onClick={()=>setOpen(true)}><Plus size={17}/>{l("Import statement","Importer un relevé")}</button></FloatingActionPortal>
  {open?<div className={styles.drawerOverlay} role="presentation" onMouseDown={e=>{if(e.currentTarget===e.target&&!pending)setOpen(false)}}><div className={styles.drawerShell}>
   <button autoFocus className={styles.drawerClose} type="button" onClick={()=>setOpen(false)} aria-label={l("Close bank import","Fermer l’import bancaire")} disabled={pending}><X size={18}/></button>
   <aside className={`${styles.importCard} ${styles.drawerCard}`} role="dialog" aria-modal="true" aria-labelledby="bank-import-title">
    <div className={styles.importHead}><div><p>{l("Banking","Banque")}</p><h2 id="bank-import-title">{l("Import bank statement","Importer un relevé bancaire")}</h2></div><span><FileSpreadsheet size={14}/>{format}</span></div>
    <p className={styles.lead}>{l("Add your statement and Zuelen will import the bank movements. The original file is kept in Documents.","Ajoutez votre relevé et Zuelen importera les mouvements bancaires. Le fichier original sera conservé dans Documents.")}</p>
    <div className={styles.importSteps}>{steps.map((step,index)=><div className={`${styles.importStep} ${step.ready?styles.importStepReady:""} ${pending&&index===2?styles.importStepActive:""}`} key={step.label}><span>{step.ready?<Check size={13}/>:index+1}</span><strong>{step.label}</strong></div>)}</div>
    <form action={action} className={styles.importForm}>
     <div className={styles.accountGrid}><label><span>{l("Account name","Nom du compte")}</span><input name="account_name" value={accountName} onChange={e=>setAccountName(e.target.value)} required disabled={pending}/></label><label><span>IBAN <em>{l("optional","facultatif")}</em></span><input name="iban" value={iban} onChange={e=>setIban(e.target.value)} placeholder="LU00 0000 0000 0000 0000" disabled={pending}/></label><label><span>{l("Currency","Devise")}</span><input name="currency" defaultValue={defaultCurrency||"EUR"} maxLength={3} disabled={pending}/></label></div>
     <button type="button" className={`${styles.dropzone} ${fileName?styles.dropzoneReady:""}`} onClick={()=>input.current?.click()} disabled={pending}><input ref={input} hidden name="statement_file" type="file" accept=".csv,.xlsx,.pdf,text/csv,application/pdf,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={e=>choose(e.target.files?.[0]??null)}/><UploadCloud size={22}/><strong>{fileName||l("Choose a bank statement","Choisir un relevé bancaire")}</strong><small>{fileName?(pdfReady?l("PDF ready to import","PDF prêt à importer"):rows.length?l(`${rows.length} movements ready`,`${rows.length} mouvements prêts`):msg||l("Reading file…","Lecture du fichier…")):l("CSV, XLSX or PDF · max 15 MB","CSV, XLSX ou PDF · 15 Mo max")}</small></button>
     {pending?<div className={styles.importProgress} role="status" aria-live="polite"><LoaderCircle className={styles.spin} size={18}/><div><strong>{pdfReady?l("Reading statement and importing movements…","Lecture du relevé et import des mouvements…"):l("Importing movements…","Import des mouvements…")}</strong><small>{pdfReady?l("PDF files can take a little longer than structured exports.","Les PDF peuvent prendre un peu plus de temps que les exports structurés."):l("This usually completes in a few seconds.","Cette étape se termine généralement en quelques secondes.")}</small></div></div>:preview.length>0?<div className={styles.preview}><div className={styles.previewHead}><span>{l("Preview","Aperçu")}{bank?` · ${bank}`:""}</span><strong>{rows.length} {l("movements","mouvements")}</strong></div>{preview.map((r,i)=><div className={styles.previewRow} key={`${r.booking_date}-${i}`}><span>{r.booking_date}</span><span>{r.counterparty_name||r.communication||r.operation_code||r.reference||l("Bank movement","Mouvement bancaire")}</span><strong className={r.amount>=0?styles.moneyIn:styles.moneyOut}>{r.amount>=0?"+":"−"}{Math.abs(r.amount).toFixed(2)} {r.currency||defaultCurrency}</strong></div>)}</div>:null}
     <input type="hidden" name="file_name" value={fileName}/><input type="hidden" name="detected_bank" value={bank??""}/><input type="hidden" name="rows_json" value={JSON.stringify(rows)}/>
     {!pending&&(state.status==="error"||(!fileReady&&msg))?<div className={`${styles.message} ${styles.error}`}>{state.status==="error"?state.message:msg}</div>:null}
     <button className={styles.importButton} type="submit" disabled={pending||!fileReady}>{pending?<LoaderCircle className={styles.spin} size={15}/>:<Landmark size={15}/>} {pending?l("Importing…","Import en cours…"):l("Import","Importer")}</button>
    </form>
   </aside>
  </div></div>:null}
 </>;
}
