"use client";

import { ArrowUp, Eye, FolderClock, LoaderCircle, MessageSquarePlus, Sparkles } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useActionState, useEffect, useRef, useState } from "react";
import { askCopilot, type CopilotState } from "@/app/app/copilot/actions";
import { useI18n } from "@/components/locale-context";
import { useRolePermissions } from "@/components/role-context";
import styles from "./copilot.module.css";

const initial:CopilotState={status:"idle",message:""};
type Conversation={id:string;title:string;created_at:string;updated_at:string};type Message={id:string;role:string;content:string;created_at:string};
export function CopilotPanel({initialQuestion="",conversations,activeConversationId,messages}:{initialQuestion?:string;conversations:Conversation[];activeConversationId:string|null;messages:Message[]}){
 const{canBookkeep}=useRolePermissions(),{locale,intlLocale}=useI18n(),fr=locale==="fr",router=useRouter(),[state,action,pending]=useActionState(askCopilot,initial),[question,setQuestion]=useState(initialQuestion),formRef=useRef<HTMLFormElement>(null),submittedInitial=useRef(false);
 const prompts=fr?["Combien de TVA dois-je payer ?","Quelle trésorerie puis-je utiliser sans risque ?","Qu’est-ce qui bloque la clôture annuelle ?","Expliquez-moi mon compte courant d’associé"]:["How much VAT do I owe?","How much cash can I safely use?","What is blocking year-end?","Explain my shareholder account"];
 useEffect(()=>{if(canBookkeep&&!submittedInitial.current&&initialQuestion.trim().length>=3){submittedInitial.current=true;const timer=window.setTimeout(()=>formRef.current?.requestSubmit(),80);return()=>window.clearTimeout(timer)}},[initialQuestion,canBookkeep]);useEffect(()=>{if(state.status==="success"&&state.conversationId){setQuestion("");const href=`/app/copilot?conversation=${state.conversationId}`;if(activeConversationId!==state.conversationId)router.replace(href);else router.refresh()}},[state.status,state.conversationId,activeConversationId,router]);
 return <div className={styles.shell}><aside className={styles.history}><div className={styles.historyHead}><div><FolderClock size={15}/><strong>{fr?"Conversations":"Conversations"}</strong></div>{canBookkeep?<Link href="/app/copilot" aria-label={fr?"Nouvelle conversation Copilot":"New Copilot conversation"}><MessageSquarePlus size={15}/></Link>:null}</div>{canBookkeep?<Link href="/app/copilot" className={styles.newChat}><Sparkles size={14}/>{fr?"Nouvelle conversation":"New conversation"}</Link>:null}<div className={styles.conversationList}>{conversations.length?conversations.map(conversation=><Link href={`/app/copilot?conversation=${conversation.id}`} key={conversation.id} className={activeConversationId===conversation.id?styles.conversationActive:""}><strong>{conversation.title}</strong><small>{new Date(conversation.updated_at).toLocaleDateString(intlLocale,{day:"2-digit",month:"short",timeZone:"Europe/Luxembourg"})}</small></Link>):<p>{fr?"Aucune conversation pour le moment.":"No conversations yet."}</p>}</div></aside>
 <main className={styles.chat}><header className={styles.chatHead}><span className={styles.logo}><Sparkles size={17}/></span><div><p>Zuelen Copilot</p><h1>{activeConversationId?conversations.find(c=>c.id===activeConversationId)?.title||(fr?"Conversation":"Conversation"):(fr?"Votre copilote financier":"Your financial copilot")}</h1><span>{canBookkeep?(fr?"Interrogez votre comptabilité en langage courant. Zuelen distingue les faits comptabilisés, les justificatifs et les estimations.":"Ask your books in everyday language. Zuelen separates posted facts, evidence and estimates."):(fr?"L’accès Lecteur est en lecture seule. Les conversations Copilot sont désactivées pour ce rôle.":"Viewer access is read-only. Copilot conversations are disabled for this role.")}</span></div></header><div className={styles.messages}>{messages.length?messages.map(message=><article className={message.role==="user"?styles.userMessage:styles.assistantMessage} key={message.id}><div className={styles.messageMeta}><span>{message.role==="user"?(fr?"Vous":"You"):"Zuelen"}</span><small>{new Date(message.created_at).toLocaleTimeString(intlLocale,{hour:"2-digit",minute:"2-digit",timeZone:"Europe/Luxembourg"})}</small></div><div className={styles.messageBody}>{message.content}</div></article>):<div className={styles.emptyState}><div className={styles.illustration} aria-hidden="true"><div className={styles.gridDots}/><span className={styles.illTileOne}><i/>€<b>TVA</b></span><span className={styles.illOrb}>{canBookkeep?<Sparkles size={24}/>:<Eye size={24}/>}</span><span className={styles.illTileTwo}><i/><i/><i/></span><span className={styles.illTileThree}>J<span>0058</span></span></div><h2>{canBookkeep?(fr?"Posez la question métier. Oubliez le jargon comptable.":"Ask the business question. Skip the accounting jargon."):(fr?"Accès en lecture seule":"Read-only access")}</h2><p>{canBookkeep?(fr?"Copilot peut expliquer la TVA, la trésorerie, les factures, la réserve fiscale, les blocages de conformité et la comptabilité enregistrée à partir des données déjà présentes dans Zuelen.":"Copilot can explain VAT, cash, invoices, tax reserve, compliance blockers and posted accounting using the records already inside Zuelen."):(fr?"Un Lecteur peut consulter les données de l’entreprise dans Zuelen, mais ne peut pas créer de conversations Copilot persistantes.":"A Viewer can inspect company records across Zuelen but cannot create persistent Copilot conversations.")}</p>{canBookkeep?<div className={styles.prompts}>{prompts.map(prompt=><button key={prompt} type="button" onClick={()=>setQuestion(prompt)}>{prompt}</button>)}</div>:null}</div>}</div>
 {canBookkeep?<div className={styles.composerWrap}><form ref={formRef} action={action} className={styles.ask}><input type="hidden" name="conversation_id" value={activeConversationId??""}/><textarea name="question" value={question} onChange={event=>setQuestion(event.target.value)} placeholder={fr?"Posez une question à Zuelen sur votre entreprise…":"Ask Zuelen about your company…"} rows={2}/><button type="submit" disabled={pending||question.trim().length<3} aria-label={fr?"Interroger Zuelen":"Ask Zuelen"}>{pending?<LoaderCircle className={styles.spin}/>:<ArrowUp/>}</button></form>{state.status==="error"?<p className={styles.error}>{state.message}</p>:null}<footer>{fr?"Lecture seule · Copilot ne peut ni comptabiliser des écritures ni soumettre des déclarations.":"Read-only · Copilot cannot post entries or submit filings."}</footer></div>:null}</main></div>;
}
