"use client";

import { ArrowUp, Eye, FolderClock, LoaderCircle, MessageSquarePlus, Sparkles } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useActionState, useEffect, useRef, useState } from "react";
import { askCopilot, type CopilotState } from "@/app/app/copilot/actions";
import { useRolePermissions } from "@/components/role-context";
import styles from "./copilot.module.css";

const initial:CopilotState={status:"idle",message:""};
const prompts=["How much VAT do I owe?","How much cash can I safely use?","What is blocking year-end?","Explain my shareholder account"];
type Conversation={id:string;title:string;created_at:string;updated_at:string};type Message={id:string;role:string;content:string;created_at:string};
export function CopilotPanel({initialQuestion="",conversations,activeConversationId,messages}:{initialQuestion?:string;conversations:Conversation[];activeConversationId:string|null;messages:Message[]}){
 const{canBookkeep}=useRolePermissions(),router=useRouter(),[state,action,pending]=useActionState(askCopilot,initial),[question,setQuestion]=useState(initialQuestion),formRef=useRef<HTMLFormElement>(null),submittedInitial=useRef(false);
 useEffect(()=>{if(canBookkeep&&!submittedInitial.current&&initialQuestion.trim().length>=3){submittedInitial.current=true;const timer=window.setTimeout(()=>formRef.current?.requestSubmit(),80);return()=>window.clearTimeout(timer)}},[initialQuestion,canBookkeep]);useEffect(()=>{if(state.status==="success"&&state.conversationId){setQuestion("");const href=`/app/copilot?conversation=${state.conversationId}`;if(activeConversationId!==state.conversationId)router.replace(href);else router.refresh()}},[state.status,state.conversationId,activeConversationId,router]);
 return <div className={styles.shell}><aside className={styles.history}><div className={styles.historyHead}><div><FolderClock size={15}/><strong>Conversations</strong></div>{canBookkeep?<Link href="/app/copilot" aria-label="New Copilot conversation"><MessageSquarePlus size={15}/></Link>:null}</div>{canBookkeep?<Link href="/app/copilot" className={styles.newChat}><Sparkles size={14}/>New conversation</Link>:null}<div className={styles.conversationList}>{conversations.length?conversations.map(conversation=><Link href={`/app/copilot?conversation=${conversation.id}`} key={conversation.id} className={activeConversationId===conversation.id?styles.conversationActive:""}><strong>{conversation.title}</strong><small>{new Date(conversation.updated_at).toLocaleDateString("en-LU",{day:"2-digit",month:"short"})}</small></Link>):<p>No conversations yet.</p>}</div></aside>
 <main className={styles.chat}><header className={styles.chatHead}><span className={styles.logo}><Sparkles size={17}/></span><div><p>Compta Copilot</p><h1>{activeConversationId?conversations.find(c=>c.id===activeConversationId)?.title||"Conversation":"Your financial copilot"}</h1><span>{canBookkeep?"Ask your books in everyday language. Compta separates posted facts, evidence and estimates.":"Viewer access is read-only. Copilot conversations are disabled for this role."}</span></div></header><div className={styles.messages}>{messages.length?messages.map(message=><article className={message.role==="user"?styles.userMessage:styles.assistantMessage} key={message.id}><div className={styles.messageMeta}><span>{message.role==="user"?"You":"Compta"}</span><small>{new Date(message.created_at).toLocaleTimeString("en-LU",{hour:"2-digit",minute:"2-digit"})}</small></div><div className={styles.messageBody}>{message.content}</div></article>):<div className={styles.emptyState}><div className={styles.illustration} aria-hidden="true"><div className={styles.gridDots}/><span className={styles.illTileOne}><i/>€<b>VAT</b></span><span className={styles.illOrb}>{canBookkeep?<Sparkles size={24}/>:<Eye size={24}/>}</span><span className={styles.illTileTwo}><i/><i/><i/></span><span className={styles.illTileThree}>J<span>0058</span></span></div><h2>{canBookkeep?"Ask the business question. Skip the accounting jargon.":"Read-only access"}</h2><p>{canBookkeep?"Copilot can explain VAT, cash, invoices, tax reserve, compliance blockers and posted accounting using the records already inside Compta.":"A Viewer can inspect company records across Compta but cannot create persistent Copilot conversations."}</p>{canBookkeep?<div className={styles.prompts}>{prompts.map(prompt=><button key={prompt} type="button" onClick={()=>setQuestion(prompt)}>{prompt}</button>)}</div>:null}</div>}</div>
 {canBookkeep?<div className={styles.composerWrap}><form ref={formRef} action={action} className={styles.ask}><input type="hidden" name="conversation_id" value={activeConversationId??""}/><textarea name="question" value={question} onChange={event=>setQuestion(event.target.value)} placeholder="Ask Compta about your company…" rows={2}/><button type="submit" disabled={pending||question.trim().length<3} aria-label="Ask Compta">{pending?<LoaderCircle className={styles.spin}/>:<ArrowUp/>}</button></form>{state.status==="error"?<p className={styles.error}>{state.message}</p>:null}<footer>Read-only · Copilot cannot post entries or submit filings.</footer></div>:null}</main></div>;
}
