"use client";

import { ArrowLeft, ArrowRight, BookOpenCheck, FileCode2, FileSpreadsheet, FileText, FolderPlus, Landmark, ListOrdered, LoaderCircle, Plus, ShieldCheck, UploadCloud, X } from "lucide-react";
import Link from "next/link";
import { createPortal } from "react-dom";
import { useActionState, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { generateFinancialDocumentAction, type GeneratedDocumentState } from "@/app/app/documents/generated-actions";
import { createClient } from "@/lib/supabase/client";
import { useRolePermissions } from "@/components/role-context";
import styles from "./documents.module.css";
import createStyles from "./document-create.module.css";

const ALLOWED=new Set(["application/pdf","image/jpeg","image/png","image/webp","text/csv"]);const MAX_BYTES=25*1024*1024;
type DocumentType="receipt"|"purchase_invoice"|"sales_invoice"|"bank_statement"|"tax_notice"|"filing"|"annex"|"other";type Mode="home"|"upload"|"generate";
const initialGenerated:GeneratedDocumentState={status:"idle",message:""};
const reports=[
 {value:"annual_accounts",label:"Annual Accounts",detail:"Cover, closing balance sheet and detailed Profit & Loss",icon:BookOpenCheck,csv:false},
 {value:"profit_loss",label:"Profit & Loss",detail:"Detailed income and expense accounts",icon:FileSpreadsheet,csv:true},
 {value:"balance_sheet",label:"Balance Sheet",detail:"Closing assets, equity and liabilities",icon:Landmark,csv:true},
 {value:"pcn",label:"PCN Closing Balances",detail:"Net year-end debit and credit balances by PCN account",icon:FileCode2,csv:true},
 {value:"trial_balance",label:"Trial Balance",detail:"Turnover and closing debit / credit position",icon:FileSpreadsheet,csv:true},
 {value:"general_ledger",label:"General Ledger",detail:"Account-by-account movements with running balances",icon:FileText,csv:true},
 {value:"general_journal",label:"General Journal",detail:"Chronological journal entries with immutable references",icon:ListOrdered,csv:true},
 {value:"annexe",label:"Annexe - Draft",detail:"Evidence-based notes summary prepared for review",icon:FileText,csv:false}
] as const;
function safeFileName(name:string){const parts=name.split("."),ext=parts.length>1?`.${parts.pop()?.toLowerCase().replace(/[^a-z0-9]/g,"")}`:"",base=parts.join(".").normalize("NFKD").replace(/[^a-zA-Z0-9-_]+/g,"-").replace(/^-+|-+$/g,"").slice(0,80)||"document";return`${base}${ext}`}
function isBillingLimit(message:string){return message.includes("ZU_BILLING_LIMIT")}

export function DocumentUploader({organizationId,companyId}:{organizationId:string;companyId:string}){
 const {canBookkeep}=useRolePermissions();const router=useRouter(),inputRef=useRef<HTMLInputElement>(null);const[file,setFile]=useState<File|null>(null),[type,setType]=useState<DocumentType>("receipt"),[busy,setBusy]=useState(false),[dragging,setDragging]=useState(false),[message,setMessage]=useState<string|null>(null),[upgradeNeeded,setUpgradeNeeded]=useState(false),[open,setOpen]=useState(false),[mode,setMode]=useState<Mode>("home"),[report,setReport]=useState<(typeof reports)[number]["value"]>("annual_accounts"),[closedYears,setClosedYears]=useState<number[]>([]),[year,setYear]=useState(""),[mounted,setMounted]=useState(false);const[generatedState,generatedAction,generatedPending]=useActionState(generateFinancialDocumentAction,initialGenerated);
 useEffect(()=>setMounted(true),[]);
 useEffect(()=>{if(!canBookkeep)return;const supabase=createClient();supabase.from("filings").select("period_label").eq("company_id",companyId).eq("filing_type","ecdf_accounts").not("ledger_snapshot","is",null).order("period_label",{ascending:false}).then(({data})=>{const years=[...new Set((data??[]).map(row=>Number(row.period_label)).filter(Number.isInteger))];setClosedYears(years);if(years.length)setYear(current=>current||String(years[0]))})},[companyId,canBookkeep]);
 useEffect(()=>{if(generatedState.status==="success")router.refresh()},[generatedState.status,router]);
 useEffect(()=>{if(!open)return;const previous=document.body.style.overflow;document.body.style.overflow="hidden";const onKey=(event:KeyboardEvent)=>{if(event.key==="Escape")close()};window.addEventListener("keydown",onKey);return()=>{document.body.style.overflow=previous;window.removeEventListener("keydown",onKey)}},[open]);
 function close(){setOpen(false);setMode("home")}function choose(next:File|null){setMessage(null);setUpgradeNeeded(false);if(!next)return setFile(null);if(!ALLOWED.has(next.type))return setMessage("Use PDF, JPG, PNG, WebP or CSV.");if(next.size>MAX_BYTES)return setMessage("The maximum file size is 25 MB.");setFile(next)}
 async function upload(){if(!file)return setMessage("Choose a document first.");setBusy(true);setMessage(null);setUpgradeNeeded(false);const supabase=createClient();let storagePath="";try{const{data:userData,error:userError}=await supabase.auth.getUser();if(userError||!userData.user)throw new Error("Your session expired. Please sign in again.");const{error:limitError}=await supabase.rpc("assert_usage_available",{p_organization_id:organizationId,p_metric:"documents",p_quantity:1});if(limitError){if(isBillingLimit(limitError.message)){setUpgradeNeeded(true);throw new Error("You've used all 3 document uploads included in Basic for this billing period. Upgrade to Premium for unlimited document uploads.")}throw limitError}const uploadYear=new Date().getFullYear();storagePath=`${organizationId}/${companyId}/${uploadYear}/${crypto.randomUUID()}-${safeFileName(file.name)}`;const{error:storageError}=await supabase.storage.from("company-documents").upload(storagePath,file,{contentType:file.type,upsert:false,cacheControl:"3600"});if(storageError)throw storageError;const{error:metadataError}=await supabase.from("documents").insert({organization_id:organizationId,company_id:companyId,type,storage_path:storagePath,file_name:file.name,mime_type:file.type,file_size:file.size,extraction_status:"not_started",created_by:userData.user.id});if(metadataError){await supabase.storage.from("company-documents").remove([storagePath]);if(isBillingLimit(metadataError.message)){setUpgradeNeeded(true);throw new Error("You've used all 3 document uploads included in Basic for this billing period. Upgrade to Premium for unlimited document uploads.")}throw metadataError}setFile(null);if(inputRef.current)inputRef.current.value="";setMessage("Document secured in Zuelen.");router.refresh();window.setTimeout(close,450)}catch(error){setMessage(error instanceof Error?error.message:"The document could not be uploaded.")}finally{setBusy(false)}}
 const selected=reports.find(r=>r.value===report)!;
 if(!mounted||!canBookkeep)return null;
 const modal=open?<div className={createStyles.modalOverlay} role="presentation" onMouseDown={event=>{if(event.currentTarget===event.target)close()}}><div className={createStyles.modalShell} role="dialog" aria-modal="true" aria-label="Create document"><button className={createStyles.modalClose} type="button" onClick={close} aria-label="Close document creator"><X size={19}/></button><aside className={`${styles.uploadCard} ${createStyles.modalCard}`}>
 {mode==="home"?<><div className={styles.uploadHead}><div><p>Document centre</p><h2>Create</h2></div><span><ShieldCheck size={14}/>Private</span></div><p className={styles.uploadLead}>Choose how you want to add to the document library. Upload source evidence, or generate a professional financial report from a closed accounting snapshot.</p><div className={createStyles.createChoices}><button type="button" onClick={()=>setMode("upload")}><span><UploadCloud size={21}/></span><div><strong>Upload document</strong><small>Add a receipt, supplier invoice, bank statement, filing or other company record to the secure evidence vault.</small></div></button><button type="button" onClick={()=>setMode("generate")}><span><FolderPlus size={21}/></span><div><strong>Generate financial document</strong><small>Create financial statements, PCN closing balances, trial balance, ledger, journal or annual-account models from a frozen year.</small></div></button></div></>:null}
 {mode==="upload"?<><button type="button" className={createStyles.drawerBack} onClick={()=>setMode("home")}><ArrowLeft size={14}/>Back to Create</button><div className={styles.uploadHead}><div><p>Secure intake</p><h2>Upload document</h2></div><span><ShieldCheck size={14}/>Private</span></div><p className={styles.uploadLead}>Choose the category, then add the original file. Zuelen keeps source evidence separate from accounting entries and extracted facts.</p><label className={styles.typeField}><span>Document category</span><select value={type} onChange={e=>setType(e.target.value as DocumentType)} disabled={busy}><option value="receipt">Receipt</option><option value="purchase_invoice">Supplier invoice</option><option value="sales_invoice">Sales invoice sent to a customer</option><option value="bank_statement">Bank statement</option><option value="tax_notice">Tax notice / authority letter</option><option value="filing">Filed declaration</option><option value="annex">Annual accounts annex</option><option value="other">Business / other document</option></select></label><button type="button" className={`${styles.dropzone} ${dragging?styles.dropzoneActive:""}`} onClick={()=>inputRef.current?.click()} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);choose(e.dataTransfer.files[0]??null)}} disabled={busy}><input ref={inputRef} type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.csv" onChange={e=>choose(e.target.files?.[0]??null)} hidden/>{file?<><span className={styles.fileIcon}><FileText size={21}/></span><strong>{file.name}</strong><small>{(file.size/1024/1024).toFixed(2)} MB</small></>:<><span className={styles.cloudIcon}><UploadCloud size={22}/></span><strong>Drop a document here</strong><small>or click to choose · max 25 MB</small></>}</button>{file?<button className={styles.clearFile} type="button" onClick={()=>choose(null)} disabled={busy}><X size={13}/>Remove file</button>:null}{message?<div className={message==="Document secured in Zuelen."?styles.successMessage:styles.errorMessage}>{message}{upgradeNeeded?<div className={createStyles.generatedLinks}><Link href="/app/settings/billing">Upgrade to Premium <ArrowRight size={12}/></Link><Link href="/app/settings/usage">View usage</Link></div>:null}</div>:null}<button type="button" className={`${styles.uploadButton} ${createStyles.primaryModalAction}`} onClick={upload} disabled={busy||!file}>{busy?<LoaderCircle className={styles.spin} size={15}/>:<UploadCloud size={15}/>} {busy?"Securing document…":"Upload to Zuelen"}</button></>:null}
 {mode==="generate"?<><button type="button" className={createStyles.drawerBack} onClick={()=>setMode("home")}><ArrowLeft size={14}/>Back to Create</button><div className={styles.uploadHead}><div><p>Frozen financials</p><h2>Generate report</h2></div><span><ShieldCheck size={14}/>Premium</span></div><p className={styles.uploadLead}>Choose a closed year and report type. You can explore the full workflow on Basic; creating the filing-ready output requires Premium.</p>{closedYears.length?<form action={generatedAction}><label className={styles.typeField}><span>Financial year</span><select name="fiscal_year" value={year} onChange={e=>setYear(e.target.value)}>{closedYears.map(y=><option key={y} value={y}>{y}</option>)}</select></label><div className={createStyles.reportGrid}>{reports.map(item=><button type="button" key={item.value} className={report===item.value?createStyles.reportActive:""} onClick={()=>setReport(item.value)}><span><item.icon size={17}/></span><div><strong>{item.label}</strong><small>{item.detail}</small></div></button>)}</div><input type="hidden" name="document_type" value={report}/><div className={createStyles.formatNote}><strong>Output</strong><span>PDF{selected.csv?" + CSV":""}</span><small>{selected.csv?"PDF is presentation-ready; CSV is a structured working export.":"PDF generated from the frozen closing snapshot."}</small></div>{generatedState.message?<div className={generatedState.status==="error"?styles.errorMessage:styles.successMessage}>{generatedState.message}{generatedState.upgradeRequired?<div className={createStyles.generatedLinks}><Link href="/app/settings/billing">Upgrade to Premium <ArrowRight size={12}/></Link><Link href="/app/settings/usage">View usage</Link></div>:generatedState.documentId?<div className={createStyles.generatedLinks}><Link href={`/app/documents/generated/${generatedState.documentId}/pdf`}>Download PDF</Link>{selected.csv?<Link href={`/app/documents/generated/${generatedState.documentId}/csv`}>Download CSV</Link>:null}</div>:null}</div>:null}<button type="submit" className={`${styles.uploadButton} ${createStyles.primaryModalAction}`} disabled={generatedPending}>{generatedPending?<LoaderCircle className={styles.spin} size={15}/>:<FolderPlus size={15}/>} {generatedPending?"Generating document…":`Generate ${selected.label}`}</button></form>:<div className={styles.errorMessage}>No closing snapshot is available yet. Close a financial year before generating financial documents.</div>}</>:null}
 </aside></div></div>:null;
 return createPortal(<><button className={styles.fab} type="button" onClick={()=>{setMode("home");setOpen(true)}}><Plus size={17}/>Create</button>{modal}</>,document.body);
}
