"use client";

import { LoaderCircle, Pencil, Trash2, X } from "lucide-react";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { useRolePermissions } from "@/components/role-context";
import styles from "./record-actions.module.css";

type DocumentType="receipt"|"purchase_invoice"|"sales_invoice"|"bank_statement"|"tax_notice"|"filing"|"annex"|"other";
export function DocumentRowActions({id,storagePath,fileName,type}:{id:string;storagePath:string;fileName:string;type:DocumentType}){
  const{canBookkeep}=useRolePermissions(),dialog=useRef<HTMLDialogElement>(null);const router=useRouter();const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");
  async function save(formData:FormData){setBusy(true);setMessage("");const nextName=String(formData.get("file_name")??"").trim(),nextType=String(formData.get("type")??type) as DocumentType;if(!nextName){setMessage("File name is required.");setBusy(false);return}const supabase=createClient();const{error}=await supabase.from("documents").update({file_name:nextName,type:nextType}).eq("id",id);setBusy(false);if(error){setMessage(error.message);return}dialog.current?.close();router.refresh()}
  async function remove(){if(!window.confirm("Delete this document from Zuelen? This removes the private file and its metadata."))return;setBusy(true);setMessage("");const supabase=createClient();const{error:storageError}=await supabase.storage.from("company-documents").remove([storagePath]);if(storageError){setMessage(storageError.message);setBusy(false);return}const{error}=await supabase.from("documents").delete().eq("id",id);setBusy(false);if(error){setMessage(error.message);return}router.refresh()}
  if(!canBookkeep)return null;
  return <div className={styles.actions}><button type="button" className={styles.iconButton} onClick={()=>dialog.current?.showModal()} aria-label="Edit document"><Pencil size={13}/></button><button type="button" className={`${styles.iconButton} ${styles.danger}`} onClick={remove} disabled={busy} aria-label="Delete document">{busy?<LoaderCircle className={styles.spin} size={13}/>:<Trash2 size={13}/>}</button><dialog ref={dialog} className={styles.dialog}><form action={save} className={styles.dialogCard}><div className={styles.dialogHead}><div><span>Document metadata</span><h3>Edit document</h3></div><button type="button" onClick={()=>dialog.current?.close()}><X size={16}/></button></div><div className={styles.grid}><label className={styles.full}><span>Display name</span><input name="file_name" defaultValue={fileName} required/></label><label className={styles.full}><span>Document type</span><select name="type" defaultValue={type}><option value="receipt">Receipt</option><option value="purchase_invoice">Supplier invoice</option><option value="sales_invoice">Sales invoice</option><option value="bank_statement">Bank statement</option><option value="tax_notice">Tax notice / authority letter</option><option value="filing">Filed declaration</option><option value="annex">Annual accounts annex</option><option value="other">Other document</option></select></label></div>{message?<div className={styles.error}>{message}</div>:null}<div className={styles.dialogFooter}><button type="button" className={styles.secondary} onClick={()=>dialog.current?.close()}>Cancel</button><button type="submit" className={styles.primary} disabled={busy}>{busy?<LoaderCircle className={styles.spin} size={14}/>:<Pencil size={14}/>}Save changes</button></div></form></dialog>{message?<span className={styles.inlineError}>{message}</span>:null}</div>
}
