"use client";

import { ArrowLeft, BadgeCheck, FileCheck2, LoaderCircle, Plus, Save, Send, Trash2 } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useActionState, useEffect, useMemo, useState } from "react";
import { correctAndReissueInvoice, saveOrIssueInvoice, type InvoiceActionState } from "@/app/app/invoices/actions";
import { CountrySelect } from "@/components/country-select";
import { useI18n } from "@/components/locale-context";
import styles from "./invoice.module.css";

type Company={legal_name:string;legal_form:string;rcs_number:string|null;vat_number:string|null;business_permit_number:string|null;registered_address:Record<string,unknown>;base_currency:string};
type Line={id:number;description:string;quantity:number;unit_price:number;vat_rate:number};
export type InvoiceComposerInitial={customer_name:string;customer_email:string;customer_country:string;customer_vat_number:string;customer_street:string;customer_postal_code:string;customer_city:string;issue_date:string;service_date:string;due_date:string;vat_treatment:string;notes:string;lines:Line[]};
const initialInvoiceState:InvoiceActionState={status:"idle",message:"",invoiceId:null};
function dateOffset(days:number){const date=new Date();date.setDate(date.getDate()+days);return date.toISOString().slice(0,10)}
function addressValue(address:Record<string,unknown>,key:string){const value=address[key];return typeof value==="string"?value:""}

export function InvoiceComposer({company,initialInvoice,correctionInvoiceId,draftInvoiceId}:{company:Company;initialInvoice?:InvoiceComposerInitial;correctionInvoiceId?:string;draftInvoiceId?:string}){
 const router=useRouter(),{locale,intlLocale}=useI18n(),fr=locale==="fr",action=correctionInvoiceId?correctAndReissueInvoice:saveOrIssueInvoice,[state,formAction,pending]=useActionState(action,initialInvoiceState);
 const money=(value:number,currency:string)=>new Intl.NumberFormat(intlLocale,{style:"currency",currency,minimumFractionDigits:2}).format(value);
 const[vatTreatment,setVatTreatment]=useState(initialInvoice?.vat_treatment??"domestic"),[customerName,setCustomerName]=useState(initialInvoice?.customer_name??""),[customerEmail,setCustomerEmail]=useState(initialInvoice?.customer_email??""),[customerStreet,setCustomerStreet]=useState(initialInvoice?.customer_street??""),[customerPostal,setCustomerPostal]=useState(initialInvoice?.customer_postal_code??""),[customerCity,setCustomerCity]=useState(initialInvoice?.customer_city??""),[customerCountry,setCustomerCountry]=useState(initialInvoice?.customer_country??"LU"),[customerVat,setCustomerVat]=useState(initialInvoice?.customer_vat_number??""),[issueDate,setIssueDate]=useState(initialInvoice?.issue_date??dateOffset(0)),[serviceDate,setServiceDate]=useState(initialInvoice?.service_date??dateOffset(0)),[dueDate,setDueDate]=useState(initialInvoice?.due_date??dateOffset(14)),[notes,setNotes]=useState(initialInvoice?.notes??""),[pricesIncludeVat,setPricesIncludeVat]=useState(false);
 const[lines,setLines]=useState<Line[]>(initialInvoice?.lines?.length?initialInvoice.lines:[{id:1,description:fr?"Services professionnels":"Professional services",quantity:1,unit_price:0,vat_rate:17}]);
 useEffect(()=>{if(state.status==="success"&&state.invoiceId)router.push(`/app/invoices/${state.invoiceId}`)},[router,state.invoiceId,state.status]);
 const normalizedLines=useMemo(()=>lines.map(line=>{const rate=vatTreatment==="eu_b2b_reverse_charge"?0:Number(line.vat_rate),entered=Number(line.unit_price||0),netUnit=pricesIncludeVat&&rate>0?entered/(1+rate/100):entered;return{...line,unit_price:Number(netUnit.toFixed(4)),vat_rate:rate}}),[lines,vatTreatment,pricesIncludeVat]);
 const totals=useMemo(()=>normalizedLines.reduce((acc,line)=>{const net=Number(line.quantity||0)*Number(line.unit_price||0),vat=net*Number(line.vat_rate||0)/100;return{net:acc.net+net,vat:acc.vat+vat,gross:acc.gross+net+vat}},{net:0,vat:0,gross:0}),[normalizedLines]);
 function updateLine(index:number,patch:Partial<Line>){setLines(current=>current.map((line,i)=>i===index?{...line,...patch}:line))}function addLine(){setLines(current=>[...current,{id:Date.now(),description:"",quantity:1,unit_price:0,vat_rate:17}])}function removeLine(index:number){setLines(current=>current.length===1?current:current.filter((_,i)=>i!==index))}
 const issuerStreet=addressValue(company.registered_address,"street"),issuerPostal=addressValue(company.registered_address,"postal_code"),issuerCity=addressValue(company.registered_address,"city"),correcting=Boolean(correctionInvoiceId),editingDraft=Boolean(draftInvoiceId),backHref=correctionInvoiceId?`/app/invoices/${correctionInvoiceId}`:draftInvoiceId?`/app/invoices/${draftInvoiceId}`:"/app/invoices";
 return <div className={styles.composerShell}><form action={formAction} className={styles.composerForm}>{correctionInvoiceId?<input type="hidden" name="original_invoice_id" value={correctionInvoiceId}/>:null}{draftInvoiceId?<input type="hidden" name="draft_invoice_id" value={draftInvoiceId}/>:null}<div className={styles.formTop}><Link href={backHref} className={styles.backLink}><ArrowLeft size={14}/>{correcting?(fr?"Facture originale":"Original invoice"):editingDraft?(fr?"Facture brouillon":"Draft invoice"):(fr?"Factures":"Invoices")}</Link><span className={styles.legalReady}><BadgeCheck size={13}/>{correcting?(fr?"Workflow de correction":"Correction workflow"):editingDraft?(fr?"Brouillon modifiable":"Editable draft"):(fr?"Profil de facture LU":"LU invoice profile")}</span></div><div className={styles.composerHeading}><p>{correcting?(fr?"Corriger la facture":"Correct invoice"):editingDraft?(fr?"Modifier le brouillon":"Edit draft"):(fr?"Créer une facture":"Create invoice")}</p><h1>{correcting?(fr?"Corriger sans réécrire l’historique.":"Fix it without rewriting history."):editingDraft?(fr?"Affinez-la avant sa comptabilisation.":"Refine it before it hits the books."):(fr?"Brouillon d’abord. Comptabilisation seulement quand tout est prêt.":"Draft first. Post only when ready.")}</h1><span>{correcting?(fr?"Zuelen contrepassera la facture originale et émettra cette facture corrigée de remplacement.":"Zuelen will reverse the original invoice and issue this corrected replacement."):(fr?"Les brouillons restent entièrement modifiables et n’affectent ni les produits, ni la TVA, ni les créances tant que vous ne les émettez pas explicitement.":"Drafts stay fully editable and do not affect revenue, VAT or receivables until you explicitly issue them.")}</span></div>
 <section className={styles.formSection}><div className={styles.sectionTitle}><span>01</span><div><strong>{fr?"Client":"Customer"}</strong><small>{fr?"À qui facturez-vous ?":"Who are you billing?"}</small></div></div><div className={styles.formGrid}><label className={styles.full}><span>{fr?"Client / dénomination légale":"Customer / legal name"}</span><input name="customer_name" value={customerName} onChange={e=>setCustomerName(e.target.value)} required/></label><label><span>E-mail</span><input name="customer_email" type="email" value={customerEmail} onChange={e=>setCustomerEmail(e.target.value)}/></label><label><span>{fr?"Pays":"Country"}</span><CountrySelect name="customer_country" value={customerCountry} onChange={value=>{setCustomerCountry(value);setCustomerPostal(current=>value==="LU"?`L-${current.replace(/\D/g,"").slice(0,4)}`:current.replace(/^L-/,""))}} required/></label><label className={styles.full}><span>{fr?"Rue de facturation":"Billing street"}</span><input name="customer_street" value={customerStreet} onChange={e=>setCustomerStreet(e.target.value)} required/></label><label><span>{fr?"Code postal":"Postal code"}</span><input name="customer_postal_code" value={customerCountry==="LU"?(customerPostal.startsWith("L-")?customerPostal:`L-${customerPostal.replace(/\D/g,"").slice(0,4)}`):customerPostal} onChange={e=>setCustomerPostal(customerCountry==="LU"?`L-${e.target.value.replace(/\D/g,"").slice(0,4)}`:e.target.value)} pattern={customerCountry==="LU"?"L-[0-9]{4}":undefined} inputMode={customerCountry==="LU"?"numeric":undefined} placeholder={customerCountry==="LU"?"L-1234":undefined} required/></label><label><span>{fr?"Ville":"City"}</span><input name="customer_city" value={customerCity} onChange={e=>setCustomerCity(e.target.value)} required/></label><label className={styles.full}><span>{fr?"Numéro TVA du client":"Customer VAT number"}</span><input name="customer_vat_number" value={customerVat} onChange={e=>setCustomerVat(e.target.value)} required={vatTreatment==="eu_b2b_reverse_charge"}/></label></div></section>
 <section className={styles.formSection}><div className={styles.sectionTitle}><span>02</span><div><strong>{fr?"Paramètres de la facture":"Invoice logic"}</strong><small>{fr?"Dates et traitement TVA":"Dates and VAT treatment"}</small></div></div><div className={styles.formGrid}><label><span>{fr?"Date d’émission":"Issue date"}</span><input name="issue_date" type="date" value={issueDate} onChange={e=>setIssueDate(e.target.value)} required/></label><label><span>{fr?"Date de prestation":"Service date"}</span><input name="service_date" type="date" value={serviceDate} onChange={e=>setServiceDate(e.target.value)} required/></label><label><span>{fr?"Date d’échéance":"Due date"}</span><input name="due_date" type="date" value={dueDate} onChange={e=>setDueDate(e.target.value)} required/></label><label><span>{fr?"Traitement TVA":"VAT treatment"}</span><select name="vat_treatment" value={vatTreatment} onChange={e=>setVatTreatment(e.target.value)}><option value="domestic">TVA Luxembourg</option><option value="eu_b2b_reverse_charge">{fr?"B2B UE · autoliquidation":"EU B2B · reverse charge"}</option></select></label><label className={styles.full}><span>{fr?"Prix saisis en":"Prices entered as"}</span><select value={pricesIncludeVat?"gross":"net"} onChange={e=>setPricesIncludeVat(e.target.value==="gross")}><option value="net">{fr?"HT / hors TVA · recommandé pour les factures B2B":"HT / excluding VAT · recommended for B2B invoices"}</option><option value="gross">{fr?"TTC / TVA comprise · Zuelen extrait automatiquement la TVA":"TTC / including VAT · Zuelen extracts VAT automatically"}</option></select></label></div>{vatTreatment==="eu_b2b_reverse_charge"?<div className={styles.ruleNote}><FileCheck2 size={14}/><span>{fr?"La TVA est forcée à 0 % et la mention « autoliquidation » est ajoutée à la facture émise.":"VAT is forced to 0% and “auto-liquidation” is added to the issued invoice."}</span></div>:null}</section>
 <section className={styles.formSection}><div className={styles.sectionTitle}><span>03</span><div><strong>{fr?"Prestations":"Services"}</strong><small>{fr?"Que facturez-vous ?":"What are you charging for?"}</small></div></div><div className={styles.lineEditor}>{lines.map((line,index)=><div className={styles.editorLine} key={line.id}><label className={styles.lineDescription}><span>Description</span><input value={line.description} onChange={e=>updateLine(index,{description:e.target.value})} required/></label><label><span>{fr?"Qté":"Qty"}</span><input type="number" min="0.0001" step="0.0001" value={line.quantity} onChange={e=>updateLine(index,{quantity:Number(e.target.value)})} required/></label><label><span>{pricesIncludeVat?"Prix unitaire TTC":"Prix unitaire HT"}</span><input type="number" min="0" step="0.01" value={line.unit_price} onChange={e=>updateLine(index,{unit_price:Number(e.target.value)})} required/></label><label><span>TVA</span><select value={vatTreatment==="eu_b2b_reverse_charge"?0:line.vat_rate} disabled={vatTreatment==="eu_b2b_reverse_charge"} onChange={e=>updateLine(index,{vat_rate:Number(e.target.value)})}><option value={17}>17%</option><option value={14}>14%</option><option value={8}>8%</option><option value={3}>3%</option><option value={0}>0%</option></select></label><button type="button" className={styles.removeLine} onClick={()=>removeLine(index)} aria-label={fr?"Supprimer la ligne":"Remove line"}><Trash2 size={14}/></button></div>)}</div><button type="button" className={styles.addLine} onClick={addLine}><Plus size={14}/>{fr?"Ajouter une ligne":"Add line"}</button><input type="hidden" name="lines_json" value={JSON.stringify(normalizedLines)}/><label className={styles.notesField}><span>Notes</span><textarea name="notes" value={notes} onChange={e=>setNotes(e.target.value)}/></label></section>
 {state.message?<div className={`${styles.actionMessage} ${state.status==="error"?styles.actionError:""}`}>{state.message}</div>:null}{correcting?<button className={styles.issueButton} type="submit" disabled={pending}>{pending?<LoaderCircle size={16} className={styles.spin}/>:<Send size={15}/>}<span>{pending?(fr?"Correction et recomptabilisation…":"Correcting & reposting…"):(fr?"Émettre la correction et contrepasser l’original":"Issue correction & reverse original")}</span></button>:<><button className={styles.addLine} type="submit" name="intent" value="save_draft" disabled={pending}><Save size={14}/>{pending?(fr?"Enregistrement…":"Saving…"):(fr?"Enregistrer le brouillon":"Save draft")}</button><button className={styles.issueButton} type="submit" name="intent" value="issue" disabled={pending}>{pending?<LoaderCircle size={16} className={styles.spin}/>:<Send size={15}/>}<span>{pending?(fr?"Traitement…":"Working…"):(fr?"Émettre la facture et comptabiliser":"Issue invoice & post ledger")}</span></button></>}</form>
 <aside className={styles.previewStage}><div className={styles.previewToolbar}><span>{correcting?(fr?"Aperçu du document corrigé":"Corrected document preview"):(fr?"Aperçu en direct":"Live document preview")}</span><span>{fr?"BROUILLON":"DRAFT"}</span></div><article className={styles.invoicePaper}><header className={styles.invoiceHeader}><div><img className={styles.paperBrand} src="/zuelen-icon.png" alt="Zuelen"/><strong>{company.legal_name}</strong><small>{company.legal_form}</small></div><div className={styles.invoiceWord}><span>{fr?"FACTURE":"INVOICE"}</span><small>{correcting?(fr?"Nouveau numéro attribué lors de la correction":"New number assigned on correction"):(fr?"Numéro attribué uniquement lors de l’émission":"Number assigned only when issued")}</small></div></header><div className={styles.invoiceMetaGrid}><div><span>{fr?"DE":"FROM"}</span><strong>{company.legal_name}</strong><p>{issuerStreet}<br/>{issuerPostal} {issuerCity}<br/>Luxembourg</p></div><div><span>{fr?"FACTURÉ À":"BILL TO"}</span><strong>{customerName||(fr?"Nom du client":"Customer name")}</strong><p>{customerStreet||(fr?"Rue de facturation":"Billing street")}<br/>{customerPostal||(fr?"Code postal":"Postal")} {customerCity||(fr?"Ville":"City")}<br/>{customerCountry||(fr?"Pays":"Country")}</p></div></div><div className={styles.previewDates}><div><span>{fr?"ÉMISSION":"ISSUE"}</span><strong>{issueDate}</strong></div><div><span>{fr?"ÉCHÉANCE":"DUE"}</span><strong>{dueDate}</strong></div><div><span>{fr?"DEVISE":"CURRENCY"}</span><strong>{company.base_currency}</strong></div></div><div className={styles.previewTable}><div className={styles.previewTableHead}><span>DESCRIPTION</span><span>{fr?"QTÉ":"QTY"}</span><span>{fr?"PRIX":"RATE"}</span><span>{fr?"MONTANT":"AMOUNT"}</span></div>{normalizedLines.map((line,index)=><div className={styles.previewTableRow} key={line.id}><span>{line.description||(fr?"Prestation":"Service")}<small>{line.vat_rate}% TVA</small></span><span>{line.quantity}</span><span>{money(lines[index]?.unit_price??line.unit_price,company.base_currency)}</span><strong>{money(line.quantity*line.unit_price,company.base_currency)}</strong></div>)}</div><div className={styles.previewTotals}><div><span>{fr?"Sous-total":"Subtotal"}</span><strong>{money(totals.net,company.base_currency)}</strong></div><div><span>TVA</span><strong>{money(totals.vat,company.base_currency)}</strong></div><div className={styles.totalRow}><span>Total</span><strong>{money(totals.gross,company.base_currency)}</strong></div></div>{vatTreatment==="eu_b2b_reverse_charge"?<div className={styles.reverseCharge}>AUTO-LIQUIDATION · REVERSE CHARGE</div>:null}<footer className={styles.invoiceFooter}><span>R.C.S. Luxembourg {company.rcs_number||"—"}</span><span>Autorisation {company.business_permit_number||"—"}</span><span>TVA {company.vat_number||"—"}</span></footer></article></aside></div>
}
