"use client";

import { ArrowDownLeft, ArrowUpRight, CheckCircle2, Landmark, LoaderCircle, LockKeyhole, Search, Sparkles, X } from "lucide-react";
import { useActionState, useMemo, useState } from "react";
import { postSourceTransaction, type TransactionActionState } from "@/app/app/transactions/actions";
import styles from "./transaction-review-card.module.css";

type Account={id:string;code:string;label:string;account_type:string};
type PcnAccount={id:string;code:string;label:string;account_type:string;account_class:number|null;parent_code:string|null};
type Transaction={id:string;occurred_on:string;direction:string;amount_gross:number|string;amount_net:number|string|null;vat_amount:number|string|null;currency:string;counterparty_name:string|null;description:string|null;suggested_account_id?:string|null;suggestion_confidence?:number|string|null;suggestion_reason?:string|null;suggestion_kind?:string|null;display_name?:string|null;bank_evidence?:string|null};
const initialTransactionState:TransactionActionState={status:"idle",message:""};
function money(value:number,currency:string){return new Intl.NumberFormat("en-LU",{style:"currency",currency,minimumFractionDigits:2}).format(value)}
function normalize(value:string){return value.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim()}
function aliases(account:PcnAccount){const code=account.code;const terms:string[]=[];if(code==="6132")terms.push("software saas cloud hosting website web wix hostinger chatgpt openai it informatique logiciel abonnement subscription digital service");if(code.startsWith("6151"))terms.push("marketing advertising ads facebook meta google ads campaign publicity publicite promotion social media");if(code==="61333"||code==="61338")terms.push("bank fee bank charge banking commission post finance frais bancaire frais compte commission");if(code==="61532")terms.push("phone mobile internet telecom telephone telecommunications");if(code==="61348"||code==="6138")terms.push("professional fee consultant freelancer contractor honoraires consulting service provider");if(code==="6413")terms.push("software licence license subscription app saas");if(code.startsWith("703"))terms.push("client payment service revenue sales invoice upwork freelance web design development customer income chiffre affaires prestation");if(code.startsWith("611"))terms.push("rent rental lease office coworking loyer location");if(code.startsWith("612"))terms.push("maintenance repair entretien reparation");if(code.startsWith("614"))terms.push("insurance assurance");if(code.startsWith("616"))terms.push("travel transport hotel restaurant meal deplacement voyage");return terms.join(" ")}
function groupLabel(account:PcnAccount,fr:boolean){if(account.account_type==="expense")return fr?"Charges":"Expenses";if(account.account_type==="revenue")return fr?"Produits":"Revenue";if(account.account_type==="asset")return fr?"Actifs":"Assets";if(account.account_type==="liability")return fr?"Passifs":"Liabilities";if(account.account_type==="equity")return fr?"Capitaux propres":"Equity";return fr?"Autres":"Other"}
function scoreAccount(account:PcnAccount,query:string,context:string){const q=normalize(query),tokens=q.split(" ").filter(Boolean),label=normalize(`${account.code} ${account.label} ${aliases(account)}`),contextNorm=normalize(context);let score=0;if(!q)return 0;if(account.code===q)score+=180;else if(account.code.startsWith(q))score+=120;if(label.includes(q))score+=80;for(const token of tokens){if(label.includes(token))score+=28;if(contextNorm.includes(token))score+=4}if(tokens.length&&tokens.every(token=>label.includes(token)))score+=35;return score}

export function TransactionReviewCard({transaction,accounts,pcnAccounts,locale="en"}:{transaction:Transaction;accounts:Account[];pcnAccounts:PcnAccount[];locale?:"en"|"fr"}){
  const fr=locale==="fr",income=transaction.direction==="income";
  const suggestedCompany=accounts.find(account=>account.id===transaction.suggested_account_id);
  const suggested=pcnAccounts.find(account=>account.code===suggestedCompany?.code);
  const[accountCode,setAccountCode]=useState(suggested?.code??"");
  const[purpose,setPurpose]=useState("");
  const[state,formAction,pending]=useActionState(postSourceTransaction,initialTransactionState);
  const eligible=useMemo(()=>pcnAccounts.filter(account=>{if(["5131","421611","461411"].includes(account.code))return false;return income?["revenue","asset","liability","expense"].includes(account.account_type):["expense","asset","liability"].includes(account.account_type)}),[pcnAccounts,income]);
  const selected=eligible.find(account=>account.code===accountCode);
  const context=`${transaction.display_name??""} ${transaction.counterparty_name??""} ${transaction.description??""} ${transaction.bank_evidence??""}`;
  const results=useMemo(()=>{if(normalize(purpose).length<2)return[];return eligible.map(account=>({account,score:scoreAccount(account,purpose,context)})).filter(item=>item.score>0).sort((a,b)=>b.score-a.score||a.account.code.localeCompare(b.account.code)).slice(0,8).map(item=>item.account)},[eligible,purpose,context]);
  const gross=Number(transaction.amount_gross),vat=Number(transaction.vat_amount??0),net=Number(transaction.amount_net??gross-vat),isExpenseRefund=income&&selected?.account_type==="expense";
  const title=transaction.display_name||transaction.counterparty_name||transaction.description||(transaction.suggestion_kind==="refund_candidate"?(fr?"Remboursement fournisseur possible":"Possible supplier refund"):income?(fr?"Encaissement":"Income transaction"):(fr?"Décaissement":"Expense transaction"));
  const confidence=transaction.suggestion_confidence==null?null:Math.round(Number(transaction.suggestion_confidence)*100);
  return <article className={styles.card}>
    <div className={styles.top}><div><p className={styles.eyebrow}>{fr?"À vérifier maintenant":"Next to review"}</p><h2>{title}</h2><div className={styles.sub}><span>{new Date(`${transaction.occurred_on}T12:00:00`).toLocaleDateString(fr?"fr-LU":"en-LU",{day:"2-digit",month:"long",year:"numeric"})}</span>{transaction.description&&transaction.description!==title?<span>· {transaction.description}</span>:null}</div></div><div className={`${styles.amount} ${income?styles.income:styles.expense}`}>{income?<ArrowUpRight size={15}/>:<ArrowDownLeft size={15}/>} {income?"+":"−"}{money(gross,transaction.currency)}</div></div>
    {suggested?<div className={styles.suggestion}><Sparkles size={15}/><div><strong>{fr?"Suggestion Zuelen":"Zuelen suggestion"}: {groupLabel(suggested,fr)} · {suggested.code}</strong><p>{suggested.label}{confidence!==null?` · ${confidence}%`:""}{transaction.suggestion_reason?` · ${transaction.suggestion_reason}`:""}</p></div><button type="button" className={styles.useSuggestion} onClick={()=>setAccountCode(suggested.code)}>{fr?"Utiliser":"Use"}</button></div>:null}
    <div className={styles.meta}><div><span>Net</span><strong>{money(net,transaction.currency)}</strong></div><div><span>VAT</span><strong>{money(vat,transaction.currency)}</strong></div><div><span>{fr?"Règlement":"Settlement"}</span><strong>Bank · 5131</strong></div></div>
    <form action={formAction} className={styles.form}><input type="hidden" name="source_transaction_id" value={transaction.id}/><input type="hidden" name="account_code" value={accountCode}/>
      <div className={styles.question}><strong>{fr?"À quoi correspondait cette transaction ?":"What was this transaction for?"}</strong><span>{fr?"Décrivez-la avec vos propres mots. Zuelen recherche ensuite la catégorie appropriée dans le PCN luxembourgeois complet.":"Describe it in your own words. Zuelen searches the full Luxembourg PCN and shows the most relevant accounting categories."}</span></div>
      <div className={styles.searchWrap}><Search size={16} style={{position:"absolute",left:14,top:16,color:"var(--z-text-secondary)"}}/><input className={styles.search} style={{paddingLeft:40}} value={purpose} onChange={event=>setPurpose(event.target.value)} placeholder={fr?"Ex. hébergement web, publicité Facebook, paiement client…":"e.g. website hosting, Facebook ads, client payment…"}/></div>
      {results.length?<div className={styles.results}>{results.map(account=><button type="button" className={`${styles.result} ${account.code===accountCode?styles.resultActive:""}`} key={account.id} onClick={()=>{setAccountCode(account.code);setPurpose(account.label)}}><div><strong>{account.label}</strong><small>{fr?"Compte PCN officiel":"Official PCN account"} · {account.code}</small></div><span className={styles.crumb}>{groupLabel(account,fr)} &gt; {account.code}</span></button>)}</div>:purpose.trim().length>=2?<div className={styles.hint}>{fr?"Aucun résultat direct. Essayez un terme plus simple, un nom de fournisseur ou un code PCN.":"No direct match yet. Try a simpler business purpose, merchant name, or PCN code."}</div>:<div className={styles.hint}>{fr?"Vous pouvez rechercher par activité, fournisseur, mot-clé ou code PCN.":"Search by business purpose, merchant, keyword, or PCN code."}</div>}
      {selected?<div className={styles.selected}><div><strong>{groupLabel(selected,fr)} · {selected.code}</strong><small>{selected.label}</small></div><button type="button" className={styles.clear} onClick={()=>setAccountCode("")}><X size={14}/> {fr?"Changer":"Change"}</button></div>:null}
      {selected?<div className={styles.preview}><div className={styles.previewHead}><Landmark size={14}/><span>{fr?"Aperçu comptable":"Posting preview"}</span><small>{isExpenseRefund?(fr?"Remboursement fournisseur":"Supplier refund"):["asset","liability"].includes(selected.account_type)?(fr?"Bilan":"Balance sheet"):selected.account_type==="expense"?(fr?"Charge":"P&L expense"):(fr?"Produit":"P&L revenue")}</small></div>{income?<><div className={styles.line}><span><b>5131</b> Bank</span><strong>Dr {money(gross,transaction.currency)}</strong></div><div className={styles.line}><span><b>{selected.code}</b> {selected.label}</span><strong>Cr {money(net,transaction.currency)}</strong></div>{vat>0?<div className={styles.line}><span><b>{isExpenseRefund?"421611":"461411"}</b> {isExpenseRefund?"Input VAT reversal":"Output VAT"}</span><strong>Cr {money(vat,transaction.currency)}</strong></div>:null}</>:<><div className={styles.line}><span><b>{selected.code}</b> {selected.label}</span><strong>Dr {money(net,transaction.currency)}</strong></div>{vat>0?<div className={styles.line}><span><b>421611</b> Input VAT</span><strong>Dr {money(vat,transaction.currency)}</strong></div>:null}<div className={styles.line}><span><b>5131</b> Bank</span><strong>Cr {money(gross,transaction.currency)}</strong></div></>}<div className={styles.balance}><CheckCircle2 size={13}/>{fr?"Débits et crédits équilibrés":"Debits and credits balance"} · {money(gross,transaction.currency)}</div></div>:null}
      {state.message?<div className={`${styles.message} ${state.status==="error"?styles.error:""}`}>{state.message}</div>:null}<button className={styles.submit} type="submit" disabled={pending||!selected}>{pending?<LoaderCircle className={styles.spin} size={15}/>:<LockKeyhole size={15}/>}<span>{pending?(fr?"Comptabilisation…":"Posting…"):(fr?"Comptabiliser":"Post to ledger")}</span></button>
    </form>
  </article>;
}
