"use server";

import { revalidatePath } from "next/cache";
import { fiscalYearBounds, getActiveFiscalYear } from "@/lib/fiscal-year";
import { localizedAccountLabel, normalizeLocale, type AccountTranslation } from "@/lib/i18n";
import { createClient } from "@/lib/supabase/server";
import { getWorkspace } from "@/lib/workspace";
import { assertActionRateLimit, localizedRateLimitMessage, SecurityRateLimitError } from "@/lib/rate-limit";
import { userFacingDataError } from "@/lib/user-facing-error";
export type CopilotState={status:"idle"|"success"|"error";message:string;answer?:string;conversationId?:string};
function validUuid(value:string){return /^[0-9a-f-]{36}$/i.test(value)}
function readResponse(payload:unknown){if(!payload||typeof payload!=="object")return{text:"",refusal:"",status:"unknown",reason:""};const root=payload as{output?:unknown[];status?:string;incomplete_details?:{reason?:string}};const texts:string[]=[],refusals:string[]=[];for(const item of root.output??[]){if(!item||typeof item!=="object")continue;for(const part of (item as{content?:unknown[]}).content??[]){if(!part||typeof part!=="object")continue;const p=part as{type?:string;text?:unknown;refusal?:unknown};if(p.type==="output_text"&&typeof p.text==="string"&&p.text.trim())texts.push(p.text.trim());if(p.type==="refusal"&&typeof p.refusal==="string")refusals.push(p.refusal)}}return{text:texts.join("\n\n"),refusal:refusals.join("\n\n"),status:root.status??"unknown",reason:root.incomplete_details?.reason??""}}

export async function askCopilot(_previous:CopilotState,formData:FormData):Promise<CopilotState>{
 const w=await getWorkspace(),locale=normalizeLocale(w.profile?.locale),fr=locale==="fr";if(!w.authenticated||!w.userId||!w.organization||!w.company)return{status:"error",message:fr?"Votre session a expiré.":"Your session expired."};const question=String(formData.get("question")??"").trim(),requestedConversation=String(formData.get("conversation_id")??"").trim();if(question.length<3)return{status:"error",message:fr?"Posez d’abord une question à Zuelen.":"Ask Zuelen a question first."};if(question.length>2000)return{status:"error",message:fr?"Limitez la question à 2 000 caractères.":"Keep the question under 2,000 characters."};const key=process.env.OPENAI_API_KEY;if(!key)return{status:"error",message:fr?"Le Copilot IA n’est pas configuré sur ce déploiement.":"AI Copilot is not configured on this deployment."};
 const s=await createClient();try{await assertActionRateLimit(s,"copilot")}catch(error){return{status:"error",message:error instanceof SecurityRateLimitError?localizedRateLimitMessage(locale,error.retryAfterSeconds):(fr?"La vérification de sécurité n’a pas pu être effectuée.":"The security check could not be completed.")}}const year=await getActiveFiscalYear(w.company.fiscal_year_start_month),bounds=fiscalYearBounds(year,w.company.fiscal_year_start_month),from=bounds.start,to=bounds.end,independent=w.company.entity_kind==="independent";let conversationId:string|undefined,history:Array<{role:string;content:string}>=[];
 if(requestedConversation&&validUuid(requestedConversation)){const{data:conversation}=await s.from("copilot_conversations").select("id").eq("id",requestedConversation).eq("company_id",w.company.id).eq("created_by",w.userId).maybeSingle();if(conversation){conversationId=conversation.id;const{data:historyRows}=await s.from("copilot_messages").select("role,content").eq("conversation_id",conversation.id).order("created_at",{ascending:true}).limit(30);history=(historyRows??[]) as Array<{role:string;content:string}>}}
 const[tx,entries,accounts,invoices,compliance,docs,filings,taxProfile,taxEvents,rules,docLinks,periods]=await Promise.all([
  s.from("source_transactions").select("id,occurred_on,direction,amount_gross,amount_net,vat_amount,vat_rate,currency,counterparty_name,description,classification_status,suggestion_reason,suggestion_kind,transaction_kind,vat_treatment,counterparty_country,posted_journal_entry_id").eq("company_id",w.company.id).gte("occurred_on",from).lte("occurred_on",to).order("occurred_on",{ascending:false}).limit(300),
  s.from("journal_entries").select("id,entry_number,entry_date,description,status,source_type,source_id").eq("company_id",w.company.id).eq("status","posted").gte("entry_date",from).lte("entry_date",to),
  s.from("company_accounts").select("id,code,label,label_en,label_fr,account_type").eq("company_id",w.company.id).eq("is_active",true),
  s.from("sales_invoices").select("id,invoice_number,issue_date,service_date,due_date,status,payment_status,subtotal,vat_total,total,currency,customer_snapshot,vat_treatment,paid_at").eq("company_id",w.company.id).gte("service_date",from).lte("service_date",to).order("service_date",{ascending:false}).limit(120),
  s.from("compliance_obligations").select("id,authority,obligation_type,period_label,due_date,amount,status,rule_key,metadata").eq("company_id",w.company.id).eq("period_label",String(year)).order("due_date",{ascending:true}).limit(100),
  s.from("documents").select("id,type,file_name,extraction_status,extracted_data,created_at").eq("company_id",w.company.id).order("created_at",{ascending:false}).limit(100),
  s.from("filings").select("id,filing_type,period_label,status,schema_version,rules_version,snapshot_at,export_status,payload,ledger_checksum,period_start,period_end").eq("company_id",w.company.id).eq("period_label",String(year)).order("created_at",{ascending:false}).limit(30),
  independent?Promise.resolve({data:null,error:null}):s.from("company_tax_profiles").select("municipality,icc_multiplier,icc_multiplier_year,prior_closing_balance_total,prior_balance_year").eq("company_id",w.company.id).maybeSingle(),
  s.from("tax_events").select("id,authority,tax_type,tax_year,amount,due_date,reference,status,bank_transaction_id,source_document_id").eq("company_id",w.company.id).or(`tax_year.eq.${year},tax_year.is.null`).order("due_date",{ascending:true}),
  s.from("classification_rules").select("normalized_counterparty,direction,vat_treatment,vat_rate,counterparty_country,times_confirmed,company_account_id").eq("company_id",w.company.id).order("times_confirmed",{ascending:false}).limit(80),
  s.from("document_transaction_links").select("document_id,source_transaction_id,bank_transaction_id,sales_invoice_id,match_score,status,match_reason").eq("company_id",w.company.id).eq("status","confirmed").limit(150),
  s.from("accounting_periods").select("starts_on,ends_on,status,locked_at").eq("company_id",w.company.id).eq("starts_on",from).eq("ends_on",to)
 ]);
 const localizedAccounts=(accounts.data??[]).map(a=>({...a,label:localizedAccountLabel(locale,a as AccountTranslation)})),accountMap=new Map(localizedAccounts.map(a=>[a.id,a]));const entryIds=(entries.data??[]).map(e=>e.id),ledger:Record<string,{code:string;label:string;type:string;debit:number;credit:number;balance:number}>={};if(entryIds.length){const{data:lines}=await s.from("journal_lines").select("journal_entry_id,company_account_id,debit,credit,vat_code,vat_rate,vat_amount").in("journal_entry_id",entryIds);for(const line of lines??[]){const a=accountMap.get(line.company_account_id);if(!a)continue;const r=ledger[a.code]??{code:a.code,label:a.label,type:a.account_type,debit:0,credit:0,balance:0};r.debit+=Number(line.debit);r.credit+=Number(line.credit);r.balance=Number((r.debit-r.credit).toFixed(2));ledger[a.code]=r}}
 const context={language:locale,workspace:{entity_kind:w.company.entity_kind,display_name:w.company.trading_name||w.company.legal_name},company:{legal_name:w.company.legal_name,legal_form:w.company.legal_form,municipality:w.company.municipality,vat_registered:w.company.vat_registered,vat_frequency:w.company.vat_filing_frequency,base_currency:w.company.base_currency},period:{active_financial_year:year,period_start:from,period_end:to,accounting_periods:periods.data??[]},ledger:Object.values(ledger),transactions:tx.data??[],invoices:invoices.data??[],compliance:compliance.data??[],documents:(docs.data??[]).map(d=>({id:d.id,type:d.type,file_name:d.file_name,status:d.extraction_status,extracted_data:d.extracted_data})),confirmed_document_links:docLinks.data??[],filings:filings.data??[],tax_events:taxEvents.data??[],learned_classification_rules:(rules.data??[]).map(r=>({...r,account:accountMap.get(r.company_account_id)??null})),corporate_tax_profile:taxProfile.data??null};
 const languageInstruction=fr?"Réponds en français clair et professionnel. Conserve les codes PCN, références, noms propres et valeurs tels qu’ils figurent dans les données. Utilise la terminologie comptable luxembourgeoise en français. La ligne de provenance finale doit commencer par « Fondé sur les données Zuelen : ».":"Answer in clear professional English. Preserve PCN codes, references, proper names and values as supplied. The final provenance line must start with 'Grounded in Zuelen:'.";
 const entityInstruction=independent?"This is an Independent workspace for a natural person operating in their own name. Do not apply or suggest corporate IRC, ICC, net wealth tax, company annual accounts or eCDF workflows. Do not calculate a complete personal income-tax liability. Tax class is contextual and must never alter CCSS calculations.":"This is a Company workspace. Corporate tax and company annual-account workflows may apply only when supported by the supplied facts.";
 try{const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-5-mini",store:false,reasoning:{effort:"low"},input:[{role:"developer",content:[{type:"input_text",text:`You are Zuelen Copilot, a read-only Luxembourg accounting assistant. ${languageInstruction} ${entityInstruction} The user is currently working in financial year ${year}, covering ${from} to ${to}. Answer financial questions in that selected-year context unless the user explicitly asks about another period. Answer only from supplied workspace context plus cautious general accounting knowledge. Start with a short direct conclusion. Distinguish POSTED facts, DOCUMENT/NOTICE facts, PREPARED FILING SNAPSHOTS, and ESTIMATES. Never say a filing was submitted merely because a draft/snapshot exists. Never invent legal deadlines, tax rates, missing documents or authority acceptance. Use conversation history only for follow-up references; current workspace context is the source of truth for numbers. When supported by specific records, end with the required compact provenance line naming relevant records. If evidence is missing, say what should be uploaded/reviewed. You cannot modify books.`}]},{role:"user",content:[{type:"input_text",text:`WORKSPACE CONTEXT\n${JSON.stringify(context)}\n\nCONVERSATION HISTORY\n${JSON.stringify(history)}\n\nCURRENT QUESTION\n${question}`}]}],max_output_tokens:2400})});const payload=await response.json();if(!response.ok)throw new Error(payload&&typeof payload==="object"&&"error" in payload?String((payload as{error?:{message?:string}}).error?.message??(fr?"La requête Copilot a échoué.":"Copilot request failed.")):(fr?"La requête Copilot a échoué.":"Copilot request failed."));const result=readResponse(payload);if(result.refusal)return{status:"error",message:result.refusal};if(!result.text){if(result.status==="incomplete")throw new Error(fr?`La réponse Copilot est incomplète${result.reason?` (${result.reason})`:""}. Réessayez.`:`Copilot response was incomplete${result.reason?` (${result.reason})`:""}. Please try again.`);throw new Error(fr?"Copilot a terminé sans produire de texte. Réessayez.":"Copilot completed without text output. Please try again.")}
  if(!conversationId){const title=question.length>58?`${question.slice(0,55)}…`:question;const{data:created,error:createError}=await s.from("copilot_conversations").insert({organization_id:w.organization.id,company_id:w.company.id,created_by:w.userId,title}).select("id").single();if(createError)throw new Error(`${fr?"Réponse générée, mais l’historique n’a pas pu être enregistré":"Answer generated, but chat history could not be saved"}: ${userFacingDataError(createError)}`);conversationId=created.id}
  const{error:messageError}=await s.from("copilot_messages").insert([{conversation_id:conversationId,organization_id:w.organization.id,company_id:w.company.id,created_by:w.userId,role:"user",content:question},{conversation_id:conversationId,organization_id:w.organization.id,company_id:w.company.id,created_by:w.userId,role:"assistant",content:result.text}]);if(messageError)throw new Error(`${fr?"Réponse générée, mais l’historique n’a pas pu être enregistré":"Answer generated, but chat history could not be saved"}: ${userFacingDataError(messageError)}`);await s.from("copilot_conversations").update({updated_at:new Date().toISOString()}).eq("id",conversationId);revalidatePath("/app/copilot");return{status:"success",message:"",answer:result.text,conversationId};
 }catch(e){return{status:"error",message:userFacingDataError(e,fr?"Copilot ne peut pas répondre pour le moment.":"Copilot could not answer right now.",locale)}}
}
