"use server";

import { createClient } from "@/lib/supabase/server";
import { getWorkspace } from "@/lib/workspace";
export type CopilotState={status:"idle"|"success"|"error";message:string;answer?:string};
function readResponse(payload:unknown){if(!payload||typeof payload!=="object")return{text:"",refusal:"",status:"unknown",reason:""};const root=payload as {output?:unknown[];status?:string;incomplete_details?:{reason?:string}};const texts:string[]=[],refusals:string[]=[];if(Array.isArray(root.output)){for(const item of root.output){if(!item||typeof item!=="object")continue;const content=(item as {content?:unknown[]}).content;if(!Array.isArray(content))continue;for(const part of content){if(!part||typeof part!=="object")continue;const p=part as {type?:string;text?:unknown;refusal?:unknown};if(p.type==="output_text"&&typeof p.text==="string"&&p.text.trim())texts.push(p.text.trim());if(p.type==="refusal"&&typeof p.refusal==="string"&&p.refusal.trim())refusals.push(p.refusal.trim())}}}return{text:texts.join("\n\n"),refusal:refusals.join("\n\n"),status:root.status??"unknown",reason:root.incomplete_details?.reason??""}}
export async function askCopilot(_previous:CopilotState,formData:FormData):Promise<CopilotState>{const w=await getWorkspace();if(!w.authenticated||!w.company)return{status:"error",message:"Your session expired."};const question=String(formData.get("question")??"").trim();if(question.length<3)return{status:"error",message:"Ask Compta a question first."};if(question.length>2000)return{status:"error",message:"Keep the question under 2,000 characters."};const key=process.env.OPENAI_API_KEY;if(!key)return{status:"error",message:"AI Copilot is not configured on this deployment."};const s=await createClient(),year=new Date().getFullYear(),from=`${year}-01-01`,to=`${year}-12-31`;
 const [tx,entries,accounts,invoices,compliance,docs,filings,taxProfile]=await Promise.all([
  s.from("source_transactions").select("occurred_on,direction,amount_gross,amount_net,vat_amount,currency,counterparty_name,description,classification_status,suggestion_reason,transaction_kind,vat_treatment,counterparty_country").eq("company_id",w.company.id).gte("occurred_on",from).lte("occurred_on",to).order("occurred_on",{ascending:false}).limit(120),
  s.from("journal_entries").select("id,entry_date,description,status").eq("company_id",w.company.id).eq("status","posted").gte("entry_date",from).lte("entry_date",to),
  s.from("company_accounts").select("id,code,label,account_type").eq("company_id",w.company.id).eq("is_active",true),
  s.from("sales_invoices").select("invoice_number,issue_date,due_date,status,payment_status,subtotal,vat_total,total,currency,customer_snapshot,vat_treatment").eq("company_id",w.company.id).order("issue_date",{ascending:false}).limit(50),
  s.from("compliance_obligations").select("authority,obligation_type,period_label,due_date,amount,status,rule_key,metadata").eq("company_id",w.company.id).order("due_date",{ascending:true}).limit(80),
  s.from("documents").select("type,file_name,extraction_status,extracted_data,created_at").eq("company_id",w.company.id).order("created_at",{ascending:false}).limit(30),
  s.from("filings").select("filing_type,period_label,status,schema_version,rules_version,snapshot_at,export_status,payload").eq("company_id",w.company.id).order("created_at",{ascending:false}).limit(10),
  s.from("company_tax_profiles").select("municipality,icc_multiplier,icc_multiplier_year,prior_closing_balance_total,prior_balance_year").eq("company_id",w.company.id).maybeSingle()
 ]);
 const accountMap=new Map((accounts.data??[]).map(a=>[a.id,a]));const entryIds=(entries.data??[]).map(e=>e.id);const ledger:Record<string,{code:string;label:string;type:string;debit:number;credit:number;balance:number}>={};if(entryIds.length){const{data:lines}=await s.from("journal_lines").select("company_account_id,debit,credit").in("journal_entry_id",entryIds);for(const line of lines??[]){const a=accountMap.get(line.company_account_id);if(!a)continue;const r=ledger[a.code]??{code:a.code,label:a.label,type:a.account_type,debit:0,credit:0,balance:0};r.debit+=Number(line.debit);r.credit+=Number(line.credit);r.balance=Number((r.debit-r.credit).toFixed(2));ledger[a.code]=r}}
 const context={company:{legal_name:w.company.legal_name,legal_form:w.company.legal_form,municipality:w.company.municipality,vat_registered:w.company.vat_registered,vat_frequency:w.company.vat_filing_frequency,base_currency:w.company.base_currency},period:{year},ledger:Object.values(ledger),transactions:tx.data??[],invoices:invoices.data??[],compliance:compliance.data??[],documents:(docs.data??[]).map(d=>({type:d.type,file_name:d.file_name,status:d.extraction_status,extracted_data:d.extracted_data})),filings:filings.data??[],tax_profile:taxProfile.data??null};
 try{const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-5-mini",store:false,reasoning:{effort:"low"},input:[{role:"developer",content:[{type:"input_text",text:"You are Compta Copilot, a read-only Luxembourg business assistant for owners who are not accountants. Answer only from supplied company context and cautious general accounting knowledge. Start with the conclusion in plain everyday language. Never lead with PCN codes, debit/credit terminology, account types, or a list of relevant accounts unless the user explicitly asks for accounting detail. Use this exact order: (1) a short direct answer of no more than 3 sentences; (2) a simple numbers breakdown when useful; (3) one practical next step in Compta. For a shareholder-current-account question, say plainly who owes whom, then show money added minus money taken out. Do not expose contradictory raw account balances when a clear net position can be derived; mention a possible mapping issue only as a brief warning. Keep the default response under 180 words. If the user asks for detail, then explain PCN and journal logic. Never claim a filing was submitted unless context says so. Never invent missing notices, evidence, rates, or facts. Clearly distinguish posted facts from estimates. You cannot modify books."}]},{role:"user",content:[{type:"input_text",text:`COMPANY CONTEXT\n${JSON.stringify(context)}\n\nUSER QUESTION\n${question}`}]}],max_output_tokens:2400})});const payload=await response.json();if(!response.ok)throw new Error(payload&&typeof payload==="object"&&"error" in payload?String((payload as {error?:{message?:string}}).error?.message??"Copilot request failed."):"Copilot request failed.");const result=readResponse(payload);if(result.text)return{status:"success",message:"",answer:result.text};if(result.refusal)return{status:"error",message:result.refusal};if(result.status==="incomplete")throw new Error(`Copilot response was incomplete${result.reason?` (${result.reason})`:""}. Please try again.`);throw new Error("Copilot completed without text output. Please try again.")}catch(e){return{status:"error",message:e instanceof Error?e.message:"Copilot could not answer right now."}}
}
