"use server";

import { createClient } from "@/lib/supabase/server";
import { getWorkspace } from "@/lib/workspace";
export type CopilotState={status:"idle"|"success"|"error";message:string;answer?:string};
function outputText(payload:unknown){if(!payload||typeof payload!=="object")return null;const output=(payload as {output?:unknown[]}).output;if(!Array.isArray(output))return null;for(const item of output){if(!item||typeof item!=="object")continue;const content=(item as {content?:unknown[]}).content;if(!Array.isArray(content))continue;for(const p of content){if(p&&typeof p==="object"&&(p as {type?:string}).type==="output_text"&&typeof(p as {text?:unknown}).text==="string")return(p as {text:string}).text}}return null}
export async function askCopilot(_previous:CopilotState,formData:FormData):Promise<CopilotState>{const w=await getWorkspace();if(!w.authenticated||!w.company)return{status:"error",message:"Your session expired."};const question=String(formData.get("question")??"").trim();if(question.length<3)return{status:"error",message:"Ask Compta a question first."};if(question.length>2000)return{status:"error",message:"Keep the question under 2,000 characters."};const key=process.env.OPENAI_API_KEY;if(!key)return{status:"error",message:"AI Copilot is not configured on this deployment."};const s=await createClient(),year=new Date().getFullYear(),from=`${year}-01-01`,to=`${year}-12-31`;
 const [tx,entries,accounts,invoices,compliance,docs,filings,taxProfile]=await Promise.all([
  s.from("source_transactions").select("occurred_on,direction,amount_gross,amount_net,vat_amount,currency,counterparty_name,description,classification_status,suggestion_reason,transaction_kind,vat_treatment,counterparty_country").eq("company_id",w.company.id).gte("occurred_on",from).lte("occurred_on",to).order("occurred_on",{ascending:false}).limit(120),
  s.from("journal_entries").select("id,entry_date,description,status").eq("company_id",w.company.id).eq("status","posted").gte("entry_date",from).lte("entry_date",to),
  s.from("company_accounts").select("id,code,label,account_type").eq("company_id",w.company.id).eq("is_active",true),
  s.from("sales_invoices").select("invoice_number,issue_date,due_date,status,payment_status,subtotal,vat_total,total,currency,customer_snapshot,vat_treatment").eq("company_id",w.company.id).order("issue_date",{ascending:false}).limit(50),
  s.from("compliance_obligations").select("authority,obligation_type,period_label,due_date,amount,status,rule_key,metadata").eq("company_id",w.company.id).order("due_date",{ascending:true}).limit(80),
  s.from("documents").select("type,file_name,extraction_status,extracted_data,created_at").eq("company_id",w.company.id).order("created_at",{ascending:false}).limit(30),
  s.from("filings").select("filing_type,period_label,status,schema_version,rules_version,snapshot_at,export_status,payload").eq("company_id",w.company.id).order("created_at",{ascending:false}).limit(10),
  s.from("company_tax_profiles").select("municipality,icc_multiplier,icc_multiplier_year,prior_closing_balance_total,prior_balance_year").eq("company_id",w.company.id).maybeSingle()
 ]);
 const accountMap=new Map((accounts.data??[]).map(a=>[a.id,a]));const entryIds=(entries.data??[]).map(e=>e.id);const ledger:Record<string,{code:string;label:string;type:string;debit:number;credit:number}>={};if(entryIds.length){const{data:lines}=await s.from("journal_lines").select("company_account_id,debit,credit").in("journal_entry_id",entryIds);for(const line of lines??[]){const a=accountMap.get(line.company_account_id);if(!a)continue;const r=ledger[a.code]??{code:a.code,label:a.label,type:a.account_type,debit:0,credit:0};r.debit+=Number(line.debit);r.credit+=Number(line.credit);ledger[a.code]=r}}
 const context={company:{legal_name:w.company.legal_name,legal_form:w.company.legal_form,municipality:w.company.municipality,vat_registered:w.company.vat_registered,vat_frequency:w.company.vat_filing_frequency,base_currency:w.company.base_currency},period:{year},ledger:Object.values(ledger),transactions:tx.data??[],invoices:invoices.data??[],compliance:compliance.data??[],documents:(docs.data??[]).map(d=>({type:d.type,file_name:d.file_name,status:d.extraction_status,extracted_data:d.extracted_data})),filings:filings.data??[],tax_profile:taxProfile.data??null};
 try{const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${key}`,"Content-Type":"application/json"},body:JSON.stringify({model:"gpt-5-mini",input:[{role:"developer",content:[{type:"input_text",text:"You are Compta Copilot, a read-only Luxembourg business accounting assistant. Answer only from the supplied company context plus cautious general accounting explanations. Never claim that a filing was submitted unless context says so. Never invent missing tax notices, VAT evidence, municipality rates, or transaction facts. Clearly distinguish posted ledger facts, estimates, and suggestions. You cannot modify books; when an action is needed, tell the user which Compta workspace to use. Keep answers concise and practical. Refer to evidence naturally as Ledger, Transactions, Invoices, Documents, Compliance, Filing snapshot, or Tax profile."}]},{role:"user",content:[{type:"input_text",text:`COMPANY CONTEXT\n${JSON.stringify(context)}\n\nUSER QUESTION\n${question}`}]}],max_output_tokens:1200})});const payload=await response.json();if(!response.ok)throw new Error(payload&&typeof payload==="object"&&"error" in payload?String((payload as {error?:{message?:string}}).error?.message??"Copilot request failed."):"Copilot request failed.");const answer=outputText(payload);if(!answer)throw new Error("Copilot returned no answer.");return{status:"success",message:"",answer}}catch(e){return{status:"error",message:e instanceof Error?e.message:"Copilot could not answer right now."}}
}
