import { BarChart3, Scale, TrendingDown, TrendingUp } from "lucide-react";
import { redirect } from "next/navigation";
import styles from "@/components/reports.module.css";
import { fiscalYearBounds, getActiveFiscalYear } from "@/lib/fiscal-year";
import { createClient } from "@/lib/supabase/server";
import { getWorkspace } from "@/lib/workspace";

export const dynamic="force-dynamic";
function money(v:number,c:string){return new Intl.NumberFormat("en-LU",{style:"currency",currency:c,minimumFractionDigits:2}).format(v)}
const chartColors=["#b3de01","#7fa000","#55750a","#344b0d","#9eb96c","#c7d69f"];
function donut(items:{value:number}[],total:number){if(total<=0)return"conic-gradient(#e6e9e2 0 100%)";let cursor=0;const stops=items.map((item,index)=>{const start=cursor,end=cursor+item.value/total*100;cursor=end;return`${chartColors[index%chartColors.length]} ${start}% ${end}%`});if(cursor<100)stops.push(`#e9ece6 ${cursor}% 100%`);return`conic-gradient(${stops.join(",")})`}

export default async function ReportsPage(){
 const workspace=await getWorkspace();if(!workspace.authenticated)redirect("/sign-in");if(!workspace.company)redirect("/setup");
 const year=await getActiveFiscalYear(workspace.company.fiscal_year_start_month),bounds=fiscalYearBounds(year,workspace.company.fiscal_year_start_month),currency=workspace.company.base_currency||"EUR",supabase=await createClient();
 const[{data:entries,error:e1},{data:accounts,error:e2},{data:incomeSources,error:e3}]=await Promise.all([
  supabase.from("journal_entries").select("id,entry_date,source_type,description").eq("company_id",workspace.company.id).eq("status","posted").gte("entry_date",bounds.start).lte("entry_date",bounds.end),
  supabase.from("company_accounts").select("id,code,label,account_type").eq("company_id",workspace.company.id).eq("is_active",true).order("code"),
  supabase.from("source_transactions").select("counterparty_name,amount_net,amount_gross").eq("company_id",workspace.company.id).eq("classification_status","posted").eq("direction","income").gte("occurred_on",bounds.start).lte("occurred_on",bounds.end)
 ]);if(e1||e2||e3)throw new Error("Could not load financial reports.");
 const entryIds=(entries??[]).map(e=>e.id),lines=entryIds.length?(await supabase.from("journal_lines").select("journal_entry_id,company_account_id,debit,credit").in("journal_entry_id",entryIds)).data??[]:[],accountMap=new Map((accounts??[]).map(a=>[a.id,a])),dateMap=new Map((entries??[]).map(e=>[e.id,e.entry_date])),sums=new Map<string,{debit:number;credit:number}>(),monthly=Array.from({length:12},(_,i)=>({label:new Date(Date.UTC(year,i,1)).toLocaleDateString("en-LU",{month:"short",timeZone:"UTC"}).slice(0,3),revenue:0,expense:0}));
 for(const line of lines){const prev=sums.get(line.company_account_id)??{debit:0,credit:0};prev.debit+=Number(line.debit);prev.credit+=Number(line.credit);sums.set(line.company_account_id,prev);const account=accountMap.get(line.company_account_id),date=dateMap.get(line.journal_entry_id),month=date?Number(date.slice(5,7))-1:-1;if(account&&month>=0&&month<12){if(account.account_type==="revenue")monthly[month].revenue+=Number(line.credit)-Number(line.debit);if(account.account_type==="expense")monthly[month].expense+=Number(line.debit)-Number(line.credit)}}
 const rows=(accounts??[]).map(a=>{const s=sums.get(a.id)??{debit:0,credit:0};return{...a,debit:s.debit,credit:s.credit}}).filter(r=>Math.abs(r.debit-r.credit)>.004||r.debit>0||r.credit>0),revenues=rows.filter(r=>r.account_type==="revenue").map(r=>({...r,balance:r.credit-r.debit})).filter(r=>Math.abs(r.balance)>.004),expenses=rows.filter(r=>r.account_type==="expense").map(r=>({...r,balance:r.debit-r.credit})).filter(r=>Math.abs(r.balance)>.004),revenueTotal=revenues.reduce((s,r)=>s+r.balance,0),expenseTotal=expenses.reduce((s,r)=>s+r.balance,0),result=revenueTotal-expenseTotal,margin=revenueTotal?result/revenueTotal*100:0;
 const assets=rows.filter(r=>r.account_type==="asset").map(r=>({...r,balance:r.debit-r.credit})).filter(r=>Math.abs(r.balance)>.004),liabs=rows.filter(r=>["liability","equity"].includes(r.account_type)).map(r=>({...r,balance:r.credit-r.debit})).filter(r=>Math.abs(r.balance)>.004),assetTotal=assets.reduce((s,r)=>s+r.balance,0),liabTotal=liabs.reduce((s,r)=>s+r.balance,0),balanceGap=assetTotal-(liabTotal+result),openingFound=(entries??[]).some(entry=>entry.source_type==="import"&&entry.description===`Opening balances · ${year}`);
 const monthResults=monthly.map((m,index)=>({...m,index,result:m.revenue-m.expense})),activeMonths=monthResults.filter(m=>m.revenue||m.expense),best=activeMonths.length?activeMonths.reduce((a,b)=>b.result>a.result?b:a):null,worst=activeMonths.length?activeMonths.reduce((a,b)=>b.result<a.result?b:a):null,chartMax=Math.max(1,...monthly.flatMap(m=>[m.revenue,m.expense]));
 const expenseMix=[...expenses].sort((a,b)=>b.balance-a.balance).slice(0,6).map(r=>({label:r.label,value:Math.max(0,r.balance),code:r.code})),expenseMixTotal=expenseMix.reduce((s,r)=>s+r.value,0),sourceMap=new Map<string,number>();for(const row of incomeSources??[]){const name=(row.counterparty_name||"Other income").trim()||"Other income",value=Number(row.amount_net??row.amount_gross??0);sourceMap.set(name,(sourceMap.get(name)??0)+value)}const revenueSources=[...sourceMap.entries()].map(([label,value])=>({label,value})).sort((a,b)=>b.value-a.value).slice(0,6),revenueSourceTotal=revenueSources.reduce((s,r)=>s+r.value,0);
 return <div className={styles.page}>
  <div className={styles.intro}><div><p>Financial intelligence · FY {year}</p><h1>Understand the year, not just the ledger.</h1><span>Performance analytics come from posted journal entries between {bounds.start} and {bounds.end}. Accounting detail remains available below when you need to trace a figure.</span></div><div className={styles.badge}>{entryIds.length} posted entries</div></div>
  <section className={styles.metrics}><article><BarChart3/><span>Revenue</span><strong>{money(revenueTotal,currency)}</strong></article><article><Scale/><span>Expenses</span><strong>{money(expenseTotal,currency)}</strong></article><article className={result>=0?styles.good:styles.bad}><TrendingUp/><span>Net result</span><strong>{money(result,currency)}</strong></article><article className={margin>=0?styles.good:styles.bad}><span>Net margin</span><strong>{margin.toFixed(1)}%</strong></article></section>
  {!openingFound&&entryIds.length?<div className={styles.warning}>The P&amp;L is usable, but the balance sheet is provisional until FY {year} has an opening-balance entry from the prior-year closing position.</div>:null}
  <section className={styles.analyticsGrid}>
   <article className={`${styles.analyticsCard} ${styles.monthlyCard}`}><div className={styles.head}><div><p>Monthly performance · {year}</p><h2>Revenue vs. expenses</h2></div><strong>{money(result,currency)} result</strong></div><div className={styles.monthInsights}><div><TrendingUp/><span>Best month</span><strong>{best?`${best.label} · ${money(best.result,currency)}`:"—"}</strong></div><div><TrendingDown/><span>Weakest month</span><strong>{worst?`${worst.label} · ${money(worst.result,currency)}`:"—"}</strong></div></div><div className={styles.monthChart}>{monthly.map(m=><div className={styles.monthCol} key={m.label}><div className={styles.monthBars}><i className={styles.revBar} style={{height:`${Math.max(m.revenue?4:0,m.revenue/chartMax*100)}%`}}/><i className={styles.expBar} style={{height:`${Math.max(m.expense?4:0,m.expense/chartMax*100)}%`}}/></div><small>{m.label}</small></div>)}</div><div className={styles.chartLegend}><span><i className={styles.revLegend}/>Revenue</span><span><i className={styles.expLegend}/>Expenses</span></div></article>
   <article className={styles.analyticsCard}><div className={styles.head}><div><p>Spend mix</p><h2>Where money went</h2></div></div><div className={styles.donutLayout}><div className={styles.donut} style={{background:donut(expenseMix,expenseMixTotal)}}><span><strong>{money(expenseTotal,currency)}</strong><small>Total expenses</small></span></div><div className={styles.mixList}>{expenseMix.map((r,i)=><div key={r.code}><i style={{background:chartColors[i%chartColors.length]}}/><span title={r.label}>{r.label}</span><strong>{expenseTotal?`${Math.round(r.value/expenseTotal*100)}%`:"0%"}</strong></div>)}</div></div></article>
   <article className={styles.analyticsCard}><div className={styles.head}><div><p>Revenue concentration</p><h2>Where revenue came from</h2></div></div><div className={styles.donutLayout}><div className={styles.donut} style={{background:donut(revenueSources,revenueSourceTotal)}}><span><strong>{revenueSources.length}</strong><small>Top sources</small></span></div><div className={styles.mixList}>{revenueSources.map((r,i)=><div key={r.label}><i style={{background:chartColors[i%chartColors.length]}}/><span title={r.label}>{r.label}</span><strong>{revenueSourceTotal?`${Math.round(r.value/revenueSourceTotal*100)}%`:"0%"}</strong></div>)}</div></div></article>
  </section>
  <section className={styles.grid}><article className={styles.card}><div className={styles.head}><div><p>Profit & loss · {year}</p><h2>Performance statement</h2></div><strong>{money(result,currency)}</strong></div><h3>Revenue</h3>{revenues.slice().sort((a,b)=>b.balance-a.balance).map(r=><div className={styles.row} key={r.id}><span><b>{r.code}</b>{r.label}</span><strong>{money(r.balance,currency)}</strong></div>)}<div className={styles.total}><span>Total revenue</span><strong>{money(revenueTotal,currency)}</strong></div><h3>Expenses</h3>{expenses.slice().sort((a,b)=>b.balance-a.balance).map(r=><div className={styles.row} key={r.id}><span><b>{r.code}</b>{r.label}</span><strong>{money(r.balance,currency)}</strong></div>)}<div className={styles.total}><span>Total expenses</span><strong>{money(expenseTotal,currency)}</strong></div><div className={styles.result}><span>Result for the year</span><strong>{money(result,currency)}</strong></div></article>
   <article className={styles.card}><div className={styles.head}><div><p>Balance sheet · {bounds.end}</p><h2>Financial position</h2></div><strong>{Math.abs(balanceGap)<.01?"Balanced":"Provisional"}</strong></div><h3>Assets</h3>{assets.map(r=><div className={styles.row} key={r.id}><span><b>{r.code}</b>{r.label}</span><strong>{money(r.balance,currency)}</strong></div>)}<div className={styles.total}><span>Total assets</span><strong>{money(assetTotal,currency)}</strong></div><h3>Liabilities & equity</h3>{liabs.map(r=><div className={styles.row} key={r.id}><span><b>{r.code}</b>{r.label}</span><strong>{money(r.balance,currency)}</strong></div>)}<div className={styles.row}><span><b>142*</b>Current-year result (computed)</span><strong>{money(result,currency)}</strong></div><div className={styles.total}><span>Liabilities + equity + result</span><strong>{money(liabTotal+result,currency)}</strong></div>{Math.abs(balanceGap)>=.01?<div className={styles.warning}>Balance-sheet gap {money(balanceGap,currency)}. Check the opening position, equity and any missing balance-sheet accounts before year-end.</div>:null}</article></section>
  <details className={styles.trial}><summary><div><p>Accounting detail · FY {year}</p><h2>Trial balance</h2><span>For accountants and reconciliation: debit, credit and balance for every active ledger account.</span></div><strong>{rows.length} active accounts</strong></summary><div className={styles.table}><div className={styles.th}><span>PCN</span><span>Account</span><span>Debit</span><span>Credit</span><span>Balance</span></div>{rows.map(r=><div className={styles.tr} key={r.id}><b>{r.code}</b><span>{r.label}</span><span>{money(r.debit,currency)}</span><span>{money(r.credit,currency)}</span><strong>{money(r.debit-r.credit,currency)}</strong></div>)}</div></details>
 </div>
}
