import { BarChart3, Scale, Table2 } from "lucide-react";
import { redirect } from "next/navigation";
import styles from "@/components/reports.module.css";
import { fiscalYearBounds, getActiveFiscalYear } from "@/lib/fiscal-year";
import { createClient } from "@/lib/supabase/server";
import { getWorkspace } from "@/lib/workspace";

export const dynamic="force-dynamic";
function money(v:number,c:string){return new Intl.NumberFormat("en-LU",{style:"currency",currency:c,minimumFractionDigits:2}).format(v)}
export default async function ReportsPage(){
 const workspace=await getWorkspace();if(!workspace.authenticated)redirect("/sign-in");if(!workspace.company)redirect("/setup");
 const year=await getActiveFiscalYear(workspace.company.fiscal_year_start_month),bounds=fiscalYearBounds(year,workspace.company.fiscal_year_start_month),currency=workspace.company.base_currency||"EUR",supabase=await createClient();
 const[{data:entries,error:e1},{data:accounts,error:e2}]=await Promise.all([
  supabase.from("journal_entries").select("id,source_type,description").eq("company_id",workspace.company.id).eq("status","posted").gte("entry_date",bounds.start).lte("entry_date",bounds.end),
  supabase.from("company_accounts").select("id,code,label,account_type").eq("company_id",workspace.company.id).eq("is_active",true).order("code")
 ]);if(e1||e2)throw new Error("Could not load financial reports.");
 const entryIds=(entries??[]).map(e=>e.id),lines=entryIds.length?(await supabase.from("journal_lines").select("company_account_id,debit,credit").in("journal_entry_id",entryIds)).data??[]:[];
 const sums=new Map<string,{debit:number;credit:number}>();for(const line of lines){const prev=sums.get(line.company_account_id)??{debit:0,credit:0};prev.debit+=Number(line.debit);prev.credit+=Number(line.credit);sums.set(line.company_account_id,prev)}
 const rows=(accounts??[]).map(a=>{const s=sums.get(a.id)??{debit:0,credit:0};return{...a,debit:s.debit,credit:s.credit}}).filter(r=>Math.abs(r.debit-r.credit)>.004||r.debit>0||r.credit>0);
 const revenues=rows.filter(r=>r.account_type==="revenue").map(r=>({...r,balance:r.credit-r.debit})).filter(r=>Math.abs(r.balance)>.004),expenses=rows.filter(r=>r.account_type==="expense").map(r=>({...r,balance:r.debit-r.credit})).filter(r=>Math.abs(r.balance)>.004);
 const revenueTotal=revenues.reduce((s,r)=>s+r.balance,0),expenseTotal=expenses.reduce((s,r)=>s+r.balance,0),result=revenueTotal-expenseTotal;
 const assets=rows.filter(r=>r.account_type==="asset").map(r=>({...r,balance:r.debit-r.credit})).filter(r=>Math.abs(r.balance)>.004),liabs=rows.filter(r=>["liability","equity"].includes(r.account_type)).map(r=>({...r,balance:r.credit-r.debit})).filter(r=>Math.abs(r.balance)>.004);
 const assetTotal=assets.reduce((s,r)=>s+r.balance,0),liabTotal=liabs.reduce((s,r)=>s+r.balance,0),balanceGap=assetTotal-(liabTotal+result),openingFound=(entries??[]).some(entry=>entry.source_type==="import"&&entry.description===`Opening balances · ${year}`);
 return <div className={styles.page}><div className={styles.intro}><div><p>Financial statements · FY {year}</p><h1>Profit & loss and balance sheet.</h1><span>Figures come only from posted journal lines between {bounds.start} and {bounds.end}. {openingFound?"The opening position is included.":"For a complete balance sheet, enter the opening position from the prior year."}</span></div><div className={styles.badge}>{entryIds.length} posted entries</div></div>
 <section className={styles.metrics}><article><BarChart3/><span>Revenue</span><strong>{money(revenueTotal,currency)}</strong></article><article><Scale/><span>Expenses</span><strong>{money(expenseTotal,currency)}</strong></article><article className={result>=0?styles.good:styles.bad}><span>Result · {year}</span><strong>{money(result,currency)}</strong></article><article><Table2/><span>Trial balance rows</span><strong>{rows.length}</strong></article></section>
 {!openingFound&&entryIds.length?<div className={styles.warning}>No opening-balance entry was found for FY {year}. The P&amp;L can still be correct, but the balance sheet may be incomplete until the prior year closing balances are entered under Accounting.</div>:null}
 <section className={styles.grid}><article className={styles.card}><div className={styles.head}><div><p>Profit & loss · {year}</p><h2>Performance</h2></div><strong>{money(result,currency)}</strong></div><h3>Revenue</h3>{revenues.map(r=><div className={styles.row} key={r.id}><span><b>{r.code}</b>{r.label}</span><strong>{money(r.balance,currency)}</strong></div>)}<div className={styles.total}><span>Total revenue</span><strong>{money(revenueTotal,currency)}</strong></div><h3>Expenses</h3>{expenses.map(r=><div className={styles.row} key={r.id}><span><b>{r.code}</b>{r.label}</span><strong>{money(r.balance,currency)}</strong></div>)}<div className={styles.total}><span>Total expenses</span><strong>{money(expenseTotal,currency)}</strong></div><div className={styles.result}><span>Result for the year</span><strong>{money(result,currency)}</strong></div></article>
 <article className={styles.card}><div className={styles.head}><div><p>Balance sheet · {bounds.end}</p><h2>Position</h2></div><strong>{Math.abs(balanceGap)<.01?"Balanced":"Provisional"}</strong></div><h3>Assets</h3>{assets.map(r=><div className={styles.row} key={r.id}><span><b>{r.code}</b>{r.label}</span><strong>{money(r.balance,currency)}</strong></div>)}<div className={styles.total}><span>Total assets</span><strong>{money(assetTotal,currency)}</strong></div><h3>Liabilities & equity</h3>{liabs.map(r=><div className={styles.row} key={r.id}><span><b>{r.code}</b>{r.label}</span><strong>{money(r.balance,currency)}</strong></div>)}<div className={styles.row}><span><b>142*</b>Current-year result (computed)</span><strong>{money(result,currency)}</strong></div><div className={styles.total}><span>Liabilities + equity + result</span><strong>{money(liabTotal+result,currency)}</strong></div>{Math.abs(balanceGap)>=.01?<div className={styles.warning}>Balance-sheet gap {money(balanceGap,currency)}. Check the opening position, equity and any missing balance-sheet accounts before year-end.</div>:null}</article></section>
 <article className={styles.trial}><div className={styles.head}><div><p>Trial balance · FY {year}</p><h2>Every active ledger account</h2></div></div><div className={styles.table}><div className={styles.th}><span>PCN</span><span>Account</span><span>Debit</span><span>Credit</span><span>Balance</span></div>{rows.map(r=><div className={styles.tr} key={r.id}><b>{r.code}</b><span>{r.label}</span><span>{money(r.debit,currency)}</span><span>{money(r.credit,currency)}</span><strong>{money(r.debit-r.credit,currency)}</strong></div>)}</div></article></div>
}
