"use server";

import { createHash } from "node:crypto";
import { revalidatePath } from "next/cache";
import { fiscalYearBounds, getActiveFiscalYear } from "@/lib/fiscal-year";
import { createClient } from "@/lib/supabase/server";
import { getWorkspace } from "@/lib/workspace";

export type ClosingState={status:"idle"|"success"|"error";message:string;filingId?:string};
type SnapshotRow={code?:string;label?:string;account_type?:string;debit?:number;credit?:number;balance?:number};
type LedgerSnapshot={trial_balance?:SnapshotRow[];profit_and_loss?:{result?:number};balance_sheet_control?:{current_year_result?:number}};
type AccountRow={id:string;code:string;label:string;account_type:string};

function refresh(){for(const p of ["/app","/app/year-end","/app/reports","/app/ecdf","/app/accounting","/app/transactions","/app/vat","/app/taxes"])revalidatePath(p)}
function extractedDate(raw:unknown){if(!raw||typeof raw!=="object")return null;const d=raw as Record<string,unknown>;for(const key of ["document_date","service_date","issue_date","date"]){const value=d[key];if(typeof value==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(value))return value}return null}
function round2(value:number){return Number(value.toFixed(2))}

async function ensureAccount(s:Awaited<ReturnType<typeof createClient>>,organizationId:string,companyId:string,code:string,label:string,accountType:"asset"|"liability"|"equity"|"expense"){
 const existing=await s.from("company_accounts").select("id,code,label,account_type").eq("company_id",companyId).eq("code",code).maybeSingle();
 if(existing.error)throw new Error(existing.error.message);if(existing.data)return existing.data as AccountRow;
 const created=await s.from("company_accounts").insert({organization_id:organizationId,company_id:companyId,code,label,account_type:accountType,is_active:true}).select("id,code,label,account_type").single();
 if(created.error||!created.data)throw new Error(created.error?.message??`Could not create account ${code}.`);return created.data as AccountRow;
}

export async function importPreviousClosingAction(_previous:ClosingState):Promise<ClosingState>{
 const w=await getWorkspace();if(!w.authenticated||!w.company||!w.organization||!w.capabilities?.hasCompanyYearEnd)return{status:"error",message:"This Company-only workflow is not available in the active workspace."};
 const s=await createClient(),year=await getActiveFiscalYear(w.company.fiscal_year_start_month),previousYear=year-1;
 const existing=await s.from("journal_entries").select("id",{count:"exact",head:true}).eq("company_id",w.company.id).eq("status","posted").eq("source_type","import").eq("description",`Opening balances · ${year}`);if(existing.error)return{status:"error",message:existing.error.message};if((existing.count??0)>0)return{status:"success",message:`FY ${year} already has an opening position.`};
 const prior=await s.from("filings").select("ledger_snapshot,snapshot_at").eq("company_id",w.company.id).eq("filing_type","ecdf_accounts").eq("period_label",String(previousYear)).order("snapshot_at",{ascending:false}).limit(1).maybeSingle();
 if(prior.error)return{status:"error",message:prior.error.message};if(!prior.data?.ledger_snapshot)return{status:"error",message:`No frozen FY ${previousYear} closing snapshot was found. Add the prior closing balances manually under Accounting.`};
 const snapshot=prior.data.ledger_snapshot as LedgerSnapshot,rows=Array.isArray(snapshot.trial_balance)?snapshot.trial_balance:[];if(!rows.length)return{status:"error",message:`The FY ${previousYear} snapshot has no trial balance to carry forward.`};
 const signedByCode=new Map<string,{signed:number;label:string;account_type:"asset"|"liability"|"equity"}>();const priorResult=Number(snapshot.profit_and_loss?.result??snapshot.balance_sheet_control?.current_year_result??0);let has142=false;
 for(const row of rows){const code=String(row.code??"").trim(),type=String(row.account_type??"");if(!code||!["asset","liability","equity"].includes(type))continue;const signed=Number.isFinite(Number(row.balance))?Number(row.balance):Number(row.debit??0)-Number(row.credit??0);if(Math.abs(signed)<.005)continue;if(code==="142"){has142=true;const current=signedByCode.get("1412")??{signed:0,label:"Retained earnings (allocated)",account_type:"equity" as const};current.signed+=signed;signedByCode.set("1412",current);continue}const current=signedByCode.get(code)??{signed:0,label:String(row.label??code),account_type:type as "asset"|"liability"|"equity"};current.signed+=signed;signedByCode.set(code,current)}
 if(!has142&&Math.abs(priorResult)>.005){const retained=signedByCode.get("1412")??{signed:0,label:"Retained earnings (allocated)",account_type:"equity" as const};retained.signed-=priorResult;signedByCode.set("1412",retained)}
 const lines:{account_id:string;debit:number;credit:number}[]=[];for(const[code,row]of signedByCode){if(Math.abs(row.signed)<.005)continue;let account:AccountRow;try{account=await ensureAccount(s,w.organization.id,w.company.id,code,row.label,row.account_type)}catch(error){return{status:"error",message:error instanceof Error?error.message:"Could not prepare the opening chart of accounts."}}lines.push({account_id:account.id,debit:row.signed>0?round2(row.signed):0,credit:row.signed<0?round2(-row.signed):0})}
 const debit=round2(lines.reduce((n,l)=>n+l.debit,0)),credit=round2(lines.reduce((n,l)=>n+l.credit,0));if(lines.length<2||Math.abs(debit-credit)>.01)return{status:"error",message:`FY ${previousYear} cannot be carried forward automatically because the extracted opening position does not balance (${debit.toFixed(2)} / ${credit.toFixed(2)}).`};
 const posted=await s.rpc("save_opening_balance_entry",{p_company_id:w.company.id,p_fiscal_year:year,p_lines:lines});if(posted.error)return{status:"error",message:posted.error.message};refresh();return{status:"success",message:`FY ${previousYear} closing balances were carried into FY ${year}. ${lines.length} balance-sheet accounts posted.`};
}

export async function applyPresentationReclassificationsAction(_previous:ClosingState):Promise<ClosingState>{
 const w=await getWorkspace();if(!w.authenticated||!w.company||!w.organization||!w.capabilities?.hasCompanyYearEnd)return{status:"error",message:"This Company-only workflow is not available in the active workspace."};const s=await createClient(),year=await getActiveFiscalYear(w.company.fiscal_year_start_month),bounds=fiscalYearBounds(year,w.company.fiscal_year_start_month);
 const entries=await s.from("journal_entries").select("id").eq("company_id",w.company.id).eq("status","posted").gte("entry_date",bounds.start).lte("entry_date",bounds.end);if(entries.error)return{status:"error",message:entries.error.message};const ids=(entries.data??[]).map(e=>e.id);if(!ids.length)return{status:"success",message:"No balance-sheet presentation adjustments are needed."};
 const accounts=await s.from("company_accounts").select("id,code,label,account_type").eq("company_id",w.company.id).eq("is_active",true);if(accounts.error)return{status:"error",message:accounts.error.message};const accountRows=(accounts.data??[]) as AccountRow[],byId=new Map(accountRows.map(a=>[a.id,a])),byCode=new Map(accountRows.map(a=>[a.code,a]));const linesResult=await s.from("journal_lines").select("company_account_id,debit,credit").in("journal_entry_id",ids);if(linesResult.error)return{status:"error",message:linesResult.error.message};const balances=new Map<string,number>();for(const l of linesResult.data??[]){const account=byId.get(l.company_account_id);if(!account)continue;balances.set(account.code,(balances.get(account.code)??0)+Number(l.debit)-Number(l.credit))}
 const mappings=[{source:"4712",target:"4212",targetLabel:"Receivables from shareholders (other than affiliated undertakings)"},{source:"46128",target:"42148",targetLabel:"ACD - other receivables"}],adjustmentLines:{account_id:string;debit:number;credit:number}[]=[];let total=0;
 for(const mapping of mappings){
  const amount=round2(balances.get(mapping.source)??0);if(amount<=.005)continue;const source=byCode.get(mapping.source);if(!source)continue;let target=byCode.get(mapping.target);
  if(!target){try{target=await ensureAccount(s,w.organization.id,w.company.id,mapping.target,mapping.targetLabel,"asset");byCode.set(mapping.target,target)}catch(error){return{status:"error",message:error instanceof Error?error.message:"Could not create a presentation account."}}}
  adjustmentLines.push({account_id:target.id,debit:amount,credit:0},{account_id:source.id,debit:0,credit:amount});total+=amount;
 }
 if(!adjustmentLines.length)return{status:"success",message:"Recognised balance-sheet presentation accounts are already clean."};const posted=await s.rpc("post_year_end_adjustment",{p_company_id:w.company.id,p_fiscal_year:year,p_description:`FY${year} balance-sheet presentation reclassifications`,p_lines:adjustmentLines});if(posted.error)return{status:"error",message:posted.error.message};refresh();return{status:"success",message:`Presentation reclassifications posted · ${new Intl.NumberFormat("en-LU",{style:"currency",currency:w.company.base_currency||"EUR"}).format(total)} moved to the correct asset-side accounts.`};
}

export async function postDepreciationAdjustmentAction(_previous:ClosingState,formData:FormData):Promise<ClosingState>{
 const w=await getWorkspace();if(!w.authenticated||!w.company||!w.organization||!w.capabilities?.hasCompanyYearEnd)return{status:"error",message:"This Company-only workflow is not available in the active workspace."};const assetId=String(formData.get("asset_account_id")??""),amount=round2(Number(formData.get("amount")));if(!assetId||!Number.isFinite(amount)||amount<=0)return{status:"error",message:"Choose a fixed-asset account and enter a depreciation amount greater than zero."};
 const s=await createClient(),year=await getActiveFiscalYear(w.company.fiscal_year_start_month),bounds=fiscalYearBounds(year,w.company.fiscal_year_start_month),asset=await s.from("company_accounts").select("id,code,label,account_type").eq("company_id",w.company.id).eq("id",assetId).eq("is_active",true).maybeSingle();if(asset.error||!asset.data)return{status:"error",message:asset.error?.message??"Asset account not found."};if(asset.data.account_type!=="asset"||!/^2/.test(asset.data.code))return{status:"error",message:"Depreciation can only be posted against a fixed-asset account."};
 const entries=await s.from("journal_entries").select("id").eq("company_id",w.company.id).eq("status","posted").gte("entry_date",bounds.start).lte("entry_date",bounds.end);if(entries.error)return{status:"error",message:entries.error.message};const ids=(entries.data??[]).map(e=>e.id);let currentBalance=0;if(ids.length){const assetLines=await s.from("journal_lines").select("debit,credit").eq("company_account_id",assetId).in("journal_entry_id",ids);if(assetLines.error)return{status:"error",message:assetLines.error.message};currentBalance=round2((assetLines.data??[]).reduce((n,l)=>n+Number(l.debit)-Number(l.credit),0))}if(amount>currentBalance+.005)return{status:"error",message:`Depreciation cannot exceed the current ${asset.data.label} carrying value (${currentBalance.toFixed(2)}).`};
 let expense:AccountRow;try{expense=await ensureAccount(s,w.organization.id,w.company.id,"6333","Depreciation / value adjustments on other installations, equipment and furniture","expense")}catch(error){return{status:"error",message:error instanceof Error?error.message:"Could not prepare the depreciation account."}}
 const posted=await s.rpc("post_year_end_adjustment",{p_company_id:w.company.id,p_fiscal_year:year,p_description:`FY${year} depreciation · ${asset.data.label}`,p_lines:[{account_id:expense.id,debit:amount,credit:0},{account_id:asset.data.id,debit:0,credit:amount}]});if(posted.error)return{status:"error",message:posted.error.message};refresh();return{status:"success",message:`Depreciation posted · ${asset.data.label} reduced by ${new Intl.NumberFormat("en-LU",{style:"currency",currency:w.company.base_currency||"EUR"}).format(amount)}.`};
}

export async function createClosingSnapshot(_previous:ClosingState):Promise<ClosingState>{
 const w=await getWorkspace();if(!w.authenticated||!w.userId||!w.company||!w.organization||!w.capabilities?.hasCompanyYearEnd)return{status:"error",message:"This Company-only workflow is not available in the active workspace."};
 const s=await createClient(),year=await getActiveFiscalYear(w.company.fiscal_year_start_month),bounds=fiscalYearBounds(year,w.company.fiscal_year_start_month),from=bounds.start,to=bounds.end;
 const [pending,bank,drafts,docResult,vat,entries,accounts]=await Promise.all([
  s.from("source_transactions").select("id",{count:"exact",head:true}).eq("company_id",w.company.id).in("classification_status",["unclassified","review","classified"]).gte("occurred_on",from).lte("occurred_on",to),
  s.from("bank_transactions").select("id",{count:"exact",head:true}).eq("company_id",w.company.id).neq("match_status","matched").neq("match_status","ignored").gte("booking_date",from).lte("booking_date",to),
  s.from("sales_invoices").select("id",{count:"exact",head:true}).eq("company_id",w.company.id).eq("status","draft").gte("service_date",from).lte("service_date",to),
  s.from("documents").select("id,extracted_data,extraction_status").eq("company_id",w.company.id).in("extraction_status",["failed","needs_review","processing"]),
  s.from("source_transactions").select("id",{count:"exact",head:true}).eq("company_id",w.company.id).neq("classification_status","posted").gt("vat_amount",0).gte("occurred_on",from).lte("occurred_on",to),
  s.from("journal_entries").select("id,entry_number,entry_date,status,source_type,description").eq("company_id",w.company.id).eq("status","posted").gte("entry_date",from).lte("entry_date",to).order("entry_number"),
  s.from("company_accounts").select("id,code,label,account_type").eq("company_id",w.company.id).eq("is_active",true).order("code")
 ]);
 if([pending,bank,drafts,docResult,vat,entries,accounts].some(r=>r.error))return{status:"error",message:"Zuelen could not complete the closing checks."};
 const docs=(docResult.data??[]).filter(doc=>{const date=extractedDate(doc.extracted_data);return date!==null&&date>=from&&date<=to});
 const blockers=(pending.count??0)+(bank.count??0)+(drafts.count??0)+docs.length+(vat.count??0);if(blockers>0)return{status:"error",message:`${blockers} closing blocker${blockers===1?" remains":"s remain"} in FY ${year}. Clear the Year-end checklist first.`};
 const entryIds=(entries.data??[]).map(e=>e.id),lines=entryIds.length?(await s.from("journal_lines").select("journal_entry_id,company_account_id,debit,credit,currency").in("journal_entry_id",entryIds)).data??[]:[];
 const entryBalance=new Map<string,{d:number;c:number}>(),accountBalance=new Map<string,{d:number;c:number}>();for(const l of lines){const e=entryBalance.get(l.journal_entry_id)??{d:0,c:0};e.d+=Number(l.debit);e.c+=Number(l.credit);entryBalance.set(l.journal_entry_id,e);const a=accountBalance.get(l.company_account_id)??{d:0,c:0};a.d+=Number(l.debit);a.c+=Number(l.credit);accountBalance.set(l.company_account_id,a)}
 if([...entryBalance.values()].some(x=>Math.abs(x.d-x.c)>.005))return{status:"error",message:"At least one posted journal entry is unbalanced. Closing is blocked."};
 const trialBalance=(accounts.data??[]).map(a=>{const x=accountBalance.get(a.id)??{d:0,c:0};return{code:a.code,label:a.label,account_type:a.account_type,debit:Number(x.d.toFixed(2)),credit:Number(x.c.toFixed(2)),balance:Number((x.d-x.c).toFixed(2))}}).filter(r=>r.debit||r.credit);
 const abnormalLiabilities=trialBalance.filter(r=>r.account_type==="liability"&&r.balance>.01);if(abnormalLiabilities.length)return{status:"error",message:`${abnormalLiabilities.length} liability balance${abnormalLiabilities.length===1?" is":"s are"} sitting on the debit side. Review the Balance-sheet presentation step before closing.`};
 const revenue=trialBalance.filter(r=>r.account_type==="revenue").reduce((n,r)=>n+r.credit-r.debit,0),expenses=trialBalance.filter(r=>r.account_type==="expense").reduce((n,r)=>n+r.debit-r.credit,0),result=Number((revenue-expenses).toFixed(2));
 const assets=trialBalance.filter(r=>r.account_type==="asset").reduce((n,r)=>n+r.debit-r.credit,0),liabilitiesAndEquity=trialBalance.filter(r=>r.account_type==="liability"||r.account_type==="equity").reduce((n,r)=>n+r.credit-r.debit,0),balanceGap=Number((assets-(liabilitiesAndEquity+result)).toFixed(2));
 const snapshot={company_id:w.company.id,fiscal_year:year,period_start:from,period_end:to,entry_count:entryIds.length,opening_position_present:(entries.data??[]).some(e=>e.source_type==="import"&&e.description===`Opening balances · ${year}`),entries:(entries.data??[]).map(e=>({id:e.id,number:e.entry_number,date:e.entry_date})),trial_balance:trialBalance,profit_and_loss:{revenue:Number(revenue.toFixed(2)),expenses:Number(expenses.toFixed(2)),result},balance_sheet_control:{assets:Number(assets.toFixed(2)),liabilities_and_equity:Number(liabilitiesAndEquity.toFixed(2)),current_year_result:result,gap:balanceGap},presentation_control:{abnormal_debit_liability_count:0}};
 if(Math.abs(balanceGap)>.01)return{status:"error",message:`The ${year} balance sheet is not balanced (${balanceGap.toFixed(2)} gap). Enter/correct the opening position before freezing the filing snapshot.`};
 const checksum=createHash("sha256").update(JSON.stringify(snapshot)).digest("hex"),now=new Date().toISOString();
 const{data:filing,error}=await s.from("filings").insert({organization_id:w.organization.id,company_id:w.company.id,filing_type:"ecdf_accounts",period_label:String(year),status:"draft",schema_version:null,rules_version:"LU-2026.1|PCN2020",payload:{stage:"closing_snapshot",ecdf:{status:"schema_required"}},ledger_snapshot:snapshot,period_start:from,period_end:to,snapshot_at:now,ledger_checksum:checksum,export_status:"schema_required",created_by:w.userId}).select("id").single();
 if(error||!filing)return{status:"error",message:error?.message??"The closing snapshot could not be created."};
 await s.rpc("set_accounting_period_status",{p_company_id:w.company.id,p_fiscal_year:year,p_status:"soft_closed"});refresh();
 return{status:"success",message:`FY ${year} closing snapshot created · ${trialBalance.length} trial-balance accounts frozen for review.`,filingId:filing.id};
}

export async function hardCloseYearAction(_previous:ClosingState,formData:FormData):Promise<ClosingState>{
 const w=await getWorkspace();if(!w.authenticated||!w.company||!w.capabilities?.hasCompanyYearEnd)return{status:"error",message:"This Company-only workflow is not available in the active workspace."};const activeYear=await getActiveFiscalYear(w.company.fiscal_year_start_month),year=Number(formData.get("year"));const confirmation=String(formData.get("confirmation")??"").trim();if(year!==activeYear)return{status:"error",message:`Switch to financial year ${year} before locking it.`};if(!Number.isInteger(year)||confirmation!==`LOCK ${year}`)return{status:"error",message:`Type LOCK ${year} exactly to confirm.`};
 const s=await createClient();const{error}=await s.rpc("set_accounting_period_status",{p_company_id:w.company.id,p_fiscal_year:year,p_status:"hard_closed"});if(error)return{status:"error",message:error.message};refresh();return{status:"success",message:`${year} is hard-closed. New postings into this period are now blocked.`};
}
