import { AlertTriangle, CheckCircle2, CircleDashed, LockKeyhole } from "lucide-react";
import Link from "next/link";
import { redirect } from "next/navigation";
import { ClosingSnapshotButton } from "@/components/closing-snapshot-button";
import { YearLockButton } from "@/components/year-lock-button";
import styles from "@/components/year-end.module.css";
import { fiscalYearBounds, getActiveFiscalYear } from "@/lib/fiscal-year";
import { createClient } from "@/lib/supabase/server";
import { getWorkspace } from "@/lib/workspace";
export const dynamic="force-dynamic";
function money(v:number,c:string){return new Intl.NumberFormat("en-LU",{style:"currency",currency:c,minimumFractionDigits:2}).format(v)}
function extractedDate(raw:unknown){if(!raw||typeof raw!=="object")return null;const d=raw as Record<string,unknown>;for(const key of ["document_date","service_date","issue_date","date"]){const value=d[key];if(typeof value==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(value))return value}return null}
export default async function YearEndPage(){const w=await getWorkspace();if(!w.authenticated)redirect("/sign-in");if(!w.company)redirect("/setup");const s=await createClient(),year=await getActiveFiscalYear(w.company.fiscal_year_start_month),bounds=fiscalYearBounds(year,w.company.fiscal_year_start_month),currency=w.company.base_currency||"EUR",from=bounds.start,to=bounds.end;
 const [pending,bank,drafts,issuedResult,paymentsResult,docResult,vat,entries,shareAccounts,snapshot,period]=await Promise.all([
  s.from("source_transactions").select("id",{count:"exact",head:true}).eq("company_id",w.company.id).in("classification_status",["unclassified","review","classified"]).gte("occurred_on",from).lte("occurred_on",to),
  s.from("bank_transactions").select("id",{count:"exact",head:true}).eq("company_id",w.company.id).neq("match_status","matched").neq("match_status","ignored").gte("booking_date",from).lte("booking_date",to),
  s.from("sales_invoices").select("id",{count:"exact",head:true}).eq("company_id",w.company.id).eq("status","draft").gte("service_date",from).lte("service_date",to),
  s.from("sales_invoices").select("id,total").eq("company_id",w.company.id).eq("status","issued").gte("service_date",from).lte("service_date",to),
  s.from("invoice_payments").select("invoice_id,amount,paid_on").eq("company_id",w.company.id).lte("paid_on",to),
  s.from("documents").select("id,extracted_data,extraction_status").eq("company_id",w.company.id).in("extraction_status",["failed","needs_review","processing"]),
  s.from("source_transactions").select("id",{count:"exact",head:true}).eq("company_id",w.company.id).neq("classification_status","posted").gt("vat_amount",0).gte("occurred_on",from).lte("occurred_on",to),
  s.from("journal_entries").select("id,source_type,description").eq("company_id",w.company.id).eq("status","posted").gte("entry_date",from).lte("entry_date",to),
  s.from("company_accounts").select("id,code,label").eq("company_id",w.company.id).in("code",["4212","4712"]),
  s.from("filings").select("id,snapshot_at,ledger_checksum").eq("company_id",w.company.id).eq("filing_type","ecdf_accounts").eq("period_label",String(year)).order("created_at",{ascending:false}).limit(1).maybeSingle(),
  s.from("accounting_periods").select("id,status,locked_at").eq("company_id",w.company.id).eq("starts_on",from).eq("ends_on",to).maybeSingle()
 ]);
 const entryIds=entries.data?.map(e=>e.id)??[],shareIds=shareAccounts.data?.map(a=>a.id)??[];let imbalance=0,shareBalance=0;if(entryIds.length){const{data:lines}=await s.from("journal_lines").select("journal_entry_id,company_account_id,debit,credit").in("journal_entry_id",entryIds);const sums=new Map<string,{d:number;c:number}>();for(const l of lines??[]){const x=sums.get(l.journal_entry_id)??{d:0,c:0};x.d+=Number(l.debit);x.c+=Number(l.credit);sums.set(l.journal_entry_id,x);if(shareIds.includes(l.company_account_id))shareBalance+=Number(l.credit)-Number(l.debit)}imbalance=[...sums.values()].filter(x=>Math.abs(x.d-x.c)>.005).length}
 const paidByInvoice=new Map<string,number>();for(const payment of paymentsResult.data??[])paidByInvoice.set(payment.invoice_id,(paidByInvoice.get(payment.invoice_id)??0)+Number(payment.amount));const outstanding=(issuedResult.data??[]).reduce((sum,i)=>sum+Math.max(0,Number(i.total)-(paidByInvoice.get(i.id)??0)),0),outstandingCount=(issuedResult.data??[]).filter(i=>Math.max(0,Number(i.total)-(paidByInvoice.get(i.id)??0))>.005).length,docs=(docResult.data??[]).filter(doc=>{const date=extractedDate(doc.extracted_data);return date!==null&&date>=from&&date<=to}),openingFound=(entries.data??[]).some(e=>e.source_type==="import"&&e.description===`Opening balances · ${year}`),checks=[
  {label:"Transactions reviewed",value:pending.count??0,ok:(pending.count??0)===0,href:"/app/transactions",detail:`${pending.count??0} still need classification in ${year}`},
  {label:"Bank reconciliation",value:bank.count??0,ok:(bank.count??0)===0,href:"/app/banking",detail:(bank.count??0)===0?"All active bank movements are reconciled":`${bank.count??0} ${year} bank movements need reconciliation`},
  {label:"Draft invoices",value:drafts.count??0,ok:(drafts.count??0)===0,href:"/app/invoices",detail:`${drafts.count??0} ${year} drafts remain outside the ledger`},
  {label:"VAT review",value:vat.count??0,ok:(vat.count??0)===0,href:"/app/vat",detail:`${vat.count??0} VAT-bearing items are unresolved`},
  {label:"Document review",value:docs.length,ok:docs.length===0,href:"/app/documents",detail:`${docs.length} dated ${year} documents need extraction/review`},
  {label:"Ledger integrity",value:imbalance,ok:imbalance===0,href:"/app/accounting",detail:imbalance?`${imbalance} posted entries are not balanced`:"Every posted entry balances"}
 ];const ready=checks.every(c=>c.ok),hasSnapshot=Boolean(snapshot.data),hardClosed=period.data?.status==="hard_closed";
 return <div className={styles.page}><div className={styles.intro}><div><p>Year-end · FY {year}</p><h1>{hardClosed?"The year is locked.":hasSnapshot?"Closing snapshot frozen.":ready?"The books are structurally ready.":"Close the gaps before you close the year."}</h1><span>{hardClosed?"This period no longer accepts operational postings. Corrections require a controlled accounting process outside the closed period.":hasSnapshot?"Annual-account preparation is anchored to a frozen ledger snapshot.":`Compta checks ${year} evidence, reconciliation and ledger integrity before allowing a close.`}</span></div><div className={`${styles.ready} ${(ready||hasSnapshot)?styles.readyGood:""}`}>{(ready||hasSnapshot)?<CheckCircle2/>:<CircleDashed/>}{hardClosed?"Hard closed":hasSnapshot?"Snapshot frozen":ready?"Ready for closing review":"Closing blockers remain"}</div></div>
 {!openingFound&&entryIds.length?<div className={styles.notice}><AlertTriangle/><span>No opening position is posted for FY {year}. P&amp;L may be usable, but the closing snapshot will refuse to freeze an unbalanced balance sheet. Add the prior-year closing balances under Accounting.</span></div>:null}
 <section className={styles.checks}>{checks.map(c=><Link href={c.href} className={styles.check} key={c.label}><span className={c.ok?styles.ok:styles.warn}>{c.ok?<CheckCircle2/>:<AlertTriangle/>}</span><div><strong>{c.label}</strong><small>{c.detail}</small></div><b>{c.ok?"Clear":c.value}</b></Link>)}</section>
 <section className={styles.grid}><article><p>Receivables at {to}</p><h2>{money(outstanding,currency)}</h2><span>{outstandingCount} {year} issued invoices were not fully settled by period end.</span></article><article><p>Shareholder current account</p><h2>{money(Math.abs(shareBalance),currency)}</h2><span>{shareBalance>0?"Company owes the shareholder.":shareBalance<0?"Shareholder owes the company.":"No net shareholder current-account balance detected."}</span></article><article><p>Posted journal</p><h2>{entryIds.length}</h2><span>Entries included in the FY {year} integrity review.</span></article></section>
 <article className={styles.lock}><LockKeyhole/><div><strong>{hardClosed?"Period locked":hasSnapshot?"Frozen filing basis":"Controlled closing snapshot"}</strong><p>{hardClosed?`Locked ${period.data?.locked_at?new Date(period.data.locked_at).toLocaleString("en-LU"):""}. Posted history remains queryable and auditable.`:hasSnapshot?"The snapshot feeds annual accounts and filing preparation. When your review is final, hard-close the year to prevent accidental back-posting.":`When every FY ${year} blocker is clear, Compta freezes the trial balance, P&L and balance-sheet control into a filing snapshot and soft-closes the period.`}</p>{hardClosed?<Link href="/app/ecdf" className={styles.closeButton}>Open annual-account preparation</Link>:hasSnapshot?<><Link href="/app/ecdf" className={styles.closeButton}>Review annual accounts</Link><YearLockButton year={year}/></>:<ClosingSnapshotButton ready={ready}/>}</div></article></div>}
