import { AlertTriangle, CheckCircle2, CircleDashed, LockKeyhole } from "lucide-react";
import Link from "next/link";
import { redirect } from "next/navigation";
import { ClosingSnapshotButton } from "@/components/closing-snapshot-button";
import { YearEndAdjustments } from "@/components/year-end-adjustments";
import { YearLockButton } from "@/components/year-lock-button";
import styles from "@/components/year-end.module.css";
import { fiscalYearBounds, getActiveFiscalYear } from "@/lib/fiscal-year";
import { createClient } from "@/lib/supabase/server";
import { getWorkspace } from "@/lib/workspace";
export const dynamic="force-dynamic";
type Account={id:string;code:string;label:string;account_type:string};
function money(v:number,c:string){return new Intl.NumberFormat("en-LU",{style:"currency",currency:c,minimumFractionDigits:2}).format(v)}
function extractedDate(raw:unknown){if(!raw||typeof raw!=="object")return null;const d=raw as Record<string,unknown>;for(const key of ["document_date","service_date","issue_date","date"]){const value=d[key];if(typeof value==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(value))return value}return null}
export default async function YearEndPage(){const w=await getWorkspace();if(!w.authenticated)redirect("/sign-in");if(!w.company)redirect("/setup");const s=await createClient(),year=await getActiveFiscalYear(w.company.fiscal_year_start_month),bounds=fiscalYearBounds(year,w.company.fiscal_year_start_month),currency=w.company.base_currency||"EUR",from=bounds.start,to=bounds.end;
 const [pending,bank,drafts,issuedResult,paymentsResult,docResult,vat,entries,accountsResult,snapshot,period,previousSnapshot]=await Promise.all([
  s.from("source_transactions").select("id",{count:"exact",head:true}).eq("company_id",w.company.id).in("classification_status",["unclassified","review","classified"]).gte("occurred_on",from).lte("occurred_on",to),
  s.from("bank_transactions").select("id",{count:"exact",head:true}).eq("company_id",w.company.id).neq("match_status","matched").neq("match_status","ignored").gte("booking_date",from).lte("booking_date",to),
  s.from("sales_invoices").select("id",{count:"exact",head:true}).eq("company_id",w.company.id).eq("status","draft").gte("service_date",from).lte("service_date",to),
  s.from("sales_invoices").select("id,total").eq("company_id",w.company.id).eq("status","issued").gte("service_date",from).lte("service_date",to),
  s.from("invoice_payments").select("invoice_id,amount,paid_on").eq("company_id",w.company.id).lte("paid_on",to),
  s.from("documents").select("id,extracted_data,extraction_status").eq("company_id",w.company.id).in("extraction_status",["failed","needs_review","processing"]),
  s.from("source_transactions").select("id",{count:"exact",head:true}).eq("company_id",w.company.id).neq("classification_status","posted").gt("vat_amount",0).gte("occurred_on",from).lte("occurred_on",to),
  s.from("journal_entries").select("id,source_type,description").eq("company_id",w.company.id).eq("status","posted").gte("entry_date",from).lte("entry_date",to),
  s.from("company_accounts").select("id,code,label,account_type").eq("company_id",w.company.id).eq("is_active",true).order("code"),
  s.from("filings").select("id,snapshot_at,ledger_checksum").eq("company_id",w.company.id).eq("filing_type","ecdf_accounts").eq("period_label",String(year)).order("created_at",{ascending:false}).limit(1).maybeSingle(),
  s.from("accounting_periods").select("id,status,locked_at").eq("company_id",w.company.id).eq("starts_on",from).eq("ends_on",to).maybeSingle(),
  s.from("filings").select("id,snapshot_at").eq("company_id",w.company.id).eq("filing_type","ecdf_accounts").eq("period_label",String(year-1)).order("snapshot_at",{ascending:false}).limit(1).maybeSingle()
 ]);
 const entriesData=entries.data??[],accounts=(accountsResult.data??[]) as Account[],entryIds=entriesData.map(e=>e.id),accountMap=new Map(accounts.map(a=>[a.id,a]));let imbalance=0,shareBalance=0;const balances=new Map<string,number>();if(entryIds.length){const{data:lines}=await s.from("journal_lines").select("journal_entry_id,company_account_id,debit,credit").in("journal_entry_id",entryIds);const sums=new Map<string,{d:number;c:number}>();for(const l of lines??[]){const debit=Number(l.debit),credit=Number(l.credit),x=sums.get(l.journal_entry_id)??{d:0,c:0};x.d+=debit;x.c+=credit;sums.set(l.journal_entry_id,x);const account=accountMap.get(l.company_account_id);if(account){balances.set(account.code,(balances.get(account.code)??0)+debit-credit);if(account.code==="4212"||account.code==="4712")shareBalance+=credit-debit}}imbalance=[...sums.values()].filter(x=>Math.abs(x.d-x.c)>.005).length}
 const paidByInvoice=new Map<string,number>();for(const payment of paymentsResult.data??[])paidByInvoice.set(payment.invoice_id,(paidByInvoice.get(payment.invoice_id)??0)+Number(payment.amount));const outstanding=(issuedResult.data??[]).reduce((sum,i)=>sum+Math.max(0,Number(i.total)-(paidByInvoice.get(i.id)??0)),0),outstandingCount=(issuedResult.data??[]).filter(i=>Math.max(0,Number(i.total)-(paidByInvoice.get(i.id)??0))>.005).length,docs=(docResult.data??[]).filter(doc=>{const date=extractedDate(doc.extracted_data);return date!==null&&date>=from&&date<=to}),openingFound=entriesData.some(e=>e.source_type==="import"&&e.description===`Opening balances · ${year}`);
 const presentationIssues=accounts.filter(a=>a.account_type==="liability"&&(balances.get(a.code)??0)>.01).map(a=>({code:a.code,label:a.label,amount:Number((balances.get(a.code)??0).toFixed(2)),automatic:a.code==="4712"||a.code==="46128"})),depreciationTotal=Number(Math.max(0,balances.get("6333")??0).toFixed(2)),fixedAssets=accounts.filter(a=>a.account_type==="asset"&&/^(21|22)/.test(a.code)&&(balances.get(a.code)??0)>.005).map(a=>({id:a.id,code:a.code,label:a.label,balance:Number((balances.get(a.code)??0).toFixed(2))}));
 const revenue=accounts.filter(a=>a.account_type==="revenue").reduce((n,a)=>n-(balances.get(a.code)??0),0),expenses=accounts.filter(a=>a.account_type==="expense").reduce((n,a)=>n+(balances.get(a.code)??0),0),result=revenue-expenses,assetsTotal=accounts.filter(a=>a.account_type==="asset").reduce((n,a)=>n+(balances.get(a.code)??0),0),liabilitiesEquity=accounts.filter(a=>a.account_type==="liability"||a.account_type==="equity").reduce((n,a)=>n-(balances.get(a.code)??0),0),balanceGap=Number((assetsTotal-(liabilitiesEquity+result)).toFixed(2)),continuityOk=openingFound||!previousSnapshot.data;
 const checks=[
  {label:"Transactions reviewed",value:pending.count??0,ok:(pending.count??0)===0,href:"/app/transactions",detail:`${pending.count??0} still need classification in ${year}`},
  {label:"Bank reconciliation",value:bank.count??0,ok:(bank.count??0)===0,href:"/app/banking",detail:(bank.count??0)===0?"All active bank movements are reconciled":`${bank.count??0} ${year} bank movements need reconciliation`},
  {label:"Draft invoices",value:drafts.count??0,ok:(drafts.count??0)===0,href:"/app/invoices",detail:`${drafts.count??0} ${year} drafts remain outside the ledger`},
  {label:"VAT review",value:vat.count??0,ok:(vat.count??0)===0,href:"/app/vat",detail:`${vat.count??0} VAT-bearing items are unresolved`},
  {label:"Document review",value:docs.length,ok:docs.length===0,href:"/app/documents",detail:`${docs.length} dated ${year} documents need extraction/review`},
  {label:"Ledger integrity",value:imbalance,ok:imbalance===0,href:"/app/accounting",detail:imbalance?`${imbalance} posted entries are not balanced`:"Every posted entry balances"},
  {label:"Opening continuity",value:openingFound?0:1,ok:continuityOk,href:"/app/accounting",detail:openingFound?"Prior closing balances are carried into this year":previousSnapshot.data?`FY ${year-1} snapshot exists but has not been carried forward`:"No prior Compta snapshot; add an opening position if this is not the first year"},
  {label:"Balance-sheet presentation",value:presentationIssues.length,ok:presentationIssues.length===0,href:"/app/year-end",detail:presentationIssues.length?`${presentationIssues.length} debit-side liability balance${presentationIssues.length===1?"":"s"} need presentation review`:"Liability balances are presented on the correct side"},
  {label:"Balance-sheet control",value:Math.abs(balanceGap),ok:Math.abs(balanceGap)<=.01,href:"/app/reports",detail:Math.abs(balanceGap)<=.01?"Assets equal liabilities, equity and current-year result":`${money(Math.abs(balanceGap),currency)} closing balance-sheet gap`}
 ];const ready=checks.every(c=>c.ok),hasSnapshot=Boolean(snapshot.data),hardClosed=period.data?.status==="hard_closed",adjustmentsDisabled=hasSnapshot||hardClosed;
 return <div className={styles.page}><div className={styles.intro}><div><p>Year-end · FY {year}</p><h1>{hardClosed?"The year is locked.":hasSnapshot?"Closing snapshot frozen.":ready?"The books are ready to freeze.":"Close the gaps before you close the year."}</h1><span>{hardClosed?"This period no longer accepts operational postings. Corrections require a controlled accounting process outside the closed period.":hasSnapshot?"Annual-account preparation is anchored to a frozen ledger snapshot.":`Compta checks ${year} evidence, reconciliation, opening continuity, closing adjustments and ledger integrity before allowing a close.`}</span></div><div className={`${styles.ready} ${(ready||hasSnapshot)?styles.readyGood:""}`}>{(ready||hasSnapshot)?<CheckCircle2/>:<CircleDashed/>}{hardClosed?"Hard closed":hasSnapshot?"Snapshot frozen":ready?"Ready to freeze":"Closing blockers remain"}</div></div>
 {!openingFound&&entryIds.length&&!previousSnapshot.data?<div className={styles.notice}><AlertTriangle/><span>No opening position is posted for FY {year}. If this is the company's first financial year, that can be valid. Otherwise, add the prior-year closing balances under Accounting before freezing.</span></div>:null}
 <section className={styles.checks}>{checks.map(c=><Link href={c.href} className={styles.check} key={c.label}><span className={c.ok?styles.ok:styles.warn}>{c.ok?<CheckCircle2/>:<AlertTriangle/>}</span><div><strong>{c.label}</strong><small>{c.detail}</small></div><b>{c.ok?"Clear":typeof c.value==="number"&&c.value%1!==0?money(c.value,currency):c.value}</b></Link>)}</section>
 <YearEndAdjustments year={year} currency={currency} openingFound={openingFound} previousSnapshotYear={previousSnapshot.data?year-1:null} presentationIssues={presentationIssues} depreciationTotal={depreciationTotal} assets={fixedAssets} disabled={adjustmentsDisabled}/>
 <section className={styles.grid}><article><p>Receivables at {to}</p><h2>{money(outstanding,currency)}</h2><span>{outstandingCount} {year} issued invoices were not fully settled by period end.</span></article><article><p>Shareholder current account</p><h2>{money(Math.abs(shareBalance),currency)}</h2><span>{shareBalance>0?"Company owes the shareholder.":shareBalance<0?"Shareholder owes the company.":"No net shareholder current-account balance detected."}</span></article><article><p>Closing balance sheet</p><h2>{money(assetsTotal,currency)}</h2><span>{Math.abs(balanceGap)<=.01?`Balanced · current-year result ${money(result,currency)}`:`Control gap ${money(Math.abs(balanceGap),currency)}`}</span></article><article><p>Posted journal</p><h2>{entryIds.length}</h2><span>Entries included in the FY {year} integrity review.</span></article></section>
 <article className={styles.lock}><LockKeyhole/><div><strong>{hardClosed?"Period locked":hasSnapshot?"Frozen filing basis":"Controlled closing snapshot"}</strong><p>{hardClosed?`Locked ${period.data?.locked_at?new Date(period.data.locked_at).toLocaleString("en-LU"):""}. Posted history remains queryable and auditable.`:hasSnapshot?"The snapshot feeds annual accounts and filing preparation. When your review is final, hard-close the year to prevent accidental back-posting.":`When every FY ${year} blocker is clear, Compta freezes the trial balance, P&L and balance-sheet control into a filing snapshot and soft-closes the period.`}</p>{hardClosed?<Link href="/app/ecdf" className={styles.closeButton}>Open annual-account preparation</Link>:hasSnapshot?<><Link href="/app/ecdf" className={styles.closeButton}>Review annual accounts</Link><YearLockButton year={year}/></>:<ClosingSnapshotButton ready={ready}/>}</div></article></div>}
